// src/views/Editor/Toolbar/ElementStylePanel/ChartStylePanel/index.vue
<template>
  <div class="chart-style-panel">
    <Button class="full-width-btn" @click="openDataEditor()">
      <i-icon-park-outline:edit /> {{ $t('elementStyle.editChart') }}
    </Button>

    <Divider />

    <template v-if="['bar', 'column', 'area', 'line'].includes(handleChartElement.chartType)">
      <div class="row">
        <Checkbox 
          @update:value="value => updateOptions({ stack: value })" 
          :value="stack"
          style="flex: 2;"
        >{{ $t('elementStyle.stacked') }}</Checkbox>
        <Checkbox 
          v-if="handleChartElement.chartType === 'line'"
          @update:value="value => updateOptions({ lineSmooth: value })" 
          :value="lineSmooth"
          style="flex: 3;"
        >{{ $t('elementStyle.smooth') }}</Checkbox>
      </div>
  
      <Divider />
    </template>

    <div class="row">
      <div style="width: 40%;">{{ $t('elementStyle.chartBackground') }}</div>
      <Popover trigger="click" style="width: 60%;">
        <template #content>
          <ColorPicker
            :modelValue="fill"
            @update:modelValue="value => updateElement({ fill: value })"
          />
        </template>
        <ColorButton :color="fill" />
      </Popover>
    </div>
    <div class="row">
      <div style="width: 40%;">{{ $t('elementStyle.axisAndText') }}</div>
      <Popover trigger="click" style="width: 60%;">
        <template #content>
          <ColorPicker
            :modelValue="textColor"
            @update:modelValue="value => updateElement({ textColor: value })"
          />
        </template>
        <ColorButton :color="textColor" />
      </Popover>
    </div>
    <div class="row">
      <div style="width: 40%;">{{ $t('elementStyle.gridColor') }}</div>
      <Popover trigger="click" style="width: 60%;">
        <template #content>
          <ColorPicker
            :modelValue="lineColor"
            @update:modelValue="value => updateElement({ lineColor: value })"
          />
        </template>
        <ColorButton :color="lineColor" />
      </Popover>
    </div>

    <div class="row">
      <div style="width: 40%;">{{ $t('elementStyle.chartTheme') }}</div>
      <Popover trigger="click" v-model:value="themesVisible" style="width: 60%;">
        <template #content>
          <div class="themes">
            <div class="label">{{ $t('elementStyle.presetChartThemes') }}</div>
            <div class="preset-themes">
              <div class="preset-theme" v-for="(item, index) in CHART_PRESET_THEMES" :key="index" @click="setThemeColors(item)">
                <div 
                  class="preset-theme-color"
                  v-for="color in item" 
                  :key="color" 
                  :style="{ backgroundColor: color }" 
                ></div>
              </div>
            </div>
            <div class="label">{{ $t('elementStyle.slideTheme') }}</div>
            <div class="preset-themes" :style="{ marginBottom: '-10px' }">
              <div class="preset-theme" @click="setThemeColors(theme.themeColors)">
                <div 
                  class="preset-theme-color"
                  v-for="color in theme.themeColors" 
                  :key="color" 
                  :style="{ backgroundColor: color }" 
                ></div>
              </div>
            </div>
            <Divider :margin="10" />
            <Button class="full-width-btn" @click="themesVisible = false; themeColorsSettingVisible = true">{{ $t('elementStyle.customColors') }}</Button>
          </div>
        </template>
        <ColorListButton :colors="themeColors" />
      </Popover>
    </div>

    <Divider />

    <ElementOutline />

    <Modal
      v-model:visible="themeColorsSettingVisible" 
      :width="310"
      @closed="themeColorsSettingVisible = false"
    >
      <ThemeColorsSetting :colors="themeColors" @update="colors => setThemeColors(colors)" />
    </Modal>
  </div>
</template>

<script lang="ts" setup>
import { ref, watch, type Ref } from 'vue'
import { storeToRefs } from 'pinia'
import { useMainStore, useSlidesStore } from '@/store'
import type { ChartOptions, PPTChartElement } from '@/types/slides'
import emitter, { EmitterEvents } from '@/utils/emitter'
import useHistorySnapshot from '@/hooks/useHistorySnapshot'
import { CHART_PRESET_THEMES } from '@/configs/chart'

import ElementOutline from '../../common/ElementOutline.vue'
import ThemeColorsSetting from './ThemeColorsSetting.vue'
import ColorButton from '@/components/ColorButton.vue'
import ColorListButton from '@/components/ColorListButton.vue'
import ColorPicker from '@/components/ColorPicker/index.vue'
import Modal from '@/components/Modal.vue'
import Divider from '@/components/Divider.vue'
import Checkbox from '@/components/Checkbox.vue'
import Button from '@/components/Button.vue'
import Popover from '@/components/Popover.vue'

const mainStore = useMainStore()
const slidesStore = useSlidesStore()
const { handleElement, handleElementId } = storeToRefs(mainStore)
const { theme } = storeToRefs(slidesStore)

const handleChartElement = handleElement as Ref<PPTChartElement>

const themesVisible = ref(false)
const themeColorsSettingVisible = ref(false)

const { addHistorySnapshot } = useHistorySnapshot()

const fill = ref<string>('#000')

const themeColors = ref<string[]>([])
const textColor = ref('')
const lineColor = ref('')
const lineSmooth = ref(false)
const stack = ref(false)

watch(handleElement, () => {
  if (!handleElement.value || handleElement.value.type !== 'chart') return
  fill.value = handleElement.value.fill || '#fff'

  lineSmooth.value = false
  stack.value = false

  if (handleElement.value.options) {
    const {
      lineSmooth: _lineSmooth,
      stack: _stack,
    } = handleElement.value.options

    if (_lineSmooth !== undefined) lineSmooth.value = _lineSmooth
    if (_stack !== undefined) stack.value = _stack
  }

  themeColors.value = handleElement.value.themeColors
  textColor.value = handleElement.value.textColor || '#333'
  lineColor.value = handleElement.value.lineColor || '#e8ecf4'
}, { deep: true, immediate: true })

const updateElement = (props: Partial<PPTChartElement>) => {
  slidesStore.updateElement({ id: handleElementId.value, props })
  addHistorySnapshot()
}

// 设置扩展选项
const updateOptions = (optionProps: ChartOptions) => {
  const _handleElement = handleElement.value as PPTChartElement

  const newOptions = { ..._handleElement.options, ...optionProps }
  updateElement({ options: newOptions })
}

// 使用预置主题配色
const setThemeColors = (colors: string[]) => {
  updateElement({ themeColors: colors })
  themesVisible.value = false
  themeColorsSettingVisible.value = false
}

const openDataEditor = () => emitter.emit(EmitterEvents.OPEN_CHART_DATA_EDITOR)
</script>

<style lang="scss" scoped>
.chart-style-panel {
  user-select: none;
}
.row {
  width: 100%;
  display: flex;
  align-items: center;
  margin-bottom: 10px;
}
.full-width-btn {
  width: 100%;
}
.label {
  font-size: 12px;
  margin-bottom: 4px;
}
.preset-themes {
  width: 250px;
  display: flex;

  @include flex-grid-layout();
}
.preset-theme {
  display: flex;
  cursor: pointer;
  border: 1px solid #ccc;
  padding: 2px;
  border-radius: $borderRadius;
  @include flex-grid-layout-children(2, 48%);

  &:hover {
    border-color: $themeColor;
    transition: border-color $transitionDelayFast;
  }
}
.preset-theme-color {
  height: 20px;
  flex: 1;
}
</style>

// apps/web/src/features/editor/ChartStylePanel.tsx
/* oxlint-disable jsx-a11y/click-events-have-key-events, jsx-a11y/no-static-element-interactions, jsx-a11y/prefer-tag-over-role -- theme swatches contain nested editing affordances and expose their actions explicitly. */
import { useState } from 'react'
import { useTranslation } from 'react-i18next'

import EditIcon from '~icons/icon-park-outline/edit'
import PaletteIcon from '~icons/icon-park-outline/platte'
import PlusIcon from '~icons/icon-park-outline/plus'
import CloseSmallIcon from '~icons/icon-park-outline/close-small'
import type { PresentationState } from '@mona/presentation-core'
import type { ChartOptions, PPTChartElement } from '@mona/presentation-core/model'

import { Button } from '@/components/ui/button'
import { ButtonGroup } from '@/components/ui/button-group'
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover'
import { ElementOutlineControls, PropertyRow } from '@/features/editor/ElementStyleCommons'
import { EditorColorPicker } from '@/features/editor/EditorColorPicker'
import { InspectorCheckbox, InspectorColorButton } from '@/features/editor/EditorInspectorPrimitives'
import { EditorModal } from '@/features/editor/EditorModal'
import { CHART_PRESET_THEMES } from '@/features/editor/editor-chart'
import type { EditorRuntime } from '@/features/editor/editor-runtime'

function ChartCheckbox({ checked, children, onChange, style }: {
  checked: boolean
  children: React.ReactNode
  onChange: (value: boolean) => void
  style?: React.CSSProperties
}) {
  return <InspectorCheckbox checked={checked} onChange={onChange} style={style}>{children}</InspectorCheckbox>
}

function ChartThemeBlocks({ colors }: { colors: readonly string[] }) {
  return <div className="mona-chart-theme-blocks">{colors.slice(0, 12).map((color, index) => <span key={`${color}-${index}`}><i style={{ backgroundColor: color }} /></span>)}</div>
}

function CustomThemeModal({ colors, onClose, onSave }: {
  colors: readonly string[]
  onClose: () => void
  onSave: (colors: string[]) => void
}) {
  const { t } = useTranslation()
  const [themeColors, setThemeColors] = useState([...colors])
  const canAddThemeColor = themeColors.length < 10
  return (
    <EditorModal onClose={onClose} open title={t('foundation.editor.chartStyle.chartThemeColors')} width={310}>
      <div className="flex flex-col">
        <div className="mb-[15px] text-[17px] font-bold">{t('foundation.editor.chartStyle.chartThemeColors')}</div>
        <div>
          {themeColors.map((color, index) => (
            <div className="mb-2.5 flex w-full items-center" key={index}>
              <div className="w-2/5 text-[13px]">{t('foundation.editor.chartStyle.themeColorNumber', { number: index + 1 })}</div>
              <ButtonGroup className="mona-chart-custom-color-group w-3/5">
                <Popover>
                  <PopoverTrigger asChild>
                    <Button aria-label={t('foundation.editor.chartStyle.themeColorNumber', { number: index + 1 })} className="mona-chart-custom-color-button" variant="outline">
                      <span><i style={{ backgroundColor: color }} /></span><PaletteIcon />
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent aria-label={t('foundation.editor.chartStyle.themeColorNumber', { number: index + 1 })} className="mona-panel-popover-content" sideOffset={8}>
                    <EditorColorPicker onChange={value => setThemeColors(current => current.map((candidate, colorIndex) => colorIndex === index ? value : candidate))} value={color} />
                  </PopoverContent>
                </Popover>
                {index ? <Button aria-label={t('foundation.editor.chartStyle.deleteColor')} onClick={() => setThemeColors(current => current.filter((_, colorIndex) => colorIndex !== index))} size="editor-icon" variant="outline"><CloseSmallIcon /></Button> : null}
              </ButtonGroup>
            </div>
          ))}
          <Button className="w-full" disabled={!canAddThemeColor} onClick={() => setThemeColors(current => [...current, '#00000000'])} size="editor" variant="outline"><PlusIcon /> {t('foundation.editor.chartStyle.addThemeColor')}</Button>
        </div>
        <Button className="mt-3 w-full" onClick={() => onSave(themeColors)} size="editor">{t('foundation.editor.chartData.confirm')}</Button>
      </div>
    </EditorModal>
  )
}

export function ChartStylePanel({ element, onEditData, presentation, runtime }: {
  element: PPTChartElement
  onEditData: () => void
  presentation: PresentationState
  runtime: EditorRuntime
}) {
  const { t } = useTranslation()
  const [themesOpen, setThemesOpen] = useState(false)
  const [customThemeOpen, setCustomThemeOpen] = useState(false)
  const commit = (props: Partial<PPTChartElement>, label = 'Update chart style') => runtime.commit(label, [{
    type: 'element.update',
    payload: { id: element.id, props },
  }], { historyKey: `chart-style-${element.id}` })
  const updateOptions = (props: ChartOptions) => commit({ options: { ...element.options, ...props } }, 'Update chart options')
  const setThemeColors = (colors: readonly string[]) => {
    commit({ themeColors: [...colors] }, 'Update chart theme')
    setThemesOpen(false)
    setCustomThemeOpen(false)
  }
  const hasStackOptions = ['bar', 'column', 'area', 'line'].includes(element.chartType)

  return (
    <div className="text-[13px] text-foreground select-none">
      <Button className="w-full" onClick={onEditData} size="editor" variant="outline"><EditIcon /> {t('foundation.editor.chartStyle.editChart')}</Button>
      <div className="my-6 w-full border-t border-black/[0.06]" />
      {hasStackOptions ? (
        <>
          <div className="mb-2.5 flex w-full items-center">
            <ChartCheckbox checked={!!element.options?.stack} onChange={stack => updateOptions({ stack })} style={{ flex: 2 }}>{t('foundation.editor.chartStyle.stacked')}</ChartCheckbox>
            {element.chartType === 'line' ? <ChartCheckbox checked={!!element.options?.lineSmooth} onChange={lineSmooth => updateOptions({ lineSmooth })} style={{ flex: 3 }}>{t('foundation.editor.chartStyle.smooth')}</ChartCheckbox> : null}
          </div>
          <div className="my-6 w-full border-t border-black/[0.06]" />
        </>
      ) : null}
      <PropertyRow label={t('foundation.editor.chartStyle.chartBackground')}><InspectorColorButton ariaLabel={t('foundation.editor.chartStyle.chartBackground')} color={element.fill || '#fff'} onChange={fill => commit({ fill })} /></PropertyRow>
      <PropertyRow label={t('foundation.editor.chartStyle.axisAndText')}><InspectorColorButton ariaLabel={t('foundation.editor.chartStyle.axisAndText')} color={element.textColor || '#333'} onChange={textColor => commit({ textColor })} /></PropertyRow>
      <PropertyRow label={t('foundation.editor.chartStyle.gridColor')}><InspectorColorButton ariaLabel={t('foundation.editor.chartStyle.gridColor')} color={element.lineColor || '#e8ecf4'} onChange={lineColor => commit({ lineColor })} /></PropertyRow>
      <PropertyRow label={t('foundation.editor.chartStyle.chartTheme')}>
        <Popover onOpenChange={setThemesOpen} open={themesOpen}>
          <PopoverTrigger asChild>
            <Button aria-label={t('foundation.editor.chartStyle.chartTheme')} className="mona-chart-theme-button" variant="outline"><ChartThemeBlocks colors={element.themeColors} /><PaletteIcon /></Button>
          </PopoverTrigger>
          <PopoverContent aria-label={t('foundation.editor.chartStyle.chartTheme')} align="center" className="mona-panel-popover-content mona-chart-themes-popover" collisionPadding={5} sideOffset={8}>
              <div className="mb-1 text-xs">{t('foundation.editor.chartStyle.presetChartThemes')}</div>
              <div className="mona-chart-preset-themes">
                {CHART_PRESET_THEMES.map((colors, index) => <Button className="mona-chart-preset-theme" key={index} onClick={() => setThemeColors(colors)} variant="outline">{colors.map(color => <span key={color} style={{ backgroundColor: color }} />)}</Button>)}
              </div>
              <div className="mb-1 text-xs">{t('foundation.editor.chartStyle.slideTheme')}</div>
              <div className="mona-chart-preset-themes is-slide-theme">
                <Button className="mona-chart-preset-theme" onClick={() => setThemeColors(presentation.theme.themeColors)} variant="outline">{presentation.theme.themeColors.map(color => <span key={color} style={{ backgroundColor: color }} />)}</Button>
              </div>
              <div className="my-2.5 w-full border-t border-black/[0.06]" />
              <Button className="w-full" onClick={() => {
                setThemesOpen(false); setCustomThemeOpen(true) 
              }} size="editor" variant="outline">{t('foundation.editor.chartStyle.customColors')}</Button>
          </PopoverContent>
        </Popover>
      </PropertyRow>
      <div className="my-6 w-full border-t border-black/[0.06]" />
      <ElementOutlineControls element={element} presentation={presentation} runtime={runtime} />
      {customThemeOpen ? <CustomThemeModal colors={element.themeColors} onClose={() => setCustomThemeOpen(false)} onSave={setThemeColors} /> : null}
    </div>
  )
}
