// src/views/Editor/Toolbar/ElementAnimationPanel.vue
<template>
  <div class="element-animation-panel">
    <div class="element-animation" v-if="handleElement">
      <Popover 
        trigger="click" 
        v-model:value="animationPoolVisible" 
        @update:value="visible => handlePopoverVisibleChange(visible)"
        style="width: 100%;"
      >
        <template #content>
          <Tabs 
            :tabs="tabs" 
            v-model:value="activeTab" 
            :tabsStyle="{ marginBottom: '20px' }" 
            :tabStyle="{ width: '33.333%' }" 
            spaceAround
          />
          <template v-for="key in animationTypes">
            <div :class="['animation-pool', key]" :key="key" v-if="activeTab === key">
              <div class="pool-type" :key="effect.type" v-for="effect in animations[key]">
                <div class="type-title">{{ $t(`animationGroups.${effect.type}`) }}:</div>
                <div class="pool-item-wrapper">
                  <div 
                    class="pool-item" 
                    v-for="item in effect.children" :key="item.value"
                    @mouseenter="hoverPreviewAnimation = item.value"
                    @mouseleave="hoverPreviewAnimation = ''"
                    @click="addAnimation(key, item.value)"
                  >
                    <div 
                      class="animation-box"
                      :class="[
                        `${ANIMATION_CLASS_PREFIX}animated`,
                        `${ANIMATION_CLASS_PREFIX}fast`,
                        hoverPreviewAnimation === item.value && `${ANIMATION_CLASS_PREFIX}${item.value}`,
                      ]"
                    >{{ $t(`animations.${item.value}`) }}</div>
                  </div>
                </div>
              </div>
              <div class="mask" v-if="!popoverMaskHide"></div>
            </div>
          </template>
        </template>
        <Button class="element-animation-btn" @click="handleAnimationId = ''">
          <i-icon-park-outline:effects /> {{ $t('animationPanel.addAnimation') }}
        </Button>
      </Popover>
    </div>

    <div class="tip" v-else><i-icon-park-outline:click style="margin-right: 5px;" /> {{ $t('animationPanel.selectElementTip') }}</div>
    
    <Divider />

    <Draggable 
      class="animation-sequence"
      :modelValue="animationSequence"
      :animation="200"
      :scroll="true"
      :scrollSensitivity="50"
      handle=".sequence-content"
      itemKey="id"
      @end="handleDragEnd"
    >
      <template #item="{ element }">
        <div class="sequence-item" :class="[element.type, { 'active': handleElement?.id === element.elId }]" @click="selectElement(element.elId)">
          <div class="sequence-content">
            <div class="index">{{element.index}}</div>
            <div class="text">「{{element.elType}}」{{element.animationEffect}}</div>
            <div class="handler">
              <i-icon-park-outline:play-one class="handler-btn" v-tooltip="$t('common.preview')" @click.stop="runAnimation(element.elId, element.effect, element.duration)" />
              <i-icon-park-outline:close-small class="handler-btn" v-tooltip="$t('common.delete')" @click.stop="deleteAnimation(element.id)" />
            </div>
          </div>

          <div class="configs" v-if="handleElementAnimation[0]?.elId === element.elId">
            <Divider :margin="16" />

            <div class="config-item">
              <div style="width: 35%;">{{ $t('animationPanel.duration') }}</div>
              <NumberInput 
                :min="500"
                :max="3000"
                :step="500"
                :value="element.duration" 
                @update:value="value => updateElementAnimationDuration(element.id, value)" 
                style="width: 65%;" 
              />
            </div>
            <div class="config-item">
              <div style="width: 35%;">{{ $t('animationPanel.trigger') }}</div>
              <Select
                :value="element.trigger"
                @update:value="value => updateElementAnimationTrigger(element.id, value as AnimationTrigger)"
                style="width: 65%;"
                :options="[
                  { label: $t('animationPanel.onClick'), value: 'click' },
                  { label: $t('animationPanel.withPrevious'), value: 'meantime' },
                  { label: $t('animationPanel.afterPrevious'), value: 'auto' },
                ]"
              />
            </div>
            <div class="config-item">
              <Button style="width: 100%;" @click="openAnimationPool(element.id)"><i-icon-park-outline:switch /> {{ $t('animationPanel.replaceAnimation') }}</Button>
            </div>
          </div>
        </div>
      </template>
    </Draggable>

    <template v-if="animationSequence.length >= 2">
      <Divider />
      <Button @click="runAllAnimation()">
        <i-icon-park-outline:pause v-if="animateIn" /><i-icon-park-outline:play-one v-else /> {{ animateIn ? $t('animationPanel.stopPreview') : $t('animationPanel.previewAll') }}
      </Button>
    </template>
  </div>
</template>

<script lang="ts" setup>
import { computed, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { createPresentationId as nanoid } from '@mona/presentation-core'
import { storeToRefs } from 'pinia'
import { useMainStore, useSlidesStore } from '@/store'
import type { AnimationTrigger, AnimationType, PPTAnimation } from '@/types/slides'
import { 
  ENTER_ANIMATIONS,
  EXIT_ANIMATIONS,
  ATTENTION_ANIMATIONS,
  ANIMATION_DEFAULT_DURATION,
  ANIMATION_DEFAULT_TRIGGER,
  ANIMATION_CLASS_PREFIX,
} from '@/configs/animation'
import useHistorySnapshot from '@/hooks/useHistorySnapshot'
import useSelectElement from '@/hooks/useSelectElement'

import Tabs from '@/components/Tabs.vue'
import Divider from '@/components/Divider.vue'
import Button from '@/components/Button.vue'
import Draggable from 'vuedraggable'
import NumberInput from '@/components/NumberInput.vue'
import Select from '@/components/Select.vue'
import Popover from '@/components/Popover.vue'

interface TabItem {
  key: AnimationType
  label: string
  color: string,
}

const animationTypes: AnimationType[] = ['in', 'out', 'attention']
const { t } = useI18n()
const animationEffects = computed<Record<string, string>>(() => {
  const labels: Record<string, string> = {}
  for (const group of [...ENTER_ANIMATIONS, ...EXIT_ANIMATIONS, ...ATTENTION_ANIMATIONS]) {
    for (const animation of group.children) {
      labels[animation.value] = t(`animations.${animation.value}`)
    }
  }
  return labels
})

const slidesStore = useSlidesStore()
const { handleElement, handleElementId } = storeToRefs(useMainStore())
const { currentSlide, formatedAnimations, currentSlideAnimations } = storeToRefs(slidesStore)

const tabs = computed<TabItem[]>(() => [
  { key: 'in', label: t('animationPanel.entrance'), color: '#68a490' },
  { key: 'out', label: t('animationPanel.exit'), color: '#d86344' },
  { key: 'attention', label: t('animationPanel.emphasis'), color: '#e8b76a' },
])
const activeTab = ref('in')
const animateIn = ref(false)
watch(() => handleElementId.value, () => {
  animationPoolVisible.value = false
})

const hoverPreviewAnimation = ref('')
const animationPoolVisible = ref(false)

const { addHistorySnapshot } = useHistorySnapshot()
const { selectElement } = useSelectElement()

// 当前页面的动画列表
const animationSequence = computed(() => {
  const animationSequence = []
  for (let i = 0; i < formatedAnimations.value.length; i++) {
    const item = formatedAnimations.value[i]
    for (let j = 0; j < item.animations.length; j++) {
      const animation = item.animations[j]
      const el = currentSlide.value.elements.find(el => el.id === animation.elId)
      if (!el) continue

      const elType = t(`elementTypes.${el.type}`)
      const animationEffect = animationEffects.value[animation.effect]
      animationSequence.push({
        ...animation,
        index: j === 0 ? i + 1 : '',
        elType,
        animationEffect,
      })
    }
  }
  return animationSequence
})

// 当前选中元素的入场动画信息
const handleElementAnimation = computed(() => {
  const animations = currentSlideAnimations.value
  const animation = animations.filter(item => item.elId === handleElementId.value)
  return animation || []
})

// 删除元素动画
const deleteAnimation = (id: string) => {
  const animations = currentSlideAnimations.value.filter(item => item.id !== id)
  slidesStore.updateSlide({ animations })
  addHistorySnapshot()
}

// 拖拽修改动画顺序后同步数据
const handleDragEnd = (eventData: { newIndex: number; oldIndex: number }) => {
  const { newIndex, oldIndex } = eventData
  if (newIndex === undefined || oldIndex === undefined || newIndex === oldIndex) return

  const animations: PPTAnimation[] = JSON.parse(JSON.stringify(currentSlideAnimations.value))
  const animation = animations[oldIndex]
  animations.splice(oldIndex, 1)
  animations.splice(newIndex, 0, animation)
  
  slidesStore.updateSlide({ animations })
  addHistorySnapshot()
}

// 执行动画预览
const runAnimation = (elId: string, effect: string, duration: number) => {
  const elRef = document.querySelector(`#editable-element-${elId} [class^=editable-element-]`)
  if (elRef) {
    const animationName = `${ANIMATION_CLASS_PREFIX}${effect}`
    document.documentElement.style.setProperty('--animate-duration', `${duration}ms`)
    elRef.classList.add(`${ANIMATION_CLASS_PREFIX}animated`, animationName)

    const handleAnimationEnd = () => {
      document.documentElement.style.removeProperty('--animate-duration')
      elRef.classList.remove(`${ANIMATION_CLASS_PREFIX}animated`, animationName)
    }
    elRef.addEventListener('animationend', handleAnimationEnd, { once: true })
  }
}

// 执行所有动画预览
const runAllAnimation = async () => {
  animateIn.value = !animateIn.value
  for (let i = 0; i < animationSequence.value.length; i++) {
    if (!animateIn.value) break
    const item = animationSequence.value[i]
    if (item.index !== 1 && item.trigger !== 'meantime') await new Promise(resolve => setTimeout(resolve, item.duration + 100)) 
    runAnimation(item.elId, item.effect, item.duration)
    if (i >= animationSequence.value.length - 1) animateIn.value = false
  }
}

// 修改元素动画持续时间
const updateElementAnimationDuration = (id: string, duration: number) => {
  if (duration < 100 || duration > 5000) return

  const animations = currentSlideAnimations.value.map(item => {
    if (item.id === id) return { ...item, duration }
    return item
  })
  slidesStore.updateSlide({ animations })
  addHistorySnapshot()
}

// 修改触发方式
const updateElementAnimationTrigger = (id: string, trigger: AnimationTrigger) => {
  const animations = currentSlideAnimations.value.map(item => {
    if (item.id === id) return { ...item, trigger }
    return item
  })
  slidesStore.updateSlide({ animations })
  addHistorySnapshot()
}

// 修改元素动画，并执行一次预览
const updateElementAnimation = (type: AnimationType, effect: string) => {
  const animations = currentSlideAnimations.value.map(item => {
    if (item.id === handleAnimationId.value) return { ...item, type, effect }
    return item
  })
  slidesStore.updateSlide({ animations })
  animationPoolVisible.value = false
  addHistorySnapshot()

  const animationItem = currentSlideAnimations.value.find(item => item.elId === handleElementId.value)
  const duration = animationItem?.duration || ANIMATION_DEFAULT_DURATION

  setTimeout(() => {
    runAnimation(handleElementId.value, effect, duration)
  }, 0)
}

const handleAnimationId = ref('')
// 添加元素动画，并执行一次预览
const addAnimation = (type: AnimationType, effect: string) => {
  if (handleAnimationId.value) {
    updateElementAnimation(type, effect)
    return
  }

  const animations: PPTAnimation[] = JSON.parse(JSON.stringify(currentSlideAnimations.value))
  animations.push({
    id: nanoid(10),
    elId: handleElementId.value,
    type,
    effect,
    duration: ANIMATION_DEFAULT_DURATION,
    trigger: ANIMATION_DEFAULT_TRIGGER,
  })
  slidesStore.updateSlide({ animations })
  animationPoolVisible.value = false
  addHistorySnapshot()

  setTimeout(() => {
    runAnimation(handleElementId.value, effect, ANIMATION_DEFAULT_DURATION)
  }, 0)
}

// 动画选择面板打开600ms后再移除遮罩层，否则打开面板后迅速滑入鼠标预览会导致抖动
const popoverMaskHide = ref(false)
const handlePopoverVisibleChange = (visible: boolean) => {
  if (visible) {
    setTimeout(() => popoverMaskHide.value = true, 600)
  }
  else popoverMaskHide.value = false
}

const openAnimationPool = (elementId: string) => {
  animationPoolVisible.value = true
  handleAnimationId.value = elementId
  handlePopoverVisibleChange(true)
}

const animations = {
  in: ENTER_ANIMATIONS,
  out: EXIT_ANIMATIONS,
  attention: ATTENTION_ANIMATIONS,
}
</script>

<style lang="scss" scoped>
$inColor: #68a490;
$outColor: #d86344;
$attentionColor: #e8b76a;

.element-animation-panel {
  height: 100%;
  display: flex;
  flex-direction: column;
}
.element-animation {
  height: 32px;
  display: flex;
  align-items: center;
}
.element-animation-btn {
  width: 100%;
}
.config-item {
  display: flex;
  align-items: center;

  & + .config-item {
    margin-top: 5px;
  }
}
.tip {
  height: 32px;
  display: flex;
  justify-content: center;
  align-items: center;
  font-style: italic;
}
.animation-pool {
  width: 400px;
  height: 500px;
  overflow-y: auto;
  overflow-x: hidden;
  font-size: 12px;
  margin-right: -10px;
  padding-right: 5px;
  position: relative;

  .mask {
    @include absolute-0();
  }

  &.in .type-title {
    border-left-color: $inColor;
    background-color: rgba($color: $inColor, $alpha: .15);
  }
  &.out .type-title {
    border-left-color: $outColor;
    background-color: rgba($color: $outColor, $alpha: .15);
  }
  &.attention .type-title {
    border-left-color: $attentionColor;
    background-color: rgba($color: $attentionColor, $alpha: .15);
  }
}
.pool-type:not(:last-child) {
  margin-bottom: 5px;
}
.type-title {
  width: 100%;
  font-size: 13px;
  margin-bottom: 10px;
  border-left: 4px solid #aaa;
  background-color: #eee;
  padding: 4px 0 4px 10px;
}
.pool-item-wrapper {
  @include flex-grid-layout();
}
.pool-item {
  @include flex-grid-layout-children(4, 24%);

  margin-bottom: 5px;
  height: 40px;
  line-height: 40px;
  text-align: center;
  cursor: pointer;
}
.animation-box {
  background-color: $lightGray;
  border-radius: $borderRadius;
}

.animation-sequence {
  flex: 1;
  padding-right: 12px;
  margin-right: -12px;

  @include overflow-overlay();
}
.sequence-item {
  border: 1px solid $borderColor;
  padding: 8px;
  border-radius: $borderRadius;
  margin-bottom: 8px;
  transition: all .5s;

  &.in.active {
    border-color: $inColor;
  }
  &.out.active {
    border-color: $outColor;
  }
  &.attention.active {
    border-color: $attentionColor;
  }
  &.active {
    height: auto;
  }

  .sequence-content {
    display: flex;
    align-items: center;
    cursor: grab;

    &:active {
      cursor: grabbing;
    }

    .index {
      flex: 1;
    }
    .text {
      flex: 6;
    }
    .handler {
      flex: 2;
      font-size: 15px;
      text-align: right;
    }
    .handler-btn {
      margin-left: 8px;
      cursor: pointer;
    }
  }
}
</style>

// apps/web/src/features/editor/ElementAnimationPanel.tsx
/* oxlint-disable jsx-a11y/prefer-tag-over-role -- source sequence rows are draggable composite controls containing their own action buttons. */
import { useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react'
import { useTranslation } from 'react-i18next'

import ClickIcon from '~icons/icon-park-outline/click'
import CloseIcon from '~icons/icon-park-outline/close-small'
import EffectsIcon from '~icons/icon-park-outline/effects'
import PauseIcon from '~icons/icon-park-outline/pause'
import PlayIcon from '~icons/icon-park-outline/play-one'
import SwitchIcon from '~icons/icon-park-outline/switch'
import {
  ANIMATION_CLASS_PREFIX,
  ANIMATION_DEFAULT_DURATION,
  ANIMATION_DEFAULT_TRIGGER,
  ATTENTION_ANIMATIONS,
  ENTER_ANIMATIONS,
  EXIT_ANIMATIONS,
} from '@mona/presentation-core/animation-config'
import { createPresentationId, selectFormattedCurrentSlideAnimations } from '@mona/presentation-core'
import type { AnimationTrigger, AnimationType, PPTAnimation, PPTElement } from '@mona/presentation-core/model'
import { editorActions, selectPresentation } from '@mona/editor-state'

import { Button } from '@/components/ui/button'
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { InspectorButton, InspectorNumberInput, InspectorSelect, inspectorDividerClass } from '@/features/editor/EditorInspectorPrimitives'
import type { EditorRuntime } from '@/features/editor/editor-runtime'
import { useEditorSelector } from '@/features/editor/use-editor-selector'

const catalogs = {
  attention: ATTENTION_ANIMATIONS,
  in: ENTER_ANIMATIONS,
  out: EXIT_ANIMATIONS,
} as const

const humanize = (value: string) => value
  .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
  .replace(/^./, first => first.toUpperCase())

const animationTarget = (elementId: string) => {
  const root = document.querySelector<HTMLElement>(`.mona-editor-slide-canvas [data-element-id="${CSS.escape(elementId)}"]`)
  if (!root) return null
  return root.querySelector<HTMLElement>('[class$="-content"]') || root.querySelector<HTMLElement>('.mona-rotate-wrapper') || root
}

export function ElementAnimationPanel({
  element,
  runtime,
}: {
  element: PPTElement | undefined
  runtime: EditorRuntime
}) {
  const { t } = useTranslation()
  const presentation = useEditorSelector(runtime.store, selectPresentation)
  const slide = presentation.slides[presentation.slideIndex]!
  const animations = slide.animations || []
  const [activeTab, setActiveTab] = useState<AnimationType>('in')
  const [open, setOpen] = useState(false)
  const [poolMask, setPoolMask] = useState(false)
  const [replacementId, setReplacementId] = useState('')
  const [hoverEffect, setHoverEffect] = useState('')
  const [previewing, setPreviewing] = useState(false)
  const [draggingIndex, setDraggingIndex] = useState<number | null>(null)
  const panelRef = useRef<HTMLDivElement>(null)
  const suppressSequenceClickRef = useRef(false)
  const poolTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const previewingRef = useRef(false)
  const reorderCleanupRef = useRef<(() => void) | null>(null)
  const historyKey = 'element-animation-panel'
  const formatted = selectFormattedCurrentSlideAnimations(presentation)
  const sequence = formatted.flatMap((group, groupIndex) => group.animations.flatMap((animation, animationIndex) => {
    const target = slide.elements.find(candidate => candidate.id === animation.elId)
    return target ? [{
      ...animation,
      animationEffect: t(`foundation.editor.animation.effect.${animation.effect}`, { defaultValue: humanize(animation.effect) }),
      elType: t(`foundation.editor.animation.elementType.${target.type}`),
      index: animationIndex === 0 ? groupIndex + 1 : '',
    }] : []
  }))
  const handleAnimations = element ? animations.filter(animation => animation.elId === element.id) : []

  useEffect(() => () => {
    if (poolTimerRef.current) clearTimeout(poolTimerRef.current)
    reorderCleanupRef.current?.()
    reorderCleanupRef.current = null
    previewingRef.current = false
  }, [])

  const changeOpen = (visible: boolean) => {
    setOpen(visible)
    if (poolTimerRef.current) clearTimeout(poolTimerRef.current)
    poolTimerRef.current = null
    if (visible) {
      setPoolMask(true)
      poolTimerRef.current = setTimeout(() => {
        poolTimerRef.current = null
        setPoolMask(false)
      }, 800)
    }
    else setPoolMask(false)
  }

  const updateAnimations = (next: PPTAnimation[], label: string) => runtime.commit(label, [{
    type: 'slide.update',
    props: { animations: next },
  }], { historyKey })

  const runAnimation = (elementId: string, effect: string, duration: number) => {
    const target = animationTarget(elementId)
    if (!target) return
    const animationName = `${ANIMATION_CLASS_PREFIX}${effect}`
    document.documentElement.style.setProperty('--animate-duration', `${duration}ms`)
    target.classList.add(`${ANIMATION_CLASS_PREFIX}animated`, animationName)
    target.addEventListener('animationend', () => {
      document.documentElement.style.removeProperty('--animate-duration')
      target.classList.remove(`${ANIMATION_CLASS_PREFIX}animated`, animationName)
    }, { once: true })
  }

  const chooseEffect = (type: AnimationType, effect: string) => {
    if (!element) return
    let duration = ANIMATION_DEFAULT_DURATION
    let next: PPTAnimation[]
    if (replacementId) {
      next = animations.map(animation => {
        if (animation.id !== replacementId) return animation
        duration = animation.duration
        return { ...animation, effect, type }
      })
    }
    else {
      next = [...structuredClone(animations), {
        duration: ANIMATION_DEFAULT_DURATION,
        effect,
        elId: element.id,
        id: createPresentationId(10),
        trigger: ANIMATION_DEFAULT_TRIGGER,
        type,
      }]
    }
    updateAnimations(next, replacementId ? 'Replace element animation' : 'Add element animation')
    changeOpen(false)
    window.setTimeout(() => runAnimation(element.id, effect, duration), 0)
  }

  const deleteAnimation = (id: string) => updateAnimations(animations.filter(animation => animation.id !== id), 'Delete element animation')
  const updateAnimation = (id: string, props: Partial<PPTAnimation>, label: string) => updateAnimations(
    animations.map(animation => animation.id === id ? { ...animation, ...props } : animation),
    label,
  )
  const selectElement = (id: string) => {
    const session = runtime.store.getState().session
    if (session.handleElementId === id || session.hiddenElementIds.includes(id)) return
    const target = slide.elements.find(candidate => candidate.id === id)
    if (!target || target.lock) return
    runtime.store.dispatch(editorActions.selectionChanged([id]))
  }

  const runAll = async () => {
    if (previewingRef.current) {
      previewingRef.current = false
      setPreviewing(false)
      return
    }
    previewingRef.current = true
    setPreviewing(true)
    for (let index = 0; index < sequence.length; index++) {
      if (!previewingRef.current) break
      const item = sequence[index]!
      if (item.index !== 1 && item.trigger !== 'meantime') {
        await new Promise(resolve => window.setTimeout(resolve, item.duration + 100))
      }
      if (!previewingRef.current) break
      runAnimation(item.elId, item.effect, item.duration)
    }
    previewingRef.current = false
    setPreviewing(false)
  }

  const reorder = (oldIndex: number, newIndex: number) => {
    if (oldIndex === newIndex) return
    const next = structuredClone(animations)
    const moved = next.splice(oldIndex, 1)[0]
    if (!moved) return
    next.splice(newIndex, 0, moved)
    updateAnimations(next, 'Reorder element animations')
  }

  const startReorder = (event: ReactPointerEvent<HTMLElement>, oldIndex: number) => {
    if (event.button !== 0) return
    const target = event.target instanceof Element ? event.target : null
    if (target?.closest('button, input, .mona-panel-select')) return
    const startY = event.clientY
    let newIndex = oldIndex
    let moved = false
    reorderCleanupRef.current?.()
    const move = (pointer: PointerEvent) => {
      if (!moved && Math.abs(pointer.clientY - startY) < 4) return
      moved = true
      setDraggingIndex(oldIndex)
      const rows = [...(panelRef.current?.querySelectorAll<HTMLElement>('.mona-animation-sequence-item') || [])]
      const firstAfterPointer = rows.findIndex(row => pointer.clientY <= row.getBoundingClientRect().top + (row.getBoundingClientRect().height / 2))
      newIndex = firstAfterPointer === -1 ? Math.max(rows.length - 1, 0) : firstAfterPointer
    }
    const cleanup = () => {
      window.removeEventListener('pointermove', move)
      window.removeEventListener('pointerup', stop)
      window.removeEventListener('pointercancel', stop)
      reorderCleanupRef.current = null
    }
    const stop = () => {
      cleanup()
      setDraggingIndex(null)
      if (!moved) return
      suppressSequenceClickRef.current = true
      reorder(oldIndex, newIndex)
    }
    window.addEventListener('pointermove', move)
    window.addEventListener('pointerup', stop, { once: true })
    window.addEventListener('pointercancel', stop, { once: true })
    reorderCleanupRef.current = cleanup
  }

  const poolTitleTone = activeTab === 'in'
    ? 'border-l-[#68a490] bg-[rgba(104,164,144,0.15)]'
    : activeTab === 'out'
      ? 'border-l-[#d86344] bg-[rgba(216,99,68,0.15)]'
      : 'border-l-[#e8b76a] bg-[rgba(232,183,106,0.15)]'
  const pool = (
    <div>
      <Tabs onValueChange={value => setActiveTab(value as AnimationType)} value={activeTab}>
        <TabsList className="mb-5 flex h-auto select-none rounded-none border-b border-[#d9d9d9] bg-transparent p-0 text-[13px] leading-none">
          {([
            ['in', t('foundation.editor.animation.entrance'), '#68a490'],
            ['out', t('foundation.editor.animation.exit'), '#d86344'],
            ['attention', t('foundation.editor.animation.emphasis'), '#e8b76a'],
          ] as const).map(([key, label, color]) => (
            <TabsTrigger
              className="w-1/3 rounded-none border-0 border-b-2 border-transparent bg-transparent px-2.5 py-2 text-center text-[#333] shadow-none data-[state=active]:border-b-[var(--animation-color)] data-[state=active]:bg-transparent data-[state=active]:shadow-none"
              key={key}
              style={{ '--animation-color': color } as React.CSSProperties}
              value={key}
            >{label}</TabsTrigger>
          ))}
        </TabsList>
      </Tabs>
      <div className="relative mr-[-10px] h-[500px] w-[400px] overflow-hidden overflow-y-auto pr-[5px] text-xs">
        {catalogs[activeTab].map(group => (
          <div className="mb-[5px] last:mb-0" key={group.type}>
            <div className={`mb-2.5 w-full border-l-4 py-1 pr-0 pl-2.5 text-[13px] ${poolTitleTone}`}>{t(`foundation.editor.animation.group.${group.type}`, { defaultValue: humanize(group.type) })}:</div>
            <div className="flex flex-wrap content-start">
              {group.children.map(item => (
                <Button
                  className="mb-[5px] h-10 w-[24%] border-0 bg-transparent p-0 text-center text-[#41464b] leading-10 not-[:nth-child(4n)]:mr-[1.333333%] hover:bg-transparent [&_span]:block [&_span]:rounded-[var(--radius-control)] [&_span]:bg-[#f9f9f9]"
                  key={item.value}
                  onClick={() => chooseEffect(activeTab, item.value)}
                  onMouseEnter={() => setHoverEffect(item.value)}
                  onMouseLeave={() => setHoverEffect('')}
                  size="editor"
                  type="button"
                  variant="ghost"
                ><span className={`${ANIMATION_CLASS_PREFIX}animated ${ANIMATION_CLASS_PREFIX}fast${hoverEffect === item.value ? ` ${ANIMATION_CLASS_PREFIX}${item.value}` : ''}`}>{t(`foundation.editor.animation.effect.${item.value}`, { defaultValue: humanize(item.value) })}</span></Button>
              ))}
            </div>
          </div>
        ))}
        {poolMask ? <div className="absolute inset-0" /> : null}
      </div>
    </div>
  )

  return (
    <div className="mona-element-animation-panel" ref={panelRef}>
      <div className="mona-element-animation-add">
        {element ? (
          <div className="mona-animation-add-popover">
            <Popover onOpenChange={changeOpen} open={open && !replacementId}>
              <PopoverTrigger asChild><Button aria-label={t('foundation.editor.animation.add')} className="mona-panel-button mona-animation-add-button" onClick={() => setReplacementId('')} size="editor" type="button" variant="editor"><EffectsIcon />{` ${t('foundation.editor.animation.add')}`}</Button></PopoverTrigger>
              <PopoverContent aria-label={t('foundation.editor.animation.add')} align="center" className="mona-animation-popover" collisionPadding={5} side="bottom" sideOffset={8}>{pool}</PopoverContent>
            </Popover>
          </div>
        ) : <div className="mona-animation-tip"><ClickIcon /> {t('foundation.editor.animation.selectTip')}</div>}
      </div>

      <div className={inspectorDividerClass} />

      <div className="mona-animation-sequence">
        {sequence.map((item, index) => (
          <div
            className={`mona-animation-sequence-item is-${item.type}${element?.id === item.elId ? ' is-active' : ''}${draggingIndex === index ? ' is-dragging' : ''}`}
            key={item.id}
            onClick={() => {
              if (suppressSequenceClickRef.current) {
                suppressSequenceClickRef.current = false
                return
              }
              selectElement(item.elId)
            }}
            onKeyDown={event => {
              if (event.key === 'Enter' || event.key === ' ') selectElement(item.elId)
            }}
            role="button"
            tabIndex={0}
          >
            <div className="mona-animation-sequence-content" onPointerDown={event => startReorder(event, index)}>
              <div className="mona-animation-index">{item.index}</div>
              <div className="mona-animation-text">「{item.elType}」{item.animationEffect}</div>
              <div className="mona-animation-handlers">
                <Button aria-label={t('foundation.editor.animation.preview')} onClick={event => {
                  event.stopPropagation(); runAnimation(item.elId, item.effect, item.duration) 
                }} onPointerDown={event => event.stopPropagation()} size="icon-xs" type="button" variant="ghost"><PlayIcon /></Button>
                <Button
                  aria-label={t('foundation.editor.animation.delete')}
                  onClick={event => {
                    event.stopPropagation()
                    // Keyboard/programmatic activation has no pointer-up.
                    if (event.detail === 0) deleteAnimation(item.id)
                  }}
                  onPointerDown={event => event.stopPropagation()}
                  onPointerUp={event => {
                    event.stopPropagation()
                    deleteAnimation(item.id)
                  }}
                  size="icon-xs"
                  type="button"
                  variant="ghost"
                ><CloseIcon /></Button>
              </div>
            </div>
            {handleAnimations[0]?.elId === item.elId ? (
              <div className="mona-animation-configs">
                <div className={`${inspectorDividerClass} !my-4`} />
                <div className="mona-animation-config-row">
                  <div style={{ width: '35%' }}>{t('foundation.editor.animation.duration')}</div>
                  <InspectorNumberInput ariaLabel={`${t('foundation.editor.animation.duration')} ${item.animationEffect}`} max={3000} min={500} onChange={value => {
                    if (value >= 100 && value <= 5000) updateAnimation(item.id, { duration: value }, 'Update animation duration')
                  }} step={500} style={{ width: '65%' }} value={item.duration} />
                </div>
                <div className="mona-animation-config-row">
                  <div style={{ width: '35%' }}>{t('foundation.editor.animation.trigger')}</div>
                  <InspectorSelect<AnimationTrigger>
                    ariaLabel={`${t('foundation.editor.animation.trigger')} ${item.animationEffect}`}
                    onChange={value => updateAnimation(item.id, { trigger: value }, 'Update animation trigger')}
                    options={[
                      { label: t('foundation.editor.animation.onClick'), value: 'click' },
                      { label: t('foundation.editor.animation.withPrevious'), value: 'meantime' },
                      { label: t('foundation.editor.animation.afterPrevious'), value: 'auto' },
                    ]}
                    style={{ width: '65%' }}
                    value={item.trigger}
                  />
                </div>
                <div className="mona-animation-config-row">
                  <Popover onOpenChange={changeOpen} open={open && replacementId === item.id}>
                    <PopoverTrigger asChild><Button aria-label={`${t('foundation.editor.animation.replace')} ${item.animationEffect}`} className="mona-panel-button" onClick={() => {
                      setReplacementId(item.id); changeOpen(true) 
                    }} size="editor" style={{ width: '100%' }} type="button" variant="editor"><SwitchIcon /> {t('foundation.editor.animation.replace')}</Button></PopoverTrigger>
                    <PopoverContent aria-label={`${t('foundation.editor.animation.replace')} ${item.animationEffect}`} align="center" className="mona-animation-popover" collisionPadding={5} side="bottom" sideOffset={8}>{pool}</PopoverContent>
                  </Popover>
                </div>
              </div>
            ) : null}
          </div>
        ))}
      </div>

      {sequence.length >= 2 ? (
        <>
          <div className={inspectorDividerClass} />
          <InspectorButton ariaLabel={previewing ? t('foundation.editor.animation.stopAll') : t('foundation.editor.animation.previewAll')} onClick={runAll}>{previewing ? <PauseIcon /> : <PlayIcon />} {previewing ? t('foundation.editor.animation.stopAll') : t('foundation.editor.animation.previewAll')}</InspectorButton>
        </>
      ) : null}
    </div>
  )
}
