// src/views/Editor/Toolbar/ElementStylePanel/LineStylePanel.vue
<template>
  <div class="line-style-panel">
    <div class="title">
      <span>{{ $t('elementStyle.replaceLine') }}</span>
      <i-icon-park-outline:down />
    </div>
    <div class="line-pool-wrapper">
      <div class="line-type-list">
        <div class="line-type-item" v-for="item in lineTypeOptions" :key="item.key" @click="changeLineType(item)">
          <div class="line-type-content">
            <svg
              overflow="visible"
              width="24"
              height="24"
            >
              <defs>
                <LinePointMarker
                  v-if="handleLineElement.points[0]"
                  :id="`replace-line-${item.key}`"
                  position="start"
                  :type="handleLineElement.points[0]"
                  color="currentColor"
                  :baseSize="2"
                  preview
                />
                <LinePointMarker
                  v-if="handleLineElement.points[1]"
                  :id="`replace-line-${item.key}`"
                  position="end"
                  :type="handleLineElement.points[1]"
                  color="currentColor"
                  :baseSize="2"
                  preview
                />
              </defs>
              <path
                :d="item.path"
                stroke="currentColor"
                fill="none"
                stroke-width="2"
                :stroke-dasharray="handleLineElement.style === 'solid' ? '0, 0' : '4, 1'"
                :marker-start="handleLineElement.points[0] ? `url(#${`replace-line-${item.key}`}-${handleLineElement.points[0]}-start)` : ''"
                :marker-end="handleLineElement.points[1] ? `url(#${`replace-line-${item.key}`}-${handleLineElement.points[1]}-end)` : ''"
              ></path>
            </svg>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div style="width: 40%;">{{ $t('elementStyle.lineStyle') }}</div>
      <SelectCustom style="width: 60%;">
        <template #options>
          <div class="option" v-for="item in lineStyleOptions" :key="item" @click="updateLine({ style: item })">
            <SVGLine :type="item" />
          </div>
        </template>
        <template #label>
          <SVGLine :type="handleLineElement.style" />
        </template>
      </SelectCustom>
    </div>
    <div class="row">
      <div style="width: 40%;">{{ $t('elementStyle.lineColor') }}</div>
      <Popover trigger="click" style="width: 60%;">
        <template #content>
          <ColorPicker
            :modelValue="handleLineElement.color"
            @update:modelValue="value => updateLine({ color: value })"
          />
        </template>
        <ColorButton :color="handleLineElement.color" />
      </Popover>
    </div>
    <div class="row">
      <div style="width: 40%;">{{ $t('elementStyle.lineWidth') }}</div>
      <NumberInput 
        :value="handleLineElement.width" 
        @update:value="value => updateLine({ width: value })" 
        style="width: 60%;" 
      />
    </div>
    
    <div class="row">
      <div style="width: 40%;">{{ $t('elementStyle.startMarker') }}</div>
      <SelectCustom style="width: 60%;">
        <template #options>
          <div class="option" v-for="item in lineMarkerOptions" :key="item" @click="updateLine({ points: [item, handleLineElement.points[1]] })">
            <SVGLine :padding="5" :markers="[item, '']" />
          </div>
        </template>
        <template #label>
          <SVGLine :padding="5" :markers="[handleLineElement.points[0], '']" />
        </template>
      </SelectCustom>
    </div>
    <div class="row">
      <div style="width: 40%;">{{ $t('elementStyle.endMarker') }}</div>
      <SelectCustom style="width: 60%;">
        <template #options>
          <div class="option" v-for="item in lineMarkerOptions" :key="item" @click="updateLine({ points: [handleLineElement.points[0], item] })">
            <SVGLine :padding="5" :markers="['', item]" />
          </div>
        </template>
        <template #label>
          <SVGLine :padding="5" :markers="['', handleLineElement.points[1]]" />
        </template>
      </SelectCustom>
    </div>

    <div class="row" v-if="handleLineElement.broken2">
      <div style="width: 40%;">{{ $t('elementStyle.lineDirection') }}</div>
      <Select 
        style="width: 60%;"
        :value="handleLineElement.broken2Direction || 'auto'"
        :options="lineBroken2DirectionOptions"
        @update:value="value => updateBroken2Direction(value)"
      />
    </div>

    <Divider />

    <div class="row">
      <Button style="flex: 1;" @click="updateLine({ start: handleLineElement.end, end: handleLineElement.start })"><i-icon-park-outline:switch /> {{ $t('elementStyle.swapDirection') }}</Button>
    </div>

    <Divider />
    <ElementShadow />
  </div>
</template>

<script lang="ts" setup>
import { computed, type Ref, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { storeToRefs } from 'pinia'
import { useMainStore, useSlidesStore } from '@/store'
import type { Broken2LineDirection, LinePoint, LineStyleType, PPTLineElement } from '@/types/slides'
import useHistorySnapshot from '@/hooks/useHistorySnapshot'

import ElementShadow from '../common/ElementShadow.vue'
import SVGLine from '../common/SVGLine.vue'
import LinePointMarker from '@/views/components/element/LineElement/LinePointMarker.vue'
import Button from '@/components/Button.vue'
import ColorButton from '@/components/ColorButton.vue'
import ColorPicker from '@/components/ColorPicker/index.vue'
import Divider from '@/components/Divider.vue'
import NumberInput from '@/components/NumberInput.vue'
import Select from '@/components/Select.vue'
import SelectCustom from '@/components/SelectCustom.vue'
import Popover from '@/components/Popover.vue'

const slidesStore = useSlidesStore()
const { handleElement } = storeToRefs(useMainStore())

const handleLineElement = handleElement as Ref<PPTLineElement>

const { addHistorySnapshot } = useHistorySnapshot()
const { t } = useI18n()

const lineStyleOptions = ref<LineStyleType[]>(['solid', 'dashed', 'dotted'])
const lineMarkerOptions = ref<LinePoint[]>(['', 'arrow', 'dot'])

const lineBroken2DirectionOptions = computed<{ label: string; value: Broken2LineDirection | 'auto' }[]>(() => [
  { label: t('common.auto'), value: 'auto' },
  { label: t('common.horizontal'), value: 'horizontal' },
  { label: t('common.vertical'), value: 'vertical' },
])
interface LineTypeOption {
  key: string
  path: string
  isBroken?: boolean
  isBroken2?: boolean
  isCurve?: boolean
  isCubic?: boolean
}

const lineTypeOptions: LineTypeOption[] = [
  { key: 'straight', path: 'M 2 2 L 22 22' },
  { key: 'broken', path: 'M 2 2 L 2 22 L 22 22', isBroken: true },
  { key: 'broken2', path: 'M 2 2 L 12 2 L 12 22 L 22 22', isBroken2: true },
  { key: 'curve', path: 'M 2 2 Q 2 22 22 22', isCurve: true },
  { key: 'cubic', path: 'M 2 2 C 22 2 2 22 22 22', isCubic: true },
] 

const changeLineType = (line: LineTypeOption) => {
  if (!handleElement.value) return

  const { id, start, end } = handleElement.value as PPTLineElement
  const midpoint: [number, number] = [(start[0] + end[0]) / 2, (start[1] + end[1]) / 2]

  const propName: Array<keyof PPTLineElement> = ['broken', 'broken2', 'curve', 'cubic']
  if (!line.isBroken2) propName.push('broken2Direction')
  slidesStore.removeElementProps({
    id,
    propName,
  })

  const props: Partial<PPTLineElement> = {}
  if (line.isBroken) props.broken = midpoint
  if (line.isBroken2) props.broken2 = midpoint
  if (line.isCurve) props.curve = midpoint
  if (line.isCubic) props.cubic = [midpoint, midpoint]

  slidesStore.updateElement({ id, props })
  addHistorySnapshot()
}

const updateLine = (props: Partial<PPTLineElement>) => {
  if (!handleElement.value) return
  slidesStore.updateElement({ id: handleElement.value.id, props })
  addHistorySnapshot()
}

const updateBroken2Direction = (value: string | number) => {
  if (!handleElement.value) return

  if (value === 'auto') {
    slidesStore.removeElementProps({
      id: handleElement.value.id,
      propName: 'broken2Direction',
    })
    addHistorySnapshot()
  }
  else updateLine({ broken2Direction: value as Broken2LineDirection })
}
</script>

<style lang="scss" scoped>
.line-style-panel {
  user-select: none;
}
.row {
  width: 100%;
  display: flex;
  align-items: center;
  margin-bottom: 10px;
}
.title {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 10px;
}
.line-pool-wrapper {
  width: 235px;
  padding: 5px;
  border: 1px solid $borderColor;
  margin-bottom: 20px;
}
.line-type-list {
  @include flex-grid-layout();
}
.line-type-item {
  @include flex-grid-layout-children(6, 14%);

  height: 0;
  padding-bottom: 14%;
  margin-bottom: 0;
  flex-shrink: 0;
  position: relative;
  color: #999;
  cursor: pointer;

  &:hover {
    color: $themeColor;
  }
}
.line-type-content {
  @include absolute-0();

  display: flex;
  justify-content: center;
  align-items: center;
}
.line-btn {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 !important;

  .line-wrapper {
    margin-left: 8px;
  }
}
.line-wrapper {
  overflow: visible;
}
.preset-point-style {
  padding: 0 10px;

  & + .preset-point-style {
    margin-top: 10px;
  }
}
.option {
  height: 32px;
  padding: 0 5px;
  border-radius: $borderRadius;

  &:not(.selected):hover {
    background-color: rgba($color: $themeColor, $alpha: .05);
    cursor: pointer;
  }

  &.selected {
    color: $themeColor;
    font-weight: 700;
  }
}
</style>

// apps/web/src/features/editor/LineStylePanel.tsx
import { useTranslation } from 'react-i18next'

import DownIcon from '~icons/icon-park-outline/down'
import SwitchIcon from '~icons/icon-park-outline/switch'
import type { PresentationState } from '@mona/presentation-core'
import type { Broken2LineDirection, LinePoint, LineStyleType, PPTLineElement } from '@mona/presentation-core/model'

import { Button } from '@/components/ui/button'
import { InspectorButton, InspectorColorButton, InspectorNumberInput, InspectorSelect, inspectorDividerClass } from '@/features/editor/EditorInspectorPrimitives'
import {
  ElementShadowControls,
  LinePointMarker,
  LinePreview,
  PropertyRow,
} from '@/features/editor/ElementStyleCommons'
import type { EditorRuntime } from '@/features/editor/editor-runtime'
import { lineStyleOptions } from '@/features/editor/editor-style-options'

const markerOptions: Array<{ label: string; value: LinePoint }> = [
  { label: 'None', value: '' },
  { label: 'Arrow', value: 'arrow' },
  { label: 'Dot', value: 'dot' },
]

interface LineTypeOption {
  isBroken?: boolean
  isBroken2?: boolean
  isCubic?: boolean
  isCurve?: boolean
  key: string
  path: string
}

const lineTypeOptions: LineTypeOption[] = [
  { key: 'straight', path: 'M 2 2 L 22 22' },
  { key: 'broken', path: 'M 2 2 L 2 22 L 22 22', isBroken: true },
  { key: 'broken2', path: 'M 2 2 L 12 2 L 12 22 L 22 22', isBroken2: true },
  { key: 'curve', path: 'M 2 2 Q 2 22 22 22', isCurve: true },
  { key: 'cubic', path: 'M 2 2 C 22 2 2 22 22 22', isCubic: true },
]

function LineTypeThumbnail({ element, item, onSelect }: { element: PPTLineElement; item: LineTypeOption; onSelect: () => void }) {
  const id = `mona-replace-line-${item.key}`
  return (
    <Button aria-label={`Replace with ${item.key} line`} className="relative flex aspect-square size-full cursor-pointer items-center justify-center border-0 bg-transparent p-0 text-neutral-400 hover:text-editor-selection [&_svg]:absolute [&_svg]:top-1/2 [&_svg]:left-1/2 [&_svg]:-translate-x-1/2 [&_svg]:-translate-y-1/2 [&_svg]:overflow-visible" onClick={onSelect} size="editor-icon" type="button" variant="ghost">
      <svg height="24" overflow="visible" width="24">
        <defs>
          {element.points[0] ? <LinePointMarker baseSize={2} color="currentColor" id={id} position="start" preview type={element.points[0]} /> : null}
          {element.points[1] ? <LinePointMarker baseSize={2} color="currentColor" id={id} position="end" preview type={element.points[1]} /> : null}
        </defs>
        <path
          d={item.path}
          fill="none"
          markerEnd={element.points[1] ? `url(#${id}-${element.points[1]}-end)` : undefined}
          markerStart={element.points[0] ? `url(#${id}-${element.points[0]}-start)` : undefined}
          stroke="currentColor"
          strokeDasharray={element.style === 'solid' ? '0, 0' : '4, 1'}
          strokeWidth="2"
        />
      </svg>
    </Button>
  )
}

export function LineStylePanel({
  element,
  presentation,
  runtime,
}: {
  element: PPTLineElement
  presentation: PresentationState
  runtime: EditorRuntime
}) {
  const { t } = useTranslation()
  const update = (props: Partial<PPTLineElement>, historyKey = `line-style-${element.id}`) => runtime.commit(
    'Update line style',
    [{ type: 'element.update', payload: { id: element.id, props } }],
    { historyKey },
  )
  const changeLineType = (item: LineTypeOption) => {
    const midpoint: [number, number] = [(element.start[0] + element.end[0]) / 2, (element.start[1] + element.end[1]) / 2]
    const property: string[] = ['broken', 'broken2', 'curve', 'cubic']
    if (!item.isBroken2) property.push('broken2Direction')
    const props: Partial<PPTLineElement> = {}
    if (item.isBroken) props.broken = midpoint
    if (item.isBroken2) props.broken2 = midpoint
    if (item.isCurve) props.curve = midpoint
    if (item.isCubic) props.cubic = [midpoint, midpoint]
    runtime.commit('Replace line type', [
      { type: 'element.properties.remove', payload: { id: element.id, property } },
      { type: 'element.update', payload: { id: element.id, props } },
    ], { historyKey: `line-replace-${element.id}` })
  }
  const directionOptions: Array<{ label: string; value: Broken2LineDirection | 'auto' }> = [
    { label: t('foundation.editor.line.auto'), value: 'auto' },
    { label: t('foundation.editor.line.horizontal'), value: 'horizontal' },
    { label: t('foundation.editor.line.vertical'), value: 'vertical' },
  ]
  return (
    <div className="mona-line-style-panel">
      <div className="mona-shape-panel-title"><span>{t('foundation.editor.line.replace')}</span><DownIcon /></div>
      <div className="mb-5 box-border grid w-58.75 grid-cols-6 gap-[3.2%] border p-1.25">
        {lineTypeOptions.map(item => <LineTypeThumbnail element={element} item={item} key={item.key} onSelect={() => changeLineType(item)} />)}
      </div>
      <PropertyRow label={t('foundation.editor.line.style')}>
        <InspectorSelect<LineStyleType> ariaLabel={t('foundation.editor.line.style')} onChange={style => update({ style })} options={lineStyleOptions} renderLabel={option => <LinePreview type={option?.value || 'solid'} />} renderOption={option => <LinePreview type={option.value} />} value={element.style} />
      </PropertyRow>
      <PropertyRow label={t('foundation.editor.line.color')}><InspectorColorButton ariaLabel={t('foundation.editor.line.color')} color={element.color} onChange={color => update({ color })} /></PropertyRow>
      <PropertyRow label={t('foundation.editor.line.width')}><InspectorNumberInput ariaLabel={t('foundation.editor.line.width')} onChange={width => update({ width })} value={element.width} /></PropertyRow>
      <PropertyRow label={t('foundation.editor.line.startMarker')}>
        <InspectorSelect<LinePoint> ariaLabel={t('foundation.editor.line.startMarker')} onChange={marker => update({ points: [marker, element.points[1]] })} options={markerOptions} renderLabel={option => <LinePreview markers={[option?.value || '', '']} padding={5} />} renderOption={option => <LinePreview markers={[option.value, '']} padding={5} />} value={element.points[0]} />
      </PropertyRow>
      <PropertyRow label={t('foundation.editor.line.endMarker')}>
        <InspectorSelect<LinePoint> ariaLabel={t('foundation.editor.line.endMarker')} onChange={marker => update({ points: [element.points[0], marker] })} options={markerOptions} renderLabel={option => <LinePreview markers={['', option?.value || '']} padding={5} />} renderOption={option => <LinePreview markers={['', option.value]} padding={5} />} value={element.points[1]} />
      </PropertyRow>
      {element.broken2 ? (
        <PropertyRow label={t('foundation.editor.line.direction')}>
          <InspectorSelect<Broken2LineDirection | 'auto'> ariaLabel={t('foundation.editor.line.direction')} onChange={direction => direction === 'auto'
            ? runtime.commit('Use automatic line direction', [{ type: 'element.properties.remove', payload: { id: element.id, property: 'broken2Direction' } }], { historyKey: `line-style-${element.id}` })
            : update({ broken2Direction: direction })} options={directionOptions} value={element.broken2Direction || 'auto'} />
        </PropertyRow>
      ) : null}
      <div className={inspectorDividerClass} />
      <InspectorButton ariaLabel={t('foundation.editor.line.swap')} onClick={() => update({ start: element.end, end: element.start }, `line-swap-${element.id}`)} style={{ width: '100%' }}><SwitchIcon /> {t('foundation.editor.line.swap')}</InspectorButton>
      <div className={inspectorDividerClass} />
      <ElementShadowControls element={element} presentation={presentation} runtime={runtime} />
    </div>
  )
}
