// src/views/Editor/Toolbar/MultiStylePanel.vue
<template>
  <div class="multi-style-panel">
    <div class="row">
      <div style="width: 40%;">{{ $t('tableStyle.fillColor') }}</div>
      <Popover trigger="click" style="width: 60%;">
        <template #content>
          <ColorPicker
            :modelValue="fill"
            @update:modelValue="value => updateFill(value)"
          />
        </template>
        <ColorButton :color="fill" />
      </Popover>
    </div>

    <Divider />

    <div class="row">
      <div style="width: 40%;">{{ $t('toolbar.borderStyle') }}</div>
      <SelectCustom style="width: 60%;">
        <template #options>
          <div class="option" v-for="item in lineStyleOptions" :key="item" @click="updateOutline({ style: item })">
            <SVGLine :type="item" />
          </div>
        </template>
        <template #label>
          <SVGLine :type="outline.style" />
        </template>
      </SelectCustom>
    </div>
    <div class="row">
      <div style="width: 40%;">{{ $t('toolbar.borderColor') }}</div>
      <Popover trigger="click" style="width: 60%;">
        <template #content>
          <ColorPicker
            :modelValue="outline.color"
            @update:modelValue="value => updateOutline({ color: value })"
          />
        </template>
        <ColorButton :color="outline.color || '#000'" />
      </Popover>
    </div>
    <div class="row">
      <div style="width: 40%;">{{ $t('toolbar.borderWidth') }}</div>
      <NumberInput 
        :value="outline.width || 0"
        @update:value="value => updateOutline({ width: value })" 
        style="width: 60%;" 
      />
    </div>

    <Divider />

    <SelectGroup class="row">
      <Select
        style="width: 60%;;"
        :value="richTextAttrs.fontname"
        search
        :searchLabel="$t('canvas.fontSearch')"
        autofocus
        @update:value="value => updateFontStyle('fontname', value as string)"
        :options="fontOptions"
      >
        <template #icon>
          <i-icon-park-outline:font-size />
        </template>
      </Select>
      <Select
        style="width: 40%;"
        :value="richTextAttrs.fontsize"
        search
        :searchLabel="$t('canvas.fontSizeSearch')"
        autofocus
        @update:value="value => updateFontStyle('fontsize', value as string)"
        :options="fontSizeOptions.map(item => ({
          label: item, value: item
        }))"
      >
        <template #icon>
          <i-icon-park-outline:add-text />
        </template>
      </Select>
    </SelectGroup>
    <ButtonGroup class="row" passive>
      <Popover trigger="click" style="width: 30%;">
        <template #content>
          <ColorPicker
            :modelValue="richTextAttrs.color"
            @update:modelValue="value => updateFontStyle('color', value)"
          />
        </template>
        <TextColorButton first :color="richTextAttrs.color" v-tooltip="$t('toolbar.textColor')">
          <i-icon-park-outline:text />
        </TextColorButton>
      </Popover>
      <Popover trigger="click" style="width: 30%;">
        <template #content>
          <ColorPicker
            :modelValue="richTextAttrs.backcolor"
            @update:modelValue="value => updateFontStyle('backcolor', value)"
          />
        </template>
        <TextColorButton :color="richTextAttrs.backcolor" v-tooltip="$t('toolbar.textHighlight')">
          <i-icon-park-outline:high-light />
        </TextColorButton>
      </Popover>
      <Button 
        class="font-size-btn"
        style="width: 20%;"
        v-tooltip="$t('common.increaseFontSize')"
        @click="updateFontStyle('fontsize-add', '2')"
      ><i-icon-park-outline:font-size />+</Button>
      <Button
        last
        class="font-size-btn"
        style="width: 20%;"
        v-tooltip="$t('common.decreaseFontSize')"
        @click="updateFontStyle('fontsize-reduce', '2')"
      ><i-icon-park-outline:font-size />-</Button>
    </ButtonGroup>
    <RadioGroup 
      class="row" 
      button-style="solid" 
      :value="richTextAttrs.align"
      @update:value="value => updateFontStyle('align', value)"
    >
      <RadioButton value="left" style="flex: 1;" v-tooltip="$t('common.leftAlign')"><i-icon-park-outline:align-text-left /></RadioButton>
      <RadioButton value="center" style="flex: 1;" v-tooltip="$t('common.centerAlign')"><i-icon-park-outline:align-text-center /></RadioButton>
      <RadioButton value="right" style="flex: 1;" v-tooltip="$t('common.rightAlign')"><i-icon-park-outline:align-text-right /></RadioButton>
      <RadioButton value="justify" style="flex: 1;" v-tooltip="$t('common.justify')"><i-icon-park-outline:align-text-both /></RadioButton>
    </RadioGroup>
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue'
import { storeToRefs } from 'pinia'
import { useMainStore, useSlidesStore } from '@/store'
import type { LineStyleType, PPTElement, PPTElementOutline, TableCell } from '@/types/slides'
import emitter, { EmitterEvents } from '@/utils/emitter'
import useLocalizedFonts from '@/hooks/useLocalizedFonts'
import useHistorySnapshot from '@/hooks/useHistorySnapshot'

import SVGLine from './common/SVGLine.vue'
import ColorButton from '@/components/ColorButton.vue'
import TextColorButton from '@/components/TextColorButton.vue'
import ColorPicker from '@/components/ColorPicker/index.vue'
import Divider from '@/components/Divider.vue'
import Button from '@/components/Button.vue'
import ButtonGroup from '@/components/ButtonGroup.vue'
import RadioButton from '@/components/RadioButton.vue'
import RadioGroup from '@/components/RadioGroup.vue'
import NumberInput from '@/components/NumberInput.vue'
import Select from '@/components/Select.vue'
import SelectGroup from '@/components/SelectGroup.vue'
import SelectCustom from '@/components/SelectCustom.vue'
import Popover from '@/components/Popover.vue'

const slidesStore = useSlidesStore()
const { richTextAttrs, activeElementList } = storeToRefs(useMainStore())
const fontOptions = useLocalizedFonts()

const { addHistorySnapshot } = useHistorySnapshot()

const updateElement = (id: string, props: Partial<PPTElement>) => {
  slidesStore.updateElement({ id, props })
  addHistorySnapshot()
}

const lineStyleOptions = ref<LineStyleType[]>(['solid', 'dashed', 'dotted'])
const fontSizeOptions = [
  '12px', '14px', '16px', '18px', '20px', '22px', '24px', '28px', '32px',
  '36px', '40px', '44px', '48px', '54px', '60px', '66px', '72px', '76px',
  '80px', '88px', '96px', '104px', '112px', '120px',
]

const fill = ref('#fff')
const outline = ref<PPTElementOutline>({
  width: 0,
  color: '#fff',
  style: 'solid',
})

// 批量修改填充色（表格元素为单元格填充、音频元素为图标颜色）
const updateFill = (value: string) => {
  for (const el of activeElementList.value) {
    if (
      el.type === 'text' ||
      el.type === 'shape' ||
      el.type === 'chart'
    ) updateElement(el.id, { fill: value })

    if (el.type === 'table') {
      const data: TableCell[][] = JSON.parse(JSON.stringify(el.data))
      for (let i = 0; i < data.length; i++) {
        for (let j = 0; j < data[i].length; j++) {
          const style = data[i][j].style || {}
          data[i][j].style = { ...style, backcolor: value }
        }
      }
      updateElement(el.id, { data })
    }

    if (el.type === 'audio') updateElement(el.id, { color: value })
  }
  fill.value = value
}

// 修改边框/线条样式
const updateOutline = (outlineProps: Partial<PPTElementOutline>) => {

  for (const el of activeElementList.value) {
    if (
      el.type === 'text' ||
      el.type === 'image' ||
      el.type === 'shape' ||
      el.type === 'table' ||
      el.type === 'chart'
    ) {
      const outline = el.outline || { width: 2, color: '#000', style: 'solid' }
      const props = { outline: { ...outline, ...outlineProps } }
      updateElement(el.id, props)
    }

    if (el.type === 'line') updateElement(el.id, outlineProps)
  }
  outline.value = { ...outline.value, ...outlineProps }
}

// 修改文字样式
const updateFontStyle = (command: string, value: string) => {
  for (const el of activeElementList.value) {
    if (el.type === 'text' || (el.type === 'shape' && el.text?.content)) {
      emitter.emit(EmitterEvents.RICH_TEXT_COMMAND, { target: el.id, action: { command, value } })
    }
    if (el.type === 'table') {
      const data: TableCell[][] = JSON.parse(JSON.stringify(el.data))
      for (let i = 0; i < data.length; i++) {
        for (let j = 0; j < data[i].length; j++) {
          const style = data[i][j].style || {}
          data[i][j].style = { ...style, [command]: value }
        }
      }
      updateElement(el.id, { data })
    }
    if (el.type === 'latex' && command === 'color') {
      updateElement(el.id, { color: value })
    }
  }
}
</script>

<style lang="scss" scoped>
.row {
  width: 100%;
  display: flex;
  align-items: center;
  margin-bottom: 10px;
}
.font-size-btn {
  padding: 0;
}
.option {
  height: 32px;
  padding: 0 5px;
  border-radius: $borderRadius;

  &:not(.selected):hover {
    background-color: rgba($color: $themeColor, $alpha: .05);
    cursor: pointer;
  }

  &.selected {
    color: $themeColor;
    font-weight: 700;
  }
}
</style>

// apps/web/src/features/editor/MultiStylePanel.tsx
import { useState, useSyncExternalStore } from 'react'
import { useTranslation } from 'react-i18next'

import AddTextIcon from '~icons/icon-park-outline/add-text'
import AlignBothIcon from '~icons/icon-park-outline/align-text-both'
import AlignCenterIcon from '~icons/icon-park-outline/align-text-center'
import AlignLeftIcon from '~icons/icon-park-outline/align-text-left'
import AlignRightIcon from '~icons/icon-park-outline/align-text-right'
import FontSizeIcon from '~icons/icon-park-outline/font-size'
import HighlightIcon from '~icons/icon-park-outline/high-light'
import TextIcon from '~icons/icon-park-outline/text'
import type {
  LineStyleType,
  PPTElement,
  PPTElementOutline,
  TableCell,
  TableCellStyle,
} from '@mona/presentation-core/model'
import type { PresentationState } from '@mona/presentation-core'
import type { RichTextAction } from '@mona/rich-text'

import { InspectorButton, InspectorButtonGroup, InspectorColorButton, InspectorNumberInput, InspectorSelect, inspectorDividerClass, inspectorSelectGroupClass } from '@/features/editor/EditorInspectorPrimitives'
import { LinePreview, PropertyRow } from '@/features/editor/ElementStyleCommons'
import type { EditorRuntime } from '@/features/editor/editor-runtime'
import { lineStyleOptions } from '@/features/editor/editor-style-options'
import { editorFontOptions, editorFontSizeOptions } from '@/features/editor/editor-text-options'

type MultiFontCommand = 'align' | 'backcolor' | 'color' | 'fontname' | 'fontsize' | 'fontsize-add' | 'fontsize-reduce'

const cloneTableData = (data: readonly (readonly TableCell[])[]): TableCell[][] => (
  JSON.parse(JSON.stringify(data)) as TableCell[][]
)

export function MultiStylePanel({
  activeElementIds,
  presentation,
  runtime,
}: {
  activeElementIds: string[]
  presentation: PresentationState
  runtime: EditorRuntime
}) {
  const { t } = useTranslation()
  const [fill, setFill] = useState('#fff')
  const [outline, setOutline] = useState<PPTElementOutline>({
    width: 0,
    color: '#fff',
    style: 'solid',
  })
  const richText = useSyncExternalStore(
    runtime.richText.subscribe,
    runtime.richText.getSnapshot,
    runtime.richText.getSnapshot,
  )
  const attrs = richText.attrs
  const slide = presentation.slides[presentation.slideIndex]!
  const selectedIds = new Set(activeElementIds)
  const activeElements = slide.elements.filter(element => selectedIds.has(element.id))
  const commitElement = (id: string, props: Partial<PPTElement>) => runtime.commit('Update multiple element styles', [{
    type: 'element.update',
    payload: { id, props },
  }], { historyKey: 'multi-style-panel' })

  const updateFill = (value: string) => {
    for (const element of activeElements) {
      if (element.type === 'text' || element.type === 'shape' || element.type === 'chart') {
        commitElement(element.id, { fill: value })
      }
      if (element.type === 'table') {
        const data = cloneTableData(element.data)
        for (const row of data) {
          for (const cell of row) cell.style = { ...(cell.style || {}), backcolor: value }
        }
        commitElement(element.id, { data })
      }
      if (element.type === 'audio') commitElement(element.id, { color: value })
    }
    setFill(value)
  }

  const updateOutline = (props: Partial<PPTElementOutline>) => {
    for (const element of activeElements) {
      if (
        element.type === 'text' ||
        element.type === 'image' ||
        element.type === 'shape' ||
        element.type === 'table' ||
        element.type === 'chart'
      ) {
        commitElement(element.id, {
          outline: { ...(element.outline || { width: 2, color: '#000', style: 'solid' }), ...props },
        })
      }
      if (element.type === 'line') commitElement(element.id, props)
    }
    setOutline(current => ({ ...current, ...props }))
  }

  const updateFontStyle = (command: MultiFontCommand, value: string) => {
    for (const element of activeElements) {
      if (element.type === 'text' || (element.type === 'shape' && element.text?.content)) {
        runtime.richText.execute(element.id, { command, value } as RichTextAction, `multi-style-rich-text-${element.id}`)
      }
      if (element.type === 'table') {
        const data = cloneTableData(element.data)
        for (const row of data) {
          for (const cell of row) {
            const style = { ...(cell.style || {}) } as TableCellStyle & Record<string, string>
            Object.assign(style, { [command]: value })
            cell.style = style
          }
        }
        commitElement(element.id, { data })
      }
      if (element.type === 'latex' && command === 'color') commitElement(element.id, { color: value })
    }
  }

  return (
    <div className="mona-multi-style-panel">
      <PropertyRow label={t('foundation.editor.multi.fillColor')}>
        <InspectorColorButton ariaLabel={t('foundation.editor.multi.fillColor')} color={fill} onChange={updateFill} />
      </PropertyRow>

      <div className={inspectorDividerClass} />

      <PropertyRow label={t('foundation.editor.multi.borderStyle')}>
        <InspectorSelect<LineStyleType>
          ariaLabel={t('foundation.editor.multi.borderStyle')}
          onChange={style => updateOutline({ style })}
          options={lineStyleOptions}
          renderLabel={option => <LinePreview type={option?.value || 'solid'} />}
          renderOption={option => <LinePreview type={option.value} />}
          value={outline.style || 'solid'}
        />
      </PropertyRow>
      <PropertyRow label={t('foundation.editor.multi.borderColor')}>
        <InspectorColorButton ariaLabel={t('foundation.editor.multi.borderColor')} color={outline.color || '#000'} onChange={color => updateOutline({ color })} />
      </PropertyRow>
      <PropertyRow label={t('foundation.editor.multi.borderWidth')}>
        <InspectorNumberInput ariaLabel={t('foundation.editor.multi.borderWidth')} min={0} onChange={width => updateOutline({ width })} value={outline.width || 0} />
      </PropertyRow>

      <div className={inspectorDividerClass} />

      <div className={`${inspectorSelectGroupClass} mona-multi-panel-row`}>
        <InspectorSelect
          ariaLabel={t('foundation.editor.text.fontFamily')}
          icon={<FontSizeIcon />}
          onChange={value => updateFontStyle('fontname', value)}
          options={[{ label: t('common.defaultFont'), value: '' }, ...editorFontOptions]}
          search
          searchLabel={t('foundation.editor.text.fontSearch')}
          style={{ width: '60%' }}
          value={attrs.fontname}
        />
        <InspectorSelect
          ariaLabel={t('foundation.editor.text.fontSize')}
          icon={<AddTextIcon />}
          onChange={value => updateFontStyle('fontsize', value)}
          options={editorFontSizeOptions}
          search
          searchLabel={t('foundation.editor.text.fontSizeSearch')}
          style={{ width: '40%' }}
          value={attrs.fontsize}
        />
      </div>
      <InspectorButtonGroup className="mona-multi-panel-row is-passive">
        <InspectorColorButton ariaLabel={t('foundation.editor.text.textColor')} color={attrs.color} icon={<TextIcon />} onChange={value => updateFontStyle('color', value)} style={{ width: '30%' }} />
        <InspectorColorButton ariaLabel={t('foundation.editor.text.highlight')} color={attrs.backcolor} icon={<HighlightIcon />} onChange={value => updateFontStyle('backcolor', value)} style={{ width: '30%' }} />
        <InspectorButton ariaLabel={t('foundation.editor.text.increaseFont')} className="mona-font-size-button" onClick={() => updateFontStyle('fontsize-add', '2')} style={{ width: '20%' }}><FontSizeIcon />+</InspectorButton>
        <InspectorButton ariaLabel={t('foundation.editor.text.decreaseFont')} className="mona-font-size-button" onClick={() => updateFontStyle('fontsize-reduce', '2')} style={{ width: '20%' }}><FontSizeIcon />-</InspectorButton>
      </InspectorButtonGroup>
      <InspectorButtonGroup className="mona-multi-panel-row">
        <InspectorButton active={attrs.align === 'left'} ariaLabel={t('foundation.editor.multi.alignLeft')} onClick={() => updateFontStyle('align', 'left')} style={{ flex: 1 }}><AlignLeftIcon /></InspectorButton>
        <InspectorButton active={attrs.align === 'center'} ariaLabel={t('foundation.editor.multi.alignCenter')} onClick={() => updateFontStyle('align', 'center')} style={{ flex: 1 }}><AlignCenterIcon /></InspectorButton>
        <InspectorButton active={attrs.align === 'right'} ariaLabel={t('foundation.editor.multi.alignRight')} onClick={() => updateFontStyle('align', 'right')} style={{ flex: 1 }}><AlignRightIcon /></InspectorButton>
        <InspectorButton active={attrs.align === 'justify'} ariaLabel={t('foundation.editor.multi.justify')} onClick={() => updateFontStyle('align', 'justify')} style={{ flex: 1 }}><AlignBothIcon /></InspectorButton>
      </InspectorButtonGroup>
    </div>
  )
}
