// src/views/Editor/Toolbar/SlideDesignPanel/index.vue
<template>
  <div class="slide-design-panel">
    <div class="title">{{ $t('designPanel.backgroundFill') }}</div>
    <div class="row">
      <Select 
        style="flex: 1;" 
        :value="background.type" 
        @update:value="value => updateBackgroundType(value as 'gradient' | 'image' | 'solid')"
        :options="[
          { label: $t('toolbar.solidFill'), value: 'solid' },
          { label: $t('toolbar.imageFill'), value: 'image' },
          { label: $t('toolbar.gradientFill'), value: 'gradient' },
        ]"
      />
      <div style="width: 10px;"></div>

      <Popover trigger="click" v-if="background.type === 'solid'" style="flex: 1;">
        <template #content>
          <ColorPicker
            :modelValue="background.color"
            @update:modelValue="color => updateBackground({ color })"
          />
        </template>
        <ColorButton :color="background.color || '#fff'" />
      </Popover>

      <Select 
        style="flex: 1;" 
        :value="background.image?.size || 'cover'" 
        @update:value="value => updateImageBackground({ size: value as SlideBackgroundImageSize })"
        v-else-if="background.type === 'image'"
        :options="[
          { label: $t('designPanel.imageContain'), value: 'contain' },
          { label: $t('designPanel.imageRepeat'), value: 'repeat' },
          { label: $t('designPanel.imageCover'), value: 'cover' },
        ]"
      />

      <Select 
        style="flex: 1;" 
        :value="background.gradient?.type || ''" 
        @update:value="value => updateGradientBackground({ type: value as GradientType })"
        v-else
        :options="[
          { label: $t('toolbar.linearGradient'), value: 'linear' },
          { label: $t('toolbar.radialGradient'), value: 'radial' },
        ]"
      />
    </div>

    <div class="background-image-wrapper" v-if="background.type === 'image'">
      <FileInput @change="files => uploadBackgroundImage(files)">
        <div class="background-image">
          <div class="content" :style="{ backgroundImage: `url(${background.image?.src})` }">
            <i-icon-park-outline:plus />
          </div>
        </div>
      </FileInput>
    </div>

    <div class="background-gradient-wrapper" v-if="background.type === 'gradient'">
      <div class="row">
        <GradientBar
          :value="background.gradient?.colors || []"
          :index="currentGradientIndex"
          @update:value="value => updateGradientBackground({ colors: value })"
          @update:index="index => currentGradientIndex = index"
        />
      </div>
      <div class="row">
        <div style="width: 40%;">{{ $t('toolbar.currentStop') }}</div>
        <Popover trigger="click" style="width: 60%;">
          <template #content>
            <ColorPicker
              :modelValue="background.gradient!.colors[currentGradientIndex].color"
              @update:modelValue="value => updateGradientBackgroundColors(value)"
            />
          </template>
          <ColorButton :color="background.gradient!.colors[currentGradientIndex].color" />
        </Popover>
      </div>
      <div class="row" v-if="background.gradient?.type === 'linear'">
        <div style="width: 40%;">{{ $t('toolbar.gradientAngle') }}</div>
        <Slider
          :min="0"
          :max="360"
          :step="15"
          :value="background.gradient.rotate || 0"
          @update:value="value => updateGradientBackground({ rotate: value as number })"
          style="width: 60%;"
        />
      </div>
    </div>

    <div class="row">
      <Button style="flex: 1;" @click="applyBackgroundAllSlide()"><i-icon-park-outline:check /> {{ $t('designPanel.applyBackgroundAll') }}</Button>
    </div>

    <Divider />

    <div class="row">
      <Select 
        style="width: 100%;" 
        :defaultLabel="$t('common.custom')"
        :value="viewportRatio" 
        @update:value="value => updateViewportRatio(value)"
        :options="[
          { label: $t('designPanel.wide169'), value: 0.5625 },
          { label: $t('designPanel.wide1610'), value: 0.625 },
          { label: $t('designPanel.standard43'), value: 0.75 },
          { label: $t('designPanel.paperLandscape'), value: 0.70710678 },
          { label: $t('designPanel.paperPortrait'), value: 1.41421356 },
          { label: $t('common.custom'), value: 'custom' },
        ]"
      />
    </div>

    <div class="row">
      <div class="canvas-size">{{ $t('designPanel.canvasSize', { width: viewportSize, height: toFixed(viewportSize * viewportRatio) }) }}</div>
    </div>

    <Divider />

    <div class="title">
      <span>{{ $t('designPanel.globalTheme') }}</span>
      <span class="more" @click="moreThemeConfigsVisible = !moreThemeConfigsVisible">
        <span class="text">{{ $t('common.more') }}</span>
        <i-icon-park-outline:down v-if="moreThemeConfigsVisible" />
        <i-icon-park-outline:right v-else />
      </span>
    </div>
    <div class="row">
      <div style="width: 40%;">{{ $t('common.font') }}:</div>
      <Select
        style="width: 60%;"
        :value="theme.fontName"
        search
        :searchLabel="$t('canvas.fontSearch')"
        autofocus
        @update:value="value => updateTheme({ fontName: value as string })"
        :options="fontOptions"
      />
    </div>
    <div class="row">
      <div style="width: 40%;">{{ $t('common.fontColor') }}:</div>
      <Popover trigger="click" style="width: 60%;">
        <template #content>
          <ColorPicker
            :modelValue="theme.fontColor"
            @update:modelValue="value => updateTheme({ fontColor: value })"
          />
        </template>
        <ColorButton :color="theme.fontColor" />
      </Popover>
    </div>
    <div class="row">
      <div style="width: 40%;">{{ $t('common.backgroundColor') }}:</div>
      <Popover trigger="click" style="width: 60%;">
        <template #content>
          <ColorPicker
            :modelValue="theme.backgroundColor"
            @update:modelValue="value => updateTheme({ backgroundColor: value })"
          />
        </template>
        <ColorButton :color="theme.backgroundColor" />
      </Popover>
    </div>
    <div class="row">
      <div style="width: 40%;">{{ $t('common.themeColor') }}:</div>
      <ColorListButton style="width: 60%;" :colors="theme.themeColors" @click="themeColorsSettingVisible = true" />
    </div>
    
    <template v-if="moreThemeConfigsVisible">
      <div class="row">
        <div style="width: 40%;">{{ $t('toolbar.borderStyle') }}</div>
        <SelectCustom style="width: 60%;">
          <template #options>
            <div class="option" v-for="item in lineStyleOptions" :key="item" @click="updateTheme({ outline: { ...theme.outline, style: item } })">
              <SVGLine :type="item" />
            </div>
          </template>
          <template #label>
            <SVGLine :type="theme.outline.style" />
          </template>
        </SelectCustom>
      </div>
      <div class="row">
        <div style="width: 40%;">{{ $t('toolbar.borderColor') }}</div>
        <Popover trigger="click" style="width: 60%;">
          <template #content>
            <ColorPicker
              :modelValue="theme.outline.color"
              @update:modelValue="value => updateTheme({ outline: { ...theme.outline, color: value } })"
            />
          </template>
          <ColorButton :color="theme.outline.color || '#000'" />
        </Popover>
      </div>
      <div class="row">
        <div style="width: 40%;">{{ $t('toolbar.borderWidth') }}</div>
        <NumberInput 
          :value="theme.outline.width || 0" 
          @update:value="value => updateTheme({ outline: { ...theme.outline, width: value } })" 
          style="width: 60%;" 
        />
      </div>
      <div class="row" style="height: 30px;">
        <div style="width: 40%;">{{ $t('toolbar.shadowHorizontal') }}</div>
        <Slider 
          style="width: 60%;"
          :min="-20" 
          :max="20" 
          :step="1" 
          :value="theme.shadow.h" 
          @update:value="value => updateTheme({ shadow: { ...theme.shadow, h: value as number } })"
        />
      </div>
      <div class="row" style="height: 30px;">
        <div style="width: 40%;">{{ $t('toolbar.shadowVertical') }}</div>
        <Slider
          style="width: 60%;"
          :min="-20"
          :max="20"
          :step="1"
          :value="theme.shadow.v"
          @update:value="value => updateTheme({ shadow: { ...theme.shadow, v: value as number } })"
        />
      </div>
      <div class="row" style="height: 30px;">
        <div style="width: 40%;">{{ $t('toolbar.blurRadius') }}</div>
        <Slider
          style="width: 60%;"
          :min="1"
          :max="30"
          :step="1"
          :value="theme.shadow.blur"
          @update:value="value => updateTheme({ shadow: { ...theme.shadow, blur: value as number } })"
        />
      </div>
      <div class="row">
        <div style="width: 40%;">{{ $t('toolbar.shadowColor') }}</div>
        <Popover trigger="click" style="width: 60%;">
          <template #content>
            <ColorPicker
              :modelValue="theme.shadow.color"
              @update:modelValue="value => updateTheme({ shadow: { ...theme.shadow, color: value } })"
            />
          </template>
          <ColorButton :color="theme.shadow.color" />
        </Popover>
      </div>
    </template>

    <div class="row">
      <Button style="flex: 1;" @click="applyThemeToAllSlides(moreThemeConfigsVisible)"><i-icon-park-outline:check /> {{ $t('designPanel.applyThemeAll') }}</Button>
    </div>

    <div class="row">
      <Button style="flex: 1;" @click="applyFontToAllSlides(theme.fontName)"><i-icon-park-outline:check /> {{ $t('designPanel.applyFontAll') }}</Button>
    </div>

    <div class="row">
      <Button style="flex: 1;" @click="themeStylesExtractVisible = true"><i-icon-park-outline:platte /> {{ $t('designPanel.extractTheme') }}</Button>
    </div>

    <Divider />

    <div class="title">{{ $t('designPanel.presetThemes') }}</div>
    <div class="theme-list">
      <div 
        class="theme-item" 
        v-for="(item, index) in PRESET_THEMES" 
        :key="index"
        :style="{
          backgroundColor: item.background,
          fontFamily: item.fontname,
        }"
      >
        <div class="theme-item-content">
          <div class="text" :style="{ color: item.fontColor }">{{ $t('designPanel.sampleText') }}</div>
          <div class="colors">
            <div class="color-block" v-for="(color, index) in item.colors" :key="index" :style="{ backgroundColor: color}"></div>
          </div>

          <div class="btns">
            <Button type="primary" size="small" @click="applyPresetTheme(item)">{{ $t('designPanel.set') }}</Button>
            <Button type="primary" size="small" style="margin-top: 3px;" @click="applyPresetTheme(item, true)">{{ $t('designPanel.setAndApply') }}</Button>
          </div>
        </div>
      </div>
    </div>
  </div>

  <Modal
    v-model:visible="themeStylesExtractVisible" 
    :width="320"
    @closed="themeStylesExtractVisible = false"
  >
    <ThemeStylesExtract @close="themeStylesExtractVisible = false" />
  </Modal>

  <Modal
    v-model:visible="themeColorsSettingVisible" 
    :width="310"
    @closed="themeColorsSettingVisible = false"
  >
    <ThemeColorsSetting @close="themeColorsSettingVisible = false" />
  </Modal>

  <Modal
    v-model:visible="customViewportSizeVisible" 
    :width="300"
    @closed="customViewportSizeVisible = false"
  >
    <ViewportSizeSetting @close="customViewportSizeVisible = false" />
  </Modal>
</template>

<script lang="ts" setup>
import { computed, ref, watch } from 'vue'
import { storeToRefs } from 'pinia'
import { useSlidesStore } from '@/store'
import type { 
  Gradient,
  GradientType,
  SlideBackground,
  SlideBackgroundType,
  SlideTheme,
  SlideBackgroundImage,
  SlideBackgroundImageSize,
  LineStyleType,
} from '@/types/slides'
import { PRESET_THEMES } from '@/configs/theme'
import useLocalizedFonts from '@/hooks/useLocalizedFonts'
import useHistorySnapshot from '@/hooks/useHistorySnapshot'
import useSlideTheme from '@/hooks/useSlideTheme'
import { getImageDataURL } from '@/utils/image'
import { toFixed } from '@/utils/common'

import ThemeStylesExtract from './ThemeStylesExtract.vue'
import ThemeColorsSetting from './ThemeColorsSetting.vue'
import ViewportSizeSetting from './ViewportSizeSetting.vue'
import SVGLine from '../common/SVGLine.vue'
import ColorButton from '@/components/ColorButton.vue'
import ColorListButton from '@/components/ColorListButton.vue'
import FileInput from '@/components/FileInput.vue'
import ColorPicker from '@/components/ColorPicker/index.vue'
import Divider from '@/components/Divider.vue'
import Slider from '@/components/Slider.vue'
import Button from '@/components/Button.vue'
import Select from '@/components/Select.vue'
import Popover from '@/components/Popover.vue'
import SelectCustom from '@/components/SelectCustom.vue'
import NumberInput from '@/components/NumberInput.vue'
import Modal from '@/components/Modal.vue'
import GradientBar from '@/components/GradientBar.vue'

const fontOptions = useLocalizedFonts()
const slidesStore = useSlidesStore()
const { slides, currentSlide, slideIndex, viewportRatio, viewportSize, theme } = storeToRefs(slidesStore)

const moreThemeConfigsVisible = ref(false)
const themeStylesExtractVisible = ref(false)
const themeColorsSettingVisible = ref(false)
const customViewportSizeVisible = ref(false)
const currentGradientIndex = ref(0)
const lineStyleOptions = ref<LineStyleType[]>(['solid', 'dashed', 'dotted'])

const background = computed(() => {
  if (!currentSlide.value.background) {
    return {
      type: 'solid',
      value: '#fff',
    } as SlideBackground
  }
  return currentSlide.value.background
})

const { addHistorySnapshot } = useHistorySnapshot()
const {
  applyPresetTheme,
  applyThemeToAllSlides,
  applyFontToAllSlides,
} = useSlideTheme()

watch(slideIndex, () => {
  currentGradientIndex.value = 0
})

// 设置背景模式：纯色、图片、渐变色
const updateBackgroundType = (type: SlideBackgroundType) => {
  if (type === 'solid') {
    const newBackground: SlideBackground = {
      ...background.value,
      type: 'solid',
      color: background.value.color || '#fff',
    }
    slidesStore.updateSlide({ background: newBackground })
  }
  else if (type === 'image') {
    const newBackground: SlideBackground = {
      ...background.value,
      type: 'image',
      image: background.value.image || {
        src: '',
        size: 'cover',
      },
    }
    slidesStore.updateSlide({ background: newBackground })
  }
  else {
    const newBackground: SlideBackground = {
      ...background.value,
      type: 'gradient',
      gradient: background.value.gradient || {
        type: 'linear',
        colors: [
          { pos: 0, color: '#fff' },
          { pos: 100, color: '#fff' },
        ],
        rotate: 0,
      },
    }
    currentGradientIndex.value = 0
    slidesStore.updateSlide({ background: newBackground })
  }
  addHistorySnapshot()
}

// 设置背景
const updateBackground = (props: Partial<SlideBackground>) => {
  slidesStore.updateSlide({ background: { ...background.value, ...props } })
  addHistorySnapshot()
}

// 设置渐变背景
const updateGradientBackground = (props: Partial<Gradient>) => {
  updateBackground({ gradient: { ...background.value.gradient!, ...props } })
}
const updateGradientBackgroundColors = (color: string) => {
  const colors = background.value.gradient!.colors.map((item, index) => {
    if (index === currentGradientIndex.value) return { ...item, color }
    return item
  })
  updateGradientBackground({ colors })
}

// 设置图片背景
const updateImageBackground = (props: Partial<SlideBackgroundImage>) => {
  updateBackground({ image: { ...background.value.image!, ...props } })
}

// 上传背景图片
const uploadBackgroundImage = (files: FileList) => {
  const imageFile = files[0]
  if (!imageFile) return
  getImageDataURL(imageFile).then(dataURL => updateImageBackground({ src: dataURL }))
}

// 应用当前页背景到全部页面
const applyBackgroundAllSlide = () => {
  const newSlides = slides.value.map(slide => {
    return {
      ...slide,
      background: currentSlide.value.background,
    }
  })
  slidesStore.setSlides(newSlides)
  addHistorySnapshot()
}

// 设置主题
const updateTheme = (themeProps: Partial<SlideTheme>) => {
  slidesStore.setTheme(themeProps)
}

// 设置画布尺寸（宽高比例）
const updateViewportRatio = (value: string | number) => {
  if (value === 'custom') {
    customViewportSizeVisible.value = true
    return
  }
  if (typeof value !== 'number') return
  slidesStore.setViewportRatio(value)
}
</script>

<style lang="scss" scoped>
.slide-design-panel {
  user-select: none;
}
.row {
  width: 100%;
  display: flex;
  align-items: center;
  margin-bottom: 10px;
}
.title {
  display: flex;
  justify-content: space-between;
  margin-bottom: 10px;

  .more {
    cursor: pointer;

    .text {
      font-size: 12px;
      margin-right: 3px;
    }
  }
}
.background-image-wrapper {
  margin-bottom: 10px;
}
.background-image {
  height: 0;
  padding-bottom: 56.25%;
  border: 1px dashed $borderColor;
  border-radius: $borderRadius;
  position: relative;
  transition: all $transitionDelay;

  &:hover {
    border-color: $themeColor;
    color: $themeColor;
  }

  .content {
    @include absolute-0();

    display: flex;
    justify-content: center;
    align-items: center;
    background-position: center;
    background-size: contain;
    background-repeat: no-repeat;
    cursor: pointer;
  }
}
.canvas-size {
  width: 100%;
  color: #888;
  font-size: 12px;
  text-align: center;
}

.theme-list {
  @include flex-grid-layout();
}
.theme-item {
  @include flex-grid-layout-children(2, 48%);

  padding-bottom: 27%;
  border-radius: $borderRadius;
  position: relative;
  cursor: pointer;

  .theme-item-content {
    @include absolute-0();

    display: flex;
    flex-direction: column;
    justify-content: center;
    padding: 8px;
    border: 1px solid $borderColor;
    border-radius: $borderRadius;
  }

  .text {
    font-size: 15px;
  }
  .colors {
    display: flex;
    margin-top: 6px;
  }
  .color-block {
    width: 12px;
    height: 12px;
    margin-right: 2px;
  }

  &:hover .btns {
    opacity: 1;
  }

  .btns {
    @include absolute-0();

    flex-direction: column;
    justify-content: center;
    align-items: center;
    display: flex;
    background-color: rgba($color: #000, $alpha: .25);
    opacity: 0;
    transition: opacity $transitionDelay;
  }
}
.option {
  height: 32px;
  padding: 0 5px;
  border-radius: $borderRadius;

  &:not(.selected):hover {
    background-color: rgba($color: $themeColor, $alpha: .05);
    cursor: pointer;
  }

  &.selected {
    color: $themeColor;
    font-weight: 700;
  }
}
</style>

// apps/web/src/features/editor/SlideDesignPanel.tsx
import { useState, type PointerEvent as ReactPointerEvent } from 'react'
import { useTranslation } from 'react-i18next'
import tinycolor from 'tinycolor2'

import CheckIcon from '~icons/icon-park-outline/check'
import DownIcon from '~icons/icon-park-outline/down'
import PaletteIcon from '~icons/icon-park-outline/platte'
import PlusIcon from '~icons/icon-park-outline/plus'
import RightIcon from '~icons/icon-park-outline/right'
import type {
  Gradient,
  SlideBackground,
  SlideBackgroundImage,
  SlideBackgroundType,
  SlideTheme,
} from '@mona/presentation-core/model'
import { selectPresentation } from '@mona/editor-state'

import { Button } from '@/components/ui/button'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Toggle } from '@/components/ui/toggle'
import { EditorGradientBar } from '@/features/editor/EditorGradientBar'
import {
  InspectorButton,
  InspectorColorButton,
  InspectorNumberInput,
  InspectorSelect,
  InspectorSlider,
} from '@/features/editor/EditorInspectorPrimitives'
import { EditorModal } from '@/features/editor/EditorModal'
import { LinePreview } from '@/features/editor/ElementStyleCommons'
import { useEditorModalClose } from '@/features/editor/editor-modal-context'
import { startListReorder } from '@/features/editor/editor-list-reorder'
import type { EditorRuntime } from '@/features/editor/editor-runtime'
import { fileToDataUrl } from '@/features/editor/editor-image'
import { lineStyleOptions } from '@/features/editor/editor-style-options'
import { editorFontOptions } from '@/features/editor/editor-text-options'
import { useEditorApplication } from '@/features/editor/services/editor-application'
import {
  applyFontToSlides,
  applyThemeToSlides,
  getSlidesThemeStyles,
  PRESET_THEMES,
  setSlideTheme,
  themeState,
  type PresetTheme,
} from '@/features/editor/editor-slide-theme'
import { useEditorSelector } from '@/features/editor/use-editor-selector'
import { PRESENTATION_FILTERS, pickFile } from '@/features/editor/editor-files'

function DesignRow({ children, label, style }: { children: React.ReactNode; label: string; style?: React.CSSProperties }) {
  return <div className="mb-2.5 flex w-full items-center" style={style}><div className="w-2/5">{label}</div><div className="w-3/5 [&>*]:w-full">{children}</div></div>
}

function ThemeColorListButton({ colors, onClick }: { colors: readonly string[]; onClick: () => void }) {
  return (
    <Button aria-label="Theme colors" className="w-full justify-center" onClick={onClick} size="editor" type="button" variant="outline">
      <span className="ml-2 flex h-5 flex-1 outline outline-1 outline-dashed outline-[rgb(102_102_102/0.12)]">
        {colors.slice(0, 12).map((color, index) => <span className="mona-theme-color-block" key={`${color}-${index}`}><span style={{ backgroundColor: color }} /></span>)}
      </span>
      <PaletteIcon className="w-8 text-muted-foreground" />
    </Button>
  )
}

function ViewportSizeSetting({ runtime }: { runtime: EditorRuntime }) {
  const { t } = useTranslation()
  const { notifications } = useEditorApplication()
  const close = useEditorModalClose()
  const presentation = useEditorSelector(runtime.store, selectPresentation)
  const [width, setWidth] = useState(Math.round(presentation.viewportSize * 100) / 100)
  const [height, setHeight] = useState(Math.round(presentation.viewportSize * presentation.viewportRatio * 100) / 100)
  const min = 500
  const max = 2000
  const apply = (nextWidth = width, nextHeight = height) => {
    if (nextWidth < min || nextWidth > max || nextHeight < min || nextHeight > max) {
      notifications.notify({ text: t('designPanel.sizeRangeError', { min, max }), type: 'warning' })
      return
    }
    runtime.commit('Set custom viewport', [
      { type: 'presentation.viewport-size.set', size: nextWidth },
      { type: 'presentation.viewport-ratio.set', ratio: nextHeight / nextWidth },
    ], { historyKey: 'slide-design-viewport' })
    close()
  }
  return (
    <div>
      <div className="mb-3.75 text-[17px] font-bold">{t('designPanel.customCanvas')}</div>
      <div className="mb-2.5 flex w-full items-center text-control [&>div:first-child]:w-12.5 [&>*:last-child]:flex-1"><div>{t('toolbar.width')}</div><InspectorNumberInput ariaLabel={t('toolbar.width')} max={max} min={min} onChange={setWidth} onEnter={value => apply(value, height)} value={width} /></div>
      <div className="mb-2.5 flex w-full items-center text-control [&>div:first-child]:w-12.5 [&>*:last-child]:flex-1"><div>{t('toolbar.height')}</div><InspectorNumberInput ariaLabel={t('toolbar.height')} max={max} min={min} onChange={setHeight} onEnter={value => apply(width, value)} value={height} /></div>
      <div className="mb-4.5 text-xs text-muted-foreground">{t('designPanel.sizeRange', { min, max })}</div>
      <div className="flex justify-end gap-2.5">
        <InspectorButton active ariaLabel={t('common.confirm')} onClick={apply}>{t('common.confirm')}</InspectorButton>
        <InspectorButton ariaLabel={t('common.cancel')} onClick={close}>{t('common.cancel')}</InspectorButton>
      </div>
    </div>
  )
}

function ThemeColorsSetting({ runtime }: { runtime: EditorRuntime }) {
  const { t } = useTranslation()
  const close = useEditorModalClose()
  const presentation = useEditorSelector(runtime.store, selectPresentation)
  const [colors, setColors] = useState(() => {
    const next = [...presentation.theme.themeColors]
    while (next.length < 6) next.push('#00000000')
    return next
  })
  const startReorder = (event: ReactPointerEvent<HTMLDivElement>, oldIndex: number) => startListReorder(event, oldIndex, {
    getRows: () => document.querySelectorAll<HTMLElement>('.mona-theme-colors-row'),
    onReorder: (from, to) => setColors(current => {
      const next = [...current]
      const item = next.splice(from, 1)[0]!
      next.splice(to, 0, item)
      return next
    }),
  })
  const confirm = () => {
    let next = colors.filter(color => color !== '#00000000')
    if (!next.length) next = ['#00000000']
    runtime.commit('Set theme colors', [{
      type: 'presentation.theme.update',
      props: { themeColors: next },
    }], { historyKey: 'slide-design-theme-colors' })
    close()
  }
  return (
    <div className="flex flex-col">
      <div className="mb-3.75 text-[17px] font-bold">{t('designPanel.editThemeColors')}</div>
      {colors.map((color, index) => (
        <div className="mona-theme-colors-row mb-2.5 flex w-full items-center [&>*:last-child]:w-3/5" key={index}>
          <div className="w-2/5 cursor-move text-control" onPointerDown={event => startReorder(event, index)}>{t('designPanel.slideThemeColor', { number: index + 1 })}</div>
          <InspectorColorButton ariaLabel={t('designPanel.slideThemeColor', { number: index + 1 })} color={color} onChange={value => setColors(current => current.map((item, itemIndex) => itemIndex === index ? value : item))} />
        </div>
      ))}
      <InspectorButton active ariaLabel={t('common.confirm')} onClick={confirm} style={{ marginTop: 12, width: '100%' }}>{t('common.confirm')}</InspectorButton>
    </div>
  )
}

function ThemeStylesExtract({ runtime }: { runtime: EditorRuntime }) {
  const { t } = useTranslation()
  const { notifications } = useEditorApplication()
  const close = useEditorModalClose()
  const presentation = useEditorSelector(runtime.store, selectPresentation)
  const [activeTab, setActiveTab] = useState<'single' | 'all'>('single')
  // The source captures extraction results when the modal opens and only
  // recalculates them when its tab changes. Applying one extracted value to
  // the theme must not silently reorder the remaining choices mid-session.
  const [styles, setStyles] = useState(() => getSlidesThemeStyles(presentation.slides[presentation.slideIndex]!, presentation.theme))
  const [selection, setSelection] = useState({ backgroundColor: 0, fontColor: 0, fontName: 0, themeColors: styles.themeColors.map((_, index) => index) })
  const selectTab = (tab: 'single' | 'all') => {
    const nextStyles = getSlidesThemeStyles(tab === 'single' ? presentation.slides[presentation.slideIndex]! : presentation.slides, presentation.theme)
    setActiveTab(tab)
    setStyles(nextStyles)
    setSelection({ backgroundColor: 0, fontColor: 0, fontName: 0, themeColors: nextStyles.themeColors.map((_, index) => index) })
  }
  const updateTheme = (props: Partial<SlideTheme>) => runtime.commit('Update extracted theme', [{
    type: 'presentation.theme.update',
    props,
  }], { historyKey: 'slide-design-extracted-theme' })
  const apply = () => {
    let themeColors = styles.themeColors.filter((_, index) => selection.themeColors.includes(index))
    if (themeColors.length > 6) {
      themeColors = themeColors.slice(0, 6)
      notifications.notify({ text: t('designPanel.themeColorLimit'), type: 'warning' })
    }
    const props: Partial<SlideTheme> = {}
    const backgroundColor = styles.backgroundColors[selection.backgroundColor]
    const fontColor = styles.fontColors[selection.fontColor]
    const fontName = styles.fontNames[selection.fontName]
    if (backgroundColor) props.backgroundColor = backgroundColor
    if (fontColor) props.fontColor = fontColor
    if (fontName) props.fontName = fontName
    if (themeColors.length) props.themeColors = themeColors
    updateTheme(props)
    close()
  }
  const readable = (color: string) => tinycolor.mostReadable(color, ['#000', '#fff'], { includeFallbackColors: true }).toRgbString()
  const hex = (color: string) => {
    const value = tinycolor(color)
    return (value.getAlpha() < 1 ? value.toHex8String() : value.toHexString()).toUpperCase()
  }
  const optionRows = [
    { key: 'fontName' as const, label: `${t('common.font')}:`, values: styles.fontNames, visual: (value: string) => <span className="h-6.25 w-37.5 truncate rounded-control border px-1.25 text-center text-xs leading-[25px]" style={{ fontFamily: value }}>{editorFontOptions.find(item => item.value === value)?.label || value}</span>, apply: (value: string) => updateTheme({ fontName: value }) },
    { key: 'fontColor' as const, label: `${t('toolbar.textColor')}:`, values: styles.fontColors, visual: (value: string) => <span className="h-6.25 w-37.5 truncate rounded-control border px-1.25 text-center text-xs leading-[25px]" style={{ backgroundColor: value, color: readable(value) }}>{hex(value)}</span>, apply: (value: string) => updateTheme({ fontColor: value }) },
    { key: 'backgroundColor' as const, label: `${t('common.backgroundColor')}:`, values: styles.backgroundColors, visual: (value: string) => <span className="h-6.25 w-37.5 truncate rounded-control border px-1.25 text-center text-xs leading-[25px]" style={{ backgroundColor: value, color: readable(value) }}>{hex(value)}</span>, apply: (value: string) => updateTheme({ backgroundColor: value }) },
  ]
  return (
    <div className="flex h-125 flex-col">
      <Tabs onValueChange={value => selectTab(value as 'single' | 'all')} value={activeTab}>
        <TabsList className="w-full justify-start border-b" variant="line">
          <TabsTrigger value="single">{t('designPanel.extractCurrent')}</TabsTrigger>
          <TabsTrigger value="all">{t('designPanel.extractAll')}</TabsTrigger>
        </TabsList>
      </Tabs>
      <div className="mr-[-20px] flex-1 overflow-auto pr-5">
        {optionRows.map(row => row.values.length ? (
          <div className="border-b border-dashed pt-3 pb-2.5 text-control" key={row.key}>
            <div className="mb-1.25 flex items-center [&_span]:text-xs [&_span]:text-muted-foreground">{row.label}</div>
            {row.values.map((value, index) => (
              <div className="mt-0.75 flex items-center justify-between" key={value}>
                {row.visual(value)}
                <div className="ml-2.5 flex flex-1 items-center justify-between text-xs">
                  <span className={selection[row.key] === index ? 'text-field opacity-100' : 'text-field opacity-0'}><CheckIcon /></span>
                  <Button onClick={() => setSelection(current => ({ ...current, [row.key]: index }))} size="xs" type="button" variant="ghost">{t('common.select')}</Button>
                  <Button onClick={() => {
                    row.apply(value); setSelection(current => ({ ...current, [row.key]: index })) 
                  }} size="xs" type="button" variant="ghost">{t('designPanel.applyToTheme')}</Button>
                </div>
              </div>
            ))}
          </div>
        ) : null)}
        {styles.themeColors.length ? (
          <div className="border-b border-dashed pt-3 pb-2.5 text-control">
            <div className="mb-1.25 flex items-center [&_span]:text-xs [&_span]:text-muted-foreground">{`${t('common.themeColor')}: `}<span>({t('designPanel.excludeColorTip')})</span></div>
            <div className="grid grid-cols-10 gap-[1.111111%] [&_button]:relative [&_button]:h-6.25 [&_button]:rounded-control [&_button]:border [&_button]:p-0 [&_button.is-disabled]:opacity-20 [&_button.is-disabled]:before:absolute [&_button.is-disabled]:before:top-2.75 [&_button.is-disabled]:before:-left-px [&_button.is-disabled]:before:h-0.5 [&_button.is-disabled]:before:w-6 [&_button.is-disabled]:before:rotate-45 [&_button.is-disabled]:before:bg-black [&_button.is-disabled]:before:content-[''] [&_button.is-disabled]:after:absolute [&_button.is-disabled]:after:top-2.75 [&_button.is-disabled]:after:-left-px [&_button.is-disabled]:after:h-0.5 [&_button.is-disabled]:after:w-6 [&_button.is-disabled]:after:-rotate-45 [&_button.is-disabled]:after:bg-black [&_button.is-disabled]:after:content-['']">
              {styles.themeColors.map((color, index) => (
                <Toggle
                  aria-label={color}
                  className={selection.themeColors.includes(index) ? '' : 'is-disabled'}
                  key={color}
                  onPressedChange={() => setSelection(current => ({ ...current, themeColors: current.themeColors.includes(index) ? current.themeColors.filter(item => item !== index) : [...current.themeColors, index] }))}
                  pressed={selection.themeColors.includes(index)}
                  style={{ backgroundColor: color }}
                />
              ))}
            </div>
          </div>
        ) : null}
      </div>
      <InspectorButton active ariaLabel={t('designPanel.saveSelectedTheme')} onClick={apply} style={{ marginTop: 12, width: '100%' }}><CheckIcon /> {t('designPanel.saveSelectedTheme')}</InspectorButton>
    </div>
  )
}

export function SlideDesignPanel({ runtime }: { runtime: EditorRuntime }) {
  const { t } = useTranslation()
  const presentation = useEditorSelector(runtime.store, selectPresentation)
  const slide = presentation.slides[presentation.slideIndex]!
  const background: SlideBackground = slide.background || { type: 'solid', color: '#fff' }
  const [more, setMore] = useState(false)
  const [gradientIndex, setGradientIndex] = useState(0)
  const [themeColorsOpen, setThemeColorsOpen] = useState(false)
  const [themeExtractOpen, setThemeExtractOpen] = useState(false)
  const [viewportOpen, setViewportOpen] = useState(false)
  const historyKey = 'slide-design-panel'

  const updateBackground = (props: Partial<SlideBackground>) => runtime.commit('Update slide background', [{ type: 'slide.update', props: { background: { ...background, ...props } as SlideBackground } }], { historyKey })
  const updateBackgroundType = (type: SlideBackgroundType) => {
    if (type === 'solid') updateBackground({ type: 'solid', color: background.color || '#fff' })
    else if (type === 'image') updateBackground({ type: 'image', image: background.image || { src: '', size: 'cover' } })
    else {
      setGradientIndex(0)
      updateBackground({ type: 'gradient', gradient: background.gradient || { type: 'linear', colors: [{ pos: 0, color: '#fff' }, { pos: 100, color: '#fff' }], rotate: 0 } })
    }
  }
  const updateGradient = (props: Partial<Gradient>) => updateBackground({ gradient: { ...background.gradient!, ...props } })
  const updateImage = (props: Partial<SlideBackgroundImage>) => updateBackground({ image: { ...background.image!, ...props } })
  const updateTheme = (props: Partial<SlideTheme>) => runtime.commit('Update presentation theme', [{
    type: 'presentation.theme.update',
    props,
  }], { historyKey: 'slide-design-theme' })
  const applyBackgroundAll = () => runtime.commit('Apply background to all slides', [{
    type: 'presentation.slides.replace',
    slides: presentation.slides.map(candidate => ({ ...candidate, background: slide.background })),
  }], { historyKey })
  const applyPreset = (preset: PresetTheme, apply = false) => {
    const commands: Parameters<EditorRuntime['commit']>[1] = [{ type: 'presentation.theme.update', props: themeState(preset) }]
    if (apply) {
      const slides = JSON.parse(JSON.stringify(presentation.slides)) as typeof presentation.slides
      for (const candidate of slides) setSlideTheme(candidate, preset)
      commands.push({ type: 'presentation.slides.replace', slides })
    }
    runtime.commit('Apply preset theme', commands, { historyKey })
  }
  const ratioOptions: Array<{ label: string; value: number | string }> = [
    { label: t('designPanel.wide169'), value: .5625 },
    { label: t('designPanel.wide1610'), value: .625 },
    { label: t('designPanel.standard43'), value: .75 },
    { label: t('designPanel.paperLandscape'), value: .70710678 },
    { label: t('designPanel.paperPortrait'), value: 1.41421356 },
    { label: t('common.custom'), value: 'custom' },
  ]
  const canvasSize = t('designPanel.canvasSize', { width: presentation.viewportSize, height: Math.round(presentation.viewportSize * presentation.viewportRatio * 100) / 100 })

  return (
    <div className="select-none">
      <div className="mb-2.5 flex justify-between">{t('designPanel.backgroundFill')}</div>
      <div className="mb-2.5 flex w-full items-center gap-2.5 [&>*]:min-w-0 [&>*]:flex-1">
        <InspectorSelect ariaLabel={t('designPanel.backgroundFill')} onChange={value => updateBackgroundType(value)} options={[
          { label: t('toolbar.solidFill'), value: 'solid' },
          { label: t('toolbar.imageFill'), value: 'image' },
          { label: t('toolbar.gradientFill'), value: 'gradient' },
        ]} value={background.type} />
        {background.type === 'solid' ? <InspectorColorButton ariaLabel={t('designPanel.backgroundFill')} color={background.color || '#fff'} onChange={color => updateBackground({ color })} /> : null}
        {background.type === 'image' ? <InspectorSelect ariaLabel={t('designPanel.backgroundFill')} onChange={value => updateImage({ size: value })} options={[
          { label: t('designPanel.imageContain'), value: 'contain' },
          { label: t('designPanel.imageRepeat'), value: 'repeat' },
          { label: t('designPanel.imageCover'), value: 'cover' },
        ]} value={background.image?.size || 'cover'} /> : null}
        {background.type === 'gradient' ? <InspectorSelect ariaLabel={t('toolbar.gradientFill')} onChange={value => updateGradient({ type: value })} options={[
          { label: t('toolbar.linearGradient'), value: 'linear' },
          { label: t('toolbar.radialGradient'), value: 'radial' },
        ]} value={background.gradient?.type || 'linear'} /> : null}
      </div>
      {background.type === 'image' ? (
        <Button
          className="relative mb-2.5 block h-0 w-full rounded-control border border-dashed p-0 pb-[56.25%] transition-colors hover:border-foreground hover:text-foreground"
          onClick={() => {
            void pickFile(PRESENTATION_FILTERS.image).then(async file => {
              if (file) updateImage({ src: await fileToDataUrl(file) })
            })
          }}
          type="button"
          variant="ghost"
        >
          <span className="absolute inset-0 flex items-center justify-center bg-contain bg-center bg-no-repeat" style={{ backgroundImage: `url(${background.image?.src})` }}><PlusIcon /></span>
        </Button>
      ) : null}
      {background.type === 'gradient' && background.gradient ? (
        <div>
          <div className="flex w-full items-center mb-2.5"><EditorGradientBar index={Math.min(gradientIndex, background.gradient.colors.length - 1)} onChange={colors => updateGradient({ colors })} onIndexChange={setGradientIndex} value={background.gradient.colors} /></div>
          <DesignRow label={t('toolbar.currentStop')}><InspectorColorButton ariaLabel={t('toolbar.currentStop')} color={background.gradient.colors[gradientIndex]?.color || '#fff'} onChange={color => updateGradient({ colors: background.gradient!.colors.map((item, index) => index === gradientIndex ? { ...item, color } : item) })} /></DesignRow>
          {background.gradient.type === 'linear' ? <DesignRow label={t('toolbar.gradientAngle')}><InspectorSlider ariaLabel={t('toolbar.gradientAngle')} max={360} min={0} onChange={rotate => updateGradient({ rotate })} step={15} value={background.gradient.rotate || 0} /></DesignRow> : null}
        </div>
      ) : null}
      <div className="flex w-full items-center mb-2.5"><InspectorButton ariaLabel={t('designPanel.applyBackgroundAll')} onClick={applyBackgroundAll} style={{ width: '100%' }}><CheckIcon /> {t('designPanel.applyBackgroundAll')}</InspectorButton></div>
      <div className="my-6 w-full border-t border-black/[0.06]" />
      <div className="flex w-full items-center mb-2.5"><InspectorSelect ariaLabel={t('designPanel.customCanvas')} onChange={value => {
        if (value === 'custom') setViewportOpen(true); else if (typeof value === 'number') runtime.commit('Set viewport ratio', [{ type: 'presentation.viewport-ratio.set', ratio: value }], { historyKey: 'slide-design-viewport' }) 
      }} options={ratioOptions} value={ratioOptions.some(option => option.value === presentation.viewportRatio) ? presentation.viewportRatio : 'custom'} /></div>
      <div className="w-full text-center text-xs text-muted-foreground">{canvasSize}</div>
      <div className="my-6 w-full border-t border-black/[0.06]" />
      <div className="mb-2.5 flex justify-between"><span>{t('designPanel.globalTheme')}</span><Button className="gap-0.75 text-xs" onClick={() => setMore(value => !value)} size="xs" type="button" variant="ghost"><span>{t('common.more')}</span>{more ? <DownIcon /> : <RightIcon />}</Button></div>
      <DesignRow label={`${t('common.font')}:`}><InspectorSelect ariaLabel={t('common.font')} onChange={fontName => updateTheme({ fontName })} options={[{ label: t('common.defaultFont'), value: '' }, ...editorFontOptions]} search searchLabel={t('canvas.fontSearch')} value={presentation.theme.fontName} /></DesignRow>
      <DesignRow label={`${t('common.fontColor')}:`}><InspectorColorButton ariaLabel={t('common.fontColor')} color={presentation.theme.fontColor} onChange={fontColor => updateTheme({ fontColor })} /></DesignRow>
      <DesignRow label={`${t('common.backgroundColor')}:`}><InspectorColorButton ariaLabel={t('common.backgroundColor')} color={presentation.theme.backgroundColor} onChange={backgroundColor => updateTheme({ backgroundColor })} /></DesignRow>
      <DesignRow label={`${t('common.themeColor')}:`}><ThemeColorListButton colors={presentation.theme.themeColors} onClick={() => setThemeColorsOpen(true)} /></DesignRow>
      {more ? (
        <>
          <DesignRow label={t('toolbar.borderStyle')}><InspectorSelect ariaLabel={t('toolbar.borderStyle')} onChange={style => updateTheme({ outline: { ...presentation.theme.outline, style } })} options={lineStyleOptions} renderLabel={option => <LinePreview type={option?.value || 'solid'} />} renderOption={option => <LinePreview type={option.value} />} value={presentation.theme.outline.style || 'solid'} /></DesignRow>
          <DesignRow label={t('toolbar.borderColor')}><InspectorColorButton ariaLabel={t('toolbar.borderColor')} color={presentation.theme.outline.color || '#000'} onChange={color => updateTheme({ outline: { ...presentation.theme.outline, color } })} /></DesignRow>
          <DesignRow label={t('toolbar.borderWidth')}><InspectorNumberInput ariaLabel={t('toolbar.borderWidth')} onChange={width => updateTheme({ outline: { ...presentation.theme.outline, width } })} value={presentation.theme.outline.width || 0} /></DesignRow>
          <DesignRow label={t('toolbar.shadowHorizontal')} style={{ height: 30 }}><InspectorSlider ariaLabel={t('toolbar.shadowHorizontal')} max={20} min={-20} onChange={h => updateTheme({ shadow: { ...presentation.theme.shadow, h } })} value={presentation.theme.shadow.h} /></DesignRow>
          <DesignRow label={t('toolbar.shadowVertical')} style={{ height: 30 }}><InspectorSlider ariaLabel={t('toolbar.shadowVertical')} max={20} min={-20} onChange={v => updateTheme({ shadow: { ...presentation.theme.shadow, v } })} value={presentation.theme.shadow.v} /></DesignRow>
          <DesignRow label={t('toolbar.blurRadius')} style={{ height: 30 }}><InspectorSlider ariaLabel={t('toolbar.blurRadius')} max={30} min={1} onChange={blur => updateTheme({ shadow: { ...presentation.theme.shadow, blur } })} value={presentation.theme.shadow.blur} /></DesignRow>
          <DesignRow label={t('toolbar.shadowColor')}><InspectorColorButton ariaLabel={t('toolbar.shadowColor')} color={presentation.theme.shadow.color} onChange={color => updateTheme({ shadow: { ...presentation.theme.shadow, color } })} /></DesignRow>
        </>
      ) : null}
      <div className="flex w-full items-center mb-2.5"><InspectorButton ariaLabel={t('designPanel.applyThemeAll')} onClick={() => runtime.commit('Apply theme to all slides', [{ type: 'presentation.slides.replace', slides: applyThemeToSlides(presentation.slides, presentation.theme, more) }], { historyKey })} style={{ width: '100%' }}><CheckIcon /> {t('designPanel.applyThemeAll')}</InspectorButton></div>
      <div className="flex w-full items-center mb-2.5"><InspectorButton ariaLabel={t('designPanel.applyFontAll')} onClick={() => runtime.commit('Apply font to all slides', [{ type: 'presentation.slides.replace', slides: applyFontToSlides(presentation.slides, presentation.theme.fontName) }], { historyKey })} style={{ width: '100%' }}><CheckIcon /> {t('designPanel.applyFontAll')}</InspectorButton></div>
      <div className="flex w-full items-center mb-2.5"><InspectorButton ariaLabel={t('designPanel.extractTheme')} onClick={() => setThemeExtractOpen(true)} style={{ width: '100%' }}><PaletteIcon /> {t('designPanel.extractTheme')}</InspectorButton></div>
      <div className="my-6 w-full border-t border-black/[0.06]" />
      <div className="mb-2.5 flex justify-between">{t('designPanel.presetThemes')}</div>
      <div className="flex flex-wrap content-start">
        {PRESET_THEMES.map((preset, index) => (
          <div className="group/preset relative mb-[4%] w-[48%] rounded-control pb-[27%] [&:not(:nth-child(2n))]:mr-[4%]" key={index} style={{ backgroundColor: preset.background, fontFamily: preset.fontname }}>
            <div className="absolute inset-0 flex flex-col justify-center rounded-control border p-2">
              <div className="text-field" style={{ color: preset.fontColor }}>{t('designPanel.sampleText')}</div>
              <div className="mt-1.5 flex [&>span]:mr-0.5 [&>span]:size-3">{preset.colors.map((color, colorIndex) => <span key={colorIndex} style={{ backgroundColor: color }} />)}</div>
              <div className="absolute inset-0 flex flex-col items-center justify-center gap-0.75 bg-black/25 opacity-0 transition-opacity group-hover/preset:opacity-100">
                <Button className="h-6 text-xs" onClick={() => applyPreset(preset)} size="xs" type="button">{t('designPanel.set')}</Button>
                <Button className="h-6 text-xs" onClick={() => applyPreset(preset, true)} size="xs" type="button">{t('designPanel.setAndApply')}</Button>
              </div>
            </div>
          </div>
        ))}
      </div>
      {themeColorsOpen ? <EditorModal onClose={() => setThemeColorsOpen(false)} open title={t('designPanel.editThemeColors')} width={310}><ThemeColorsSetting runtime={runtime} /></EditorModal> : null}
      {themeExtractOpen ? <EditorModal onClose={() => setThemeExtractOpen(false)} open title={t('designPanel.extractTheme')} width={320}><ThemeStylesExtract runtime={runtime} /></EditorModal> : null}
      {viewportOpen ? <EditorModal onClose={() => setViewportOpen(false)} open title={t('designPanel.customCanvas')} width={300}><ViewportSizeSetting runtime={runtime} /></EditorModal> : null}
    </div>
  )
}
