// apps/web/src/features/mobile/MobilePlayer.tsx
/* oxlint-disable jsx-a11y/click-events-have-key-events, jsx-a11y/no-static-element-interactions -- The rotated full-screen mobile navigation surface intentionally mirrors the established editor's touch/click contract. */
import { useEffect, useMemo, useRef, useState } from 'react'
import { useTranslation } from 'react-i18next'

import LogoutIcon from '~icons/icon-park-outline/logout'
import { selectPresentation } from '@mona/editor-state'

import { Button } from '@/components/ui/button'
import type { EditorRuntime } from '@/features/editor/editor-runtime'
import { useEditorSelector } from '@/features/editor/use-editor-selector'
import { MobileThumbnails } from '@/features/mobile/MobileThumbnails'
import type { MobileMode } from '@/features/mobile/MobileView'
import { ScaledSlide } from '@/features/presentation-renderer/ScaledSlide'

const RANDOM_TURNING_MODES = ['fade', 'slideX', 'slideY'] as const
const resolveTurningModes = (slides: readonly import('@mona/presentation-core/model').Slide[]) => slides.map(slide => {
  let turningMode = slide.turningMode || 'slideY'
  // the source editor intentionally resolves a fresh random transition whenever the slides collection invalidates.
  // eslint-disable-next-line react-hooks/purity
  if (turningMode === 'random') turningMode = RANDOM_TURNING_MODES[Math.floor(Math.random() * RANDOM_TURNING_MODES.length)]!
  return { ...slide, turningMode }
})

export function MobilePlayer({ changeMode, runtime }: {
  changeMode: (mode: MobileMode) => void
  runtime: EditorRuntime
}) {
  const { t } = useTranslation()
  const presentation = useEditorSelector(runtime.store, selectPresentation)
  const [toolVisible, setToolVisible] = useState(false)
  const [playerSize] = useState(() => ({ width: document.body.clientHeight, height: document.body.clientWidth }))
  const touchStartRef = useRef<{ x: number; y: number } | null>(null)

  useEffect(() => {
    if (runtime.store.getState().presentation.slideIndex !== 0) runtime.focusSlide(0)
  }, [runtime])

  const slides = useMemo(() => resolveTurningModes(presentation.slides), [presentation.slides])

  const playerRatio = playerSize.width ? playerSize.height / playerSize.width : 0
  const slideSize = playerRatio >= presentation.viewportRatio
    ? { width: playerSize.width, height: playerSize.width * presentation.viewportRatio }
    : { height: playerSize.height, width: playerSize.height / presentation.viewportRatio }
  const currentMode = slides[presentation.slideIndex]?.turningMode

  const finishTouch = (event: React.TouchEvent) => {
    const start = touchStartRef.current
    const touch = event.changedTouches[0]
    touchStartRef.current = null
    if (!start || !touch) return
    const offsetX = touch.pageX - start.x
    const offsetY = touch.pageY - start.y
    const offsetAbsX = Math.abs(offsetX)
    const offsetAbsY = Math.abs(offsetY)
    if (offsetAbsX > offsetAbsY && offsetAbsX > 50) {
      if (offsetX < 0 && presentation.slideIndex > 0) runtime.focusSlide(presentation.slideIndex - 1)
      if (offsetX > 0 && presentation.slideIndex < slides.length - 1) runtime.focusSlide(presentation.slideIndex + 1)
    }
    if (offsetAbsY > offsetAbsX && offsetAbsY > 50) {
      if (offsetY > 0 && presentation.slideIndex > 0) runtime.focusSlide(presentation.slideIndex - 1)
      if (offsetY < 0 && presentation.slideIndex < slides.length - 1) runtime.focusSlide(presentation.slideIndex + 1)
    }
  }

  return (
    <div
      className="mona-mobile-player"
      style={{
        width: playerSize.width,
        height: playerSize.height,
        transform: `rotate(90deg) translateY(-${playerSize.height}px)`,
      }}
    >
      <div
        className="mona-mobile-player-slides"
        onClick={() => setToolVisible(value => !value)}
        onTouchEnd={finishTouch}
        onTouchStart={event => {
          const touch = event.changedTouches[0]
          if (touch) touchStartRef.current = { x: touch.pageX, y: touch.pageY }
        }}
      >
        {slides.map((slide, index) => {
          const distance = index - presentation.slideIndex
          const classes = [
            'mona-mobile-player-slide',
            `turning-mode-${slide.turningMode}`,
            distance === 0 ? 'is-current' : distance < 0 ? 'is-before' : 'is-after',
            distance === -1 ? 'is-last' : '',
            distance === 1 ? 'is-next' : '',
            Math.abs(distance) === 1 && slide.turningMode !== currentMode ? 'is-hidden' : '',
          ].filter(Boolean).join(' ')
          return (
            <div className={classes} key={slide.id}>
              {Math.abs(distance) < 2 ? (
                <div className="mona-mobile-player-slide-content" style={slideSize}>
                  <ScaledSlide
                    fixedWidth={slideSize.width}
                    slide={slide}
                    theme={presentation.theme}
                    thumbnail
                    viewportRatio={presentation.viewportRatio}
                    viewportSize={presentation.viewportSize}
                  />
                </div>
              ) : null}
            </div>
          )
        })}
      </div>
      {toolVisible ? (
        <>
          <div className="mona-mobile-player-header">
            <Button className="mona-mobile-player-back" onClick={() => changeMode('preview')} size="editor" type="button" variant="ghost"><LogoutIcon /> {t('mobile.exitPlay')}</Button>
          </div>
          <MobileThumbnails className="mona-mobile-player-thumbnails" runtime={runtime} />
        </>
      ) : null}
    </div>
  )
}

// src/views/Mobile/MobilePlayer.vue
<template>
  <div class="mobile-player" 
    :style="{
      width: playerSize.width + 'px',
      height: playerSize.height + 'px',
      transform: `rotate(90deg) translateY(-${playerSize.height}px)`,
    }"
  >
    <div 
      class="screen-slide-list" 
      @click="toolVisible = !toolVisible"
      @touchstart="$event => touchStartListener($event)"
      @touchend="$event => touchEndListener($event)"
    >
      <div 
        :class="[
          'slide-item', 
          `turning-mode-${slide.turningMode || 'slideY'}`,
          {
            'current': index === slideIndex,
            'before': index < slideIndex,
            'after': index > slideIndex,
            'hide': (index === slideIndex - 1 || index === slideIndex + 1) && slide.turningMode !== slidesWithTurningMode[slideIndex].turningMode,
            'last': index === slideIndex - 1,
            'next': index === slideIndex + 1,
          }
        ]"
        v-for="(slide, index) in slidesWithTurningMode" 
        :key="slide.id"
      >
        <div 
          class="slide-content" 
          :style="{
            width: slideSize.width + 'px',
            height: slideSize.height + 'px',
          }"
          v-if="Math.abs(slideIndex - index) < 2"
        >
          <ThumbnailSlide 
            :slide="slide" 
            :size="slideSize.width" 
          />
        </div>
      </div>
    </div>

    <template v-if="toolVisible">
      <div class="header">
        <div class="back" @click="changeMode('preview')"><i-icon-park-outline:logout /> {{ $t('mobile.exitPlay') }}</div>
      </div>
      <MobileThumbnails class="thumbnails" />
    </template>
  </div>
</template>

<script lang="ts" setup>
import { computed, onMounted, ref } from 'vue'
import { storeToRefs } from 'pinia'
import { useSlidesStore } from '@/store'
import type { Mode } from '@/types/mobile'
import useSlidesWithTurningMode from '../Screen/hooks/useSlidesWithTurningMode'

import ThumbnailSlide from '@/views/components/ThumbnailSlide/index.vue'
import MobileThumbnails from './MobileThumbnails.vue'

defineProps<{
  changeMode: (mode: Mode) => void
}>()

const slidesStore = useSlidesStore()
const { slides, slideIndex, viewportRatio } = storeToRefs(slidesStore)

const { slidesWithTurningMode } = useSlidesWithTurningMode()

const toolVisible = ref(false)

const playerSize = ref({ width: 0, height: 0 })

onMounted(() => {
  if (slideIndex.value !== 0) slidesStore.updateSlideIndex(0)

  playerSize.value = {
    width: document.body.clientHeight,
    height: document.body.clientWidth,
  }
})

const slideSize = computed(() => {
  const playerRatio = playerSize.value.height / playerSize.value.width

  let slideWidth = 0
  let slideHeight = 0

  if (playerRatio >= viewportRatio.value) {
    slideWidth = playerSize.value.width
    slideHeight = slideWidth * viewportRatio.value
  }
  else {
    slideHeight = playerSize.value.height
    slideWidth = slideHeight / viewportRatio.value
  }

  return {
    width: slideWidth,
    height: slideHeight,
  }
})

const touchInfo = ref<{ x: number; y: number; } | null>(null)
const touchStartListener = (e: TouchEvent) => {
  touchInfo.value = {
    x: e.changedTouches[0].pageX,
    y: e.changedTouches[0].pageY,
  }
}
const touchEndListener = (e: TouchEvent) => {
  if (!touchInfo.value) return

  const offsetX = e.changedTouches[0].pageX - touchInfo.value.x
  const offsetY = e.changedTouches[0].pageY - touchInfo.value.y
  const offsetAbsX = Math.abs(offsetX)
  const offsetAbsY = Math.abs(offsetY)

  if ( offsetAbsX > offsetAbsY && offsetAbsX > 50 ) {
    if (offsetX < 0 && slideIndex.value > 0) slidesStore.updateSlideIndex(slideIndex.value - 1)
    if (offsetX > 0 && slideIndex.value < slides.value.length - 1) slidesStore.updateSlideIndex(slideIndex.value + 1)
  }

  if ( offsetAbsY > offsetAbsX && offsetAbsY > 50 ) {
    if (offsetY > 0 && slideIndex.value > 0) slidesStore.updateSlideIndex(slideIndex.value - 1)
    if (offsetY < 0 && slideIndex.value < slides.value.length - 1) slidesStore.updateSlideIndex(slideIndex.value + 1)
  }
}
</script>

<style lang="scss" scoped>
.mobile-player {
  transform-origin: 0 0;
  background-color: #1d1d1d;
  position: relative;
}
.screen-slide-list {
  position: relative;
  width: 100%;
  height: 100%;
}
.slide-item {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;

  &:not(.last, .next) {
    z-index: -1;
  }

  &.current {
    z-index: 2;
  }

  &.hide {
    opacity: 0;
  }

  &.turning-mode-no {
    &.before {
      transform: translateY(-100%);
    }
    &.after {
      transform: translateY(100%);
    }
  }
  &.turning-mode-fade {
    transition: opacity .75s;
    &.before {
      pointer-events: none;
      opacity: 0;
    }
    &.after {
      pointer-events: none;
      opacity: 0;
    }
  }
  &.turning-mode-slideX {
    transition: transform .35s;
    &.before {
      transform: translateX(-100%);
    }
    &.after {
      transform: translateX(100%);
    }
  }
  &.turning-mode-slideY {
    transition: transform .35s;
    &.before {
      transform: translateY(-100%);
    }
    &.after {
      transform: translateY(100%);
    }
  }
}
.slide-content {
  background-color: #fff;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  display: flex;
  justify-content: center;
  align-items: center;
}

.header {
  width: 100%;
  height: 40px;
  line-height: 40px;
  padding: 0 15px;
  position: absolute;
  top: 0;
  left: 0;
  z-index: 99;
  background-color: rgba($color: #1d1d1d, $alpha: .7);
  text-align: right;
  font-size: 13px;
  color: #fff;
  animation: slideInDown .15s;

  .back {
    height: 100%;
  }
}
.thumbnails {
  width: 100%;
  position: absolute;
  bottom: 0;
  left: 0;
  z-index: 99;
  background-color: rgba($color: #1d1d1d, $alpha: .7);
  overflow: auto !important;
  animation: slideInUp .15s;
}

@keyframes slideInUp {
  from {
    transform: translateY(100%);
  }
  to {
    transform: translateY(0);
  }
}
@keyframes slideInDown {
  from {
    transform: translateY(-100%);
  }
  to {
    transform: translateY(0);
  }
}
</style>
