// apps/web/src/features/editor/ElementPositionPanel.tsx
import { useTranslation } from 'react-i18next'

import AlignBottomIcon from '~icons/icon-park-outline/align-bottom'
import AlignHorizontallyIcon from '~icons/icon-park-outline/align-horizontally'
import AlignLeftIcon from '~icons/icon-park-outline/align-left'
import AlignRightIcon from '~icons/icon-park-outline/align-right'
import AlignTopIcon from '~icons/icon-park-outline/align-top'
import AlignVerticallyIcon from '~icons/icon-park-outline/align-vertically'
import BringToFrontIcon from '~icons/icon-park-outline/bring-to-front'
import BringToFrontOneIcon from '~icons/icon-park-outline/bring-to-front-one'
import LockIcon from '~icons/icon-park-outline/lock'
import RotateIcon from '~icons/icon-park-outline/rotate'
import SendToBackIcon from '~icons/icon-park-outline/send-to-back'
import SentToBackIcon from '~icons/icon-park-outline/sent-to-back'
import UnlockIcon from '~icons/icon-park-outline/unlock'
import { SHAPE_PATH_FORMULAS } from '@mona/presentation-core/shape-path-formulas'
import type { PresentationState } from '@mona/presentation-core'
import type { PPTElement } from '@mona/presentation-core/model'
import round from 'lodash/round'

import {
  InspectorButton,
  InspectorButtonGroup,
  InspectorNumberInput,
} from '@/features/editor/EditorInspectorPrimitives'
import {
  alignElementsToCanvasLikePptist,
  orderElementLikePptist,
  type ElementOrderCommand,
  type MultiAlignmentCommand,
} from '@/features/editor/editor-geometry'
import type { EditorRuntime } from '@/features/editor/editor-runtime'

const minSizeByType: Record<string, number> = {
  audio: 20,
  chart: 200,
  image: 20,
  latex: 20,
  shape: 20,
  table: 30,
  text: 40,
  video: 250,
}

export function ElementPositionPanel({
  activeElementIds,
  element,
  presentation,
  runtime,
}: {
  activeElementIds: string[]
  element: PPTElement
  presentation: PresentationState
  runtime: EditorRuntime
}) {
  const { t } = useTranslation()
  const slide = presentation.slides[presentation.slideIndex]!
  const historyKey = 'element-position-panel'
  const left = round(element.left, 1)
  const top = round(element.top, 1)
  const width = element.type === 'line' ? 0 : round(element.width, 1)
  const height = element.type === 'line' ? 0 : round(element.height, 1)
  const rotate = 'rotate' in element && element.rotate !== undefined ? round(element.rotate, 1) : 0
  const fixedRatio = 'fixedRatio' in element && Boolean(element.fixedRatio)
  const minSize = minSizeByType[element.type] || 20
  const isAutoHeightText = element.type === 'text' && !element.vertical && !element.fixedHeight
  const isAutoWidthText = element.type === 'text' && Boolean(element.vertical) && !element.fixedHeight
  const update = (props: Partial<PPTElement>) => runtime.commit('Update element position', [{
    type: 'element.update',
    payload: { id: element.id, props },
  }], { historyKey })

  const order = (command: ElementOrderCommand) => {
    const elements = orderElementLikePptist(slide.elements, element.id, command)
    if (!elements) return
    runtime.commit('Reorder element', [{ type: 'slide.update', props: { elements } }], { historyKey })
  }
  const align = (command: MultiAlignmentCommand) => {
    const elements = alignElementsToCanvasLikePptist({
      command,
      elements: slide.elements,
      selectedIds: new Set(activeElementIds),
      viewportHeight: presentation.viewportSize * presentation.viewportRatio,
      viewportWidth: presentation.viewportSize,
    })
    // Quirk retired: Vue's NumberInput watcher wrote the handle element's
    // coordinates back rounded to one decimal while other members kept full
    // precision. All aligned members now keep the calculation's precision.
    runtime.commit('Align element to canvas', [{ type: 'slide.update', props: { elements } }], { historyKey })
  }
  const resize = (nextWidth: number, nextHeight: number) => {
    let props: Partial<PPTElement> = { height: nextHeight, width: nextWidth }
    if (element.type === 'shape' && element.pathFormula) {
      const formula = SHAPE_PATH_FORMULAS[element.pathFormula]
      if (formula) {
        props = {
          ...props,
          path: formula.editable
            ? formula.formula(nextWidth, nextHeight, element.keypoints)
            : formula.formula(nextWidth, nextHeight),
          viewBox: [nextWidth, nextHeight],
        }
      }
    }
    update(props)
  }

  return (
    <div className="mona-element-position-panel">
      <div className="mona-position-title">{t('foundation.editor.position.layer')}</div>
      <InspectorButtonGroup className="mona-position-row">
        <InspectorButton ariaLabel={t('foundation.editor.position.bringFront')} onClick={() => order('top')} style={{ flex: 1 }}><SendToBackIcon /> {t('foundation.editor.position.bringFront')}</InspectorButton>
        <InspectorButton ariaLabel={t('foundation.editor.position.sendBack')} onClick={() => order('bottom')} style={{ flex: 1 }}><BringToFrontOneIcon /> {t('foundation.editor.position.sendBack')}</InspectorButton>
      </InspectorButtonGroup>
      <InspectorButtonGroup className="mona-position-row">
        <InspectorButton ariaLabel={t('foundation.editor.position.moveForward')} onClick={() => order('up')} style={{ flex: 1 }}><BringToFrontIcon /> {t('foundation.editor.position.moveForward')}</InspectorButton>
        <InspectorButton ariaLabel={t('foundation.editor.position.moveBackward')} onClick={() => order('down')} style={{ flex: 1 }}><SentToBackIcon /> {t('foundation.editor.position.moveBackward')}</InspectorButton>
      </InspectorButtonGroup>

      <div className="mona-panel-divider" />

      <div className="mona-position-title">{t('foundation.editor.position.alignment')}</div>
      <InspectorButtonGroup className="mona-position-row">
        <InspectorButton ariaLabel={t('foundation.editor.position.alignLeft')} onClick={() => align('left')} style={{ flex: 1 }}><AlignLeftIcon /></InspectorButton>
        <InspectorButton ariaLabel={t('foundation.editor.position.horizontalCenter')} onClick={() => align('horizontal')} style={{ flex: 1 }}><AlignVerticallyIcon /></InspectorButton>
        <InspectorButton ariaLabel={t('foundation.editor.position.alignRight')} onClick={() => align('right')} style={{ flex: 1 }}><AlignRightIcon /></InspectorButton>
      </InspectorButtonGroup>
      <InspectorButtonGroup className="mona-position-row">
        <InspectorButton ariaLabel={t('foundation.editor.position.alignTop')} onClick={() => align('top')} style={{ flex: 1 }}><AlignTopIcon /></InspectorButton>
        <InspectorButton ariaLabel={t('foundation.editor.position.verticalCenter')} onClick={() => align('vertical')} style={{ flex: 1 }}><AlignHorizontallyIcon /></InspectorButton>
        <InspectorButton ariaLabel={t('foundation.editor.position.alignBottom')} onClick={() => align('bottom')} style={{ flex: 1 }}><AlignBottomIcon /></InspectorButton>
      </InspectorButtonGroup>

      <div className="mona-panel-divider" />

      <div className="mona-position-row">
        <InspectorNumberInput ariaLabel={t('foundation.editor.position.x')} label={t('foundation.editor.position.x')} min={-1000} onChange={value => update({ left: value })} step={5} style={{ width: '45%' }} value={left} />
        <div style={{ width: '10%' }} />
        <InspectorNumberInput ariaLabel={t('foundation.editor.position.y')} label={t('foundation.editor.position.y')} min={-1000} onChange={value => update({ top: value })} step={5} style={{ width: '45%' }} value={top} />
      </div>

      {element.type !== 'line' ? (
        <div className="mona-position-row">
          <InspectorNumberInput
            ariaLabel={t('foundation.editor.position.width')}
            disabled={isAutoWidthText}
            label={t('foundation.editor.position.width')}
            max={1500}
            min={minSize}
            onChange={value => {
              if (isAutoWidthText) return
              let nextHeight = height
              if (fixedRatio) {
                const ratio = width / height
                nextHeight = value / ratio < minSize ? minSize : value / ratio
              }
              resize(value, nextHeight)
            }}
            step={5}
            style={{ width: '45%' }}
            value={width}
          />
          {['audio', 'image', 'shape'].includes(element.type) ? (
            <button
              aria-label={fixedRatio ? t('foundation.editor.position.unlockRatio') : t('foundation.editor.position.lockRatio')}
              aria-pressed={fixedRatio}
              className={`mona-position-icon-button${fixedRatio ? ' is-active' : ''}`}
              onClick={() => update({ fixedRatio: !fixedRatio } as Partial<PPTElement>)}
              style={{ width: '10%' }}
              type="button"
            >{fixedRatio ? <LockIcon /> : <UnlockIcon />}</button>
          ) : <div style={{ width: '10%' }} />}
          <InspectorNumberInput
            ariaLabel={t('foundation.editor.position.height')}
            disabled={isAutoHeightText || element.type === 'table'}
            label={t('foundation.editor.position.height')}
            max={800}
            min={minSize}
            onChange={value => {
              if (isAutoHeightText || element.type === 'table') return
              let nextWidth = width
              if (fixedRatio) {
                const ratio = width / height
                nextWidth = value * ratio < minSize ? minSize : value * ratio
              }
              resize(nextWidth, value)
            }}
            step={5}
            style={{ width: '45%' }}
            value={height}
          />
        </div>
      ) : null}

      {!['audio', 'line', 'video'].includes(element.type) ? (
        <>
          <div className="mona-panel-divider" />
          <div className="mona-position-row">
            <InspectorNumberInput ariaLabel={t('foundation.editor.position.rotation')} label={t('foundation.editor.position.rotation')} max={180} min={-180} onChange={value => update({ rotate: value } as Partial<PPTElement>)} step={5} style={{ width: '45%' }} value={rotate} />
            <div style={{ width: '7%' }} />
            <button aria-label={t('foundation.editor.position.rotateMinus')} className="mona-position-text-button" onClick={() => update({ rotate: Math.max(-180, Math.floor(rotate / 45) * 45 - 45) } as Partial<PPTElement>)} style={{ width: '24%' }} type="button"><RotateIcon /> -45°</button>
            <button aria-label={t('foundation.editor.position.rotatePlus')} className="mona-position-text-button" onClick={() => update({ rotate: Math.min(180, Math.floor(rotate / 45) * 45 + 45) } as Partial<PPTElement>)} style={{ width: '24%' }} type="button"><RotateIcon style={{ transform: 'rotateY(180deg)' }} /> +45°</button>
          </div>
        </>
      ) : null}
    </div>
  )
}

// src/views/Editor/Toolbar/ElementPositionPanel.vue
<template>
  <div class="element-positopn-panel">
    <div class="title">{{ $t('toolbar.layer') }}</div>
    <ButtonGroup class="row">
      <Button style="flex: 1;" @click="orderElement(handleElement!, ElementOrderCommands.TOP)"><i-icon-park-outline:send-to-back /> {{ $t('toolbar.bringFront') }}</Button>
      <Button style="flex: 1;" @click="orderElement(handleElement!, ElementOrderCommands.BOTTOM)"><i-icon-park-outline:bring-to-front-one /> {{ $t('toolbar.sendBack') }}</Button>
    </ButtonGroup>
    <ButtonGroup class="row">
      <Button style="flex: 1;" @click="orderElement(handleElement!, ElementOrderCommands.UP)"><i-icon-park-outline:BringToFront /> {{ $t('toolbar.moveForward') }}</Button>
      <Button style="flex: 1;" @click="orderElement(handleElement!, ElementOrderCommands.DOWN)"><i-icon-park-outline:SentToBack /> {{ $t('toolbar.moveBackward') }}</Button>
    </ButtonGroup>

    <Divider />
    
    <div class="title">{{ $t('toolbar.alignment') }}</div>
    <ButtonGroup class="row">
      <Button style="flex: 1;" v-tooltip="$t('common.leftAlign')" @click="alignElementToCanvas(ElementAlignCommands.LEFT)"><i-icon-park-outline:align-left /></Button>
      <Button style="flex: 1;" v-tooltip="$t('common.horizontalCenter')" @click="alignElementToCanvas(ElementAlignCommands.HORIZONTAL)"><i-icon-park-outline:align-vertically /></Button>
      <Button style="flex: 1;" v-tooltip="$t('common.rightAlign')" @click="alignElementToCanvas(ElementAlignCommands.RIGHT)"><i-icon-park-outline:align-right /></Button>
    </ButtonGroup>
    <ButtonGroup class="row">
      <Button style="flex: 1;" v-tooltip="$t('common.topAlign')" @click="alignElementToCanvas(ElementAlignCommands.TOP)"><i-icon-park-outline:align-top /></Button>
      <Button style="flex: 1;" v-tooltip="$t('common.verticalCenter')" @click="alignElementToCanvas(ElementAlignCommands.VERTICAL)"><i-icon-park-outline:align-horizontally /></Button>
      <Button style="flex: 1;" v-tooltip="$t('common.bottomAlign')" @click="alignElementToCanvas(ElementAlignCommands.BOTTOM)"><i-icon-park-outline:align-bottom /></Button>
    </ButtonGroup>

    <Divider />

    <div class="row">
      <NumberInput
        :min="-1000"
        :step="5"
        :value="left"
        @update:value="value => updateLeft(value)"
        style="width: 45%;"
      >
        <template #prefix>
          {{ $t('toolbar.x') }}
        </template>
      </NumberInput>
      <div style="width: 10%;"></div>
      <NumberInput
        :min="-1000"
        :step="5"
        :value="top"
        @update:value="value => updateTop(value)"
        style="width: 45%;"
      >
        <template #prefix>
          {{ $t('toolbar.y') }}
        </template>
      </NumberInput>
    </div>

    <template v-if="handleElement!.type !== 'line'">
      <div class="row">
        <NumberInput
          :min="minSize"
          :max="1500"
          :step="5"
          :disabled="isAutoWidthText"
          :value="width"
          @update:value="value => updateWidth(value)"
          style="width: 45%;"
        >
          <template #prefix>
            {{ $t('toolbar.width') }}
          </template>
        </NumberInput>
        <template v-if="['image', 'shape', 'audio'].includes(handleElement!.type)">
          <span style="width: 10%;" class="icon-btn" :class="{ 'active': fixedRatio }" v-tooltip="fixedRatio ? $t('toolbar.unlockAspectRatio') : $t('toolbar.lockAspectRatio')" @click="updateFixedRatio(!fixedRatio)">
            <i-icon-park-outline:lock v-if="fixedRatio" />
            <i-icon-park-outline:unlock v-else />
          </span>
        </template>
        <div style="width: 10%;" v-else></div>
        <NumberInput 
          :min="minSize"
          :max="800"
          :step="5"
          :disabled="isAutoHeightText || handleElement!.type === 'table'"
          :value="height" 
          @update:value="value => updateHeight(value)"
          style="width: 45%;"
        >
          <template #prefix>
            {{ $t('toolbar.height') }}
          </template>
        </NumberInput>
      </div>
    </template>

    <template v-if="!['line', 'video', 'audio'].includes(handleElement!.type)">
      <Divider />

      <div class="row">
        <NumberInput 
          :min="-180"
          :max="180"
          :step="5"
          :value="rotate" 
          @update:value="value => updateRotate(value)" 
          style="width: 45%;" 
        >
          <template #prefix>
            {{ $t('toolbar.rotation') }}
          </template>
        </NumberInput>
        <div style="width: 7%;"></div>
        <div class="text-btn" @click="updateRotate45('-')" style="width: 24%;"><i-icon-park-outline:rotate /> -45°</div>
        <div class="text-btn" @click="updateRotate45('+')"  style="width: 24%;"><i-icon-park-outline:rotate :style="{ transform: 'rotateY(180deg)' }" /> +45°</div>
      </div>
    </template>
  </div>
</template>

<script lang="ts" setup>
import { computed, ref, watch } from 'vue'
import { round } from 'lodash'
import { storeToRefs } from 'pinia'
import { useMainStore, useSlidesStore } from '@/store'
import type { PPTElement } from '@/types/slides'
import { ElementAlignCommands, ElementOrderCommands } from '@/types/edit'
import { MIN_SIZE } from '@/configs/element'
import { SHAPE_PATH_FORMULAS } from '@/configs/shapes'
import useOrderElement from '@/hooks/useOrderElement'
import useAlignElementToCanvas from '@/hooks/useAlignElementToCanvas'
import useHistorySnapshot from '@/hooks/useHistorySnapshot'
import Divider from '@/components/Divider.vue'
import Button from '@/components/Button.vue'
import ButtonGroup from '@/components/ButtonGroup.vue'
import NumberInput from '@/components/NumberInput.vue'

const slidesStore = useSlidesStore()
const { handleElement, handleElementId } = storeToRefs(useMainStore())

const left = ref(0)
const top = ref(0)
const width = ref(0)
const height = ref(0)
const rotate = ref(0)
const fixedRatio = ref(false)

const minSize = computed(() => {
  if (!handleElement.value) return 20
  return MIN_SIZE[handleElement.value.type] || 20
})

const isAutoHeightText = computed(() => {
  return handleElement.value?.type === 'text' && !handleElement.value.vertical && !handleElement.value.fixedHeight
})
const isAutoWidthText = computed(() => {
  return handleElement.value?.type === 'text' && handleElement.value.vertical && !handleElement.value.fixedHeight
})

watch(handleElement, () => {
  if (!handleElement.value) return

  left.value = round(handleElement.value.left, 1)
  top.value = round(handleElement.value.top, 1)

  fixedRatio.value = 'fixedRatio' in handleElement.value && !!handleElement.value.fixedRatio

  if (handleElement.value.type !== 'line') {
    width.value = round(handleElement.value.width, 1)
    height.value = round(handleElement.value.height, 1)
    rotate.value = 'rotate' in handleElement.value && handleElement.value.rotate !== undefined ? round(handleElement.value.rotate, 1) : 0
  }
}, { deep: true, immediate: true })

const { orderElement } = useOrderElement()
const { alignElementToCanvas } = useAlignElementToCanvas()

const { addHistorySnapshot } = useHistorySnapshot()

// 设置元素位置
const updateLeft = (value: number) => {
  const props = { left: value }
  slidesStore.updateElement({ id: handleElementId.value, props })
  addHistorySnapshot()
}
const updateTop = (value: number) => {
  const props = { top: value }
  slidesStore.updateElement({ id: handleElementId.value, props })
  addHistorySnapshot()
}

// 设置元素宽度、高度、旋转角度
// 对形状设置宽高时，需要检查是否需要更新形状路径
const updateShapePathData = (width: number, height: number) => {
  if (handleElement.value && handleElement.value.type === 'shape' && 'pathFormula' in handleElement.value && handleElement.value.pathFormula) {
    const pathFormula = SHAPE_PATH_FORMULAS[handleElement.value.pathFormula]

    let path = ''
    if ('editable' in pathFormula && pathFormula.editable) path = pathFormula.formula(width, height, handleElement.value.keypoints!)
    else path = pathFormula.formula(width, height)

    return {
      viewBox: [width, height],
      path,
    }
  }
  return null
}

const updateWidth = (value: number) => {
  if (!handleElement.value) return
  if (handleElement.value.type === 'line' || isAutoWidthText.value) return

  let h = height.value

  if (fixedRatio.value) {
    const ratio = width.value / height.value
    h = (value / ratio) < minSize.value ? minSize.value : (value / ratio)
  }
  let props: Partial<PPTElement> = { width: value, height: h }

  const shapePathData = updateShapePathData(value, h)
  if (shapePathData) {
    props = {
      width: value,
      height: h,
      ...shapePathData,
    }
  }

  slidesStore.updateElement({ id: handleElementId.value, props })
  addHistorySnapshot()
}

const updateHeight = (value: number) => {
  if (!handleElement.value) return
  if (handleElement.value.type === 'line' || handleElement.value.type === 'table' || isAutoHeightText.value) return

  let w = width.value

  if (fixedRatio.value) {
    const ratio = width.value / height.value
    w = (value * ratio) < minSize.value ? minSize.value : (value * ratio)
  }
  let props: Partial<PPTElement> = { width: w, height: value }

  const shapePathData = updateShapePathData(w, value)
  if (shapePathData) {
    props = {
      width: w,
      height: value,
      ...shapePathData,
    }
  }

  slidesStore.updateElement({ id: handleElementId.value, props })
  addHistorySnapshot()
}

const updateRotate = (value: number) => {
  const props = { rotate: value }
  slidesStore.updateElement({ id: handleElementId.value, props })
  addHistorySnapshot()
}

// 固定元素的宽高比
const updateFixedRatio = (value: boolean) => {
  const props = { fixedRatio: value }
  slidesStore.updateElement({ id: handleElementId.value, props })
  addHistorySnapshot()
}

// 将元素旋转45度（顺时针或逆时针）
const updateRotate45 = (command: '+' | '-') => {
  let _rotate = Math.floor(rotate.value / 45) * 45
  if (command === '+') _rotate = _rotate + 45
  else if (command === '-') _rotate = _rotate - 45

  if (_rotate < -180) _rotate = -180
  if (_rotate > 180) _rotate = 180

  const props = { rotate: _rotate }
  slidesStore.updateElement({ id: handleElementId.value, props })
  addHistorySnapshot()
}
</script>

<style lang="scss" scoped>
.row {
  width: 100%;
  display: flex;
  align-items: center;
  margin-bottom: 10px;
}
.title {
  margin-bottom: 10px;
}
.label {
  text-align: center;
}
.icon-btn {
  display: inline-block;
  text-align: center;
  cursor: pointer;

  &.active {
    color: $themeColor;
  }
}
.text-btn {
  height: 30px;
  line-height: 30px;
  text-align: center;
  cursor: pointer;

  &:hover {
    background-color: #efefef;
    border-radius: $borderRadius;
  }
}
</style>
