// apps/web/src/features/editor/ShapeStylePanel.tsx
import { useState, useSyncExternalStore } from 'react'
import { useTranslation } from 'react-i18next'

import AlignBottomIcon from '~icons/icon-park-outline/align-text-bottom-one'
import AlignMiddleIcon from '~icons/icon-park-outline/align-text-middle-one'
import AlignTopIcon from '~icons/icon-park-outline/align-text-top-one'
import DownIcon from '~icons/icon-park-outline/down'
import FormatBrushIcon from '~icons/icon-park-outline/format-brush'
import FullwidthIcon from '~icons/icon-park-outline/fullwidth'
import PlusIcon from '~icons/icon-park-outline/plus'
import RowHeightIcon from '~icons/icon-park-outline/row-height'
import VerticalSpacingIcon from '~icons/icon-park-outline/vertical-spacing-between-items'
import type { PresentationState, ShapePoolItem } from '@mona/presentation-core'
import { SHAPE_LIST, SHAPE_PATH_FORMULAS } from '@mona/presentation-core/shape-presets'
import type { Gradient, GradientType, PPTShapeElement, ShapeText, TextInset } from '@mona/presentation-core/model'

import { Button } from '@/components/ui/button'
import { EditorGradientBar } from '@/features/editor/EditorGradientBar'
import { InspectorButton, InspectorButtonGroup, InspectorColorButton, InspectorNumberInput, InspectorSelect, InspectorSlider, inspectorDividerClass, inspectorRowClass, inspectorSplitRowClass } from '@/features/editor/EditorInspectorPrimitives'
import {
  ElementFlipControls,
  ElementOpacityControl,
  ElementOutlineControls,
  ElementShadowControls,
  PropertyRow,
} from '@/features/editor/ElementStyleCommons'
import type { EditorRuntime } from '@/features/editor/editor-runtime'
import { editorLineHeightOptions, editorParagraphSpaceOptions, editorWordSpaceOptions } from '@/features/editor/editor-text-options'
import { RichTextBaseControls } from '@/features/editor/TextStylePanel'
import { PRESENTATION_FILTERS, pickFile } from '@/features/editor/editor-files'
import { fileToDataUrl } from '@/features/editor/editor-image'

type FillType = 'fill' | 'gradient' | 'pattern'

function ShapeThumbnail({ onSelect, shape }: { onSelect: () => void; shape: ShapePoolItem }) {
  return (
    <Button aria-label={shape.title || 'Shape preset'} className="relative aspect-square size-full cursor-pointer border-0 bg-transparent p-0 text-neutral-400 [&_svg]:absolute [&_svg]:top-1/2 [&_svg]:left-1/2 [&_svg]:-translate-x-1/2 [&_svg]:-translate-y-1/2 [&_svg]:overflow-visible hover:[&_path:not(.is-outlined)]:stroke-editor-selection hover:[&_path.is-outlined]:fill-editor-selection" onClick={onSelect} size="editor-icon" type="button" variant="ghost">
      <svg height="18" overflow="visible" width="18">
        <g transform={`scale(${18 / shape.viewBox[0]}, ${18 / shape.viewBox[1]}) translate(0,0) matrix(1,0,0,1,0,0)`}>
          <path
            className={shape.outlined ? 'is-outlined' : ''}
            d={shape.path}
            fill={shape.outlined ? '#999' : 'transparent'}
            stroke={shape.outlined ? 'transparent' : '#999'}
            strokeLinecap="butt"
            strokeMiterlimit="8"
            strokeWidth="2"
            vectorEffect="non-scaling-stroke"
          />
        </g>
      </svg>
    </Button>
  )
}

export function ShapeStylePanel({
  element,
  presentation,
  runtime,
}: {
  element: PPTShapeElement
  presentation: PresentationState
  runtime: EditorRuntime
}) {
  const { t } = useTranslation()
  const painter = useSyncExternalStore(runtime.shapeFormatPainter.subscribe, runtime.shapeFormatPainter.getSnapshot, runtime.shapeFormatPainter.getSnapshot)
  const [gradientSelection, setGradientSelection] = useState({ elementId: element.id, index: 0 })
  const gradientIndex = gradientSelection.elementId === element.id ? gradientSelection.index : 0
  const setGradientIndex = (index: number) => setGradientSelection({ elementId: element.id, index })
  const defaultGradient: Gradient = {
    type: 'linear',
    rotate: 0,
    colors: [{ pos: 0, color: element.fill || '#fff' }, { pos: 100, color: '#fff' }],
  }
  const gradient = element.gradient || defaultGradient
  const fillType: FillType = element.pattern !== undefined ? 'pattern' : element.gradient ? 'gradient' : 'fill'
  const inset: TextInset = element.text?.inset || [10, 10, 10, 10]
  const update = (props: Partial<PPTShapeElement>, historyKey = `shape-style-${element.id}`) => runtime.commit(
    'Update shape style',
    [{ type: 'element.update', payload: { id: element.id, props } }],
    { historyKey },
  )
  const remove = (property: string | string[], historyKey = `shape-style-${element.id}`) => runtime.commit(
    'Remove shape style',
    [{ type: 'element.properties.remove', payload: { id: element.id, property } }],
    { historyKey },
  )
  const updateGradient = (props: Partial<Gradient>) => update({ gradient: { ...gradient, ...props } })
  const updateText = (props: Partial<ShapeText>) => update({
    text: {
      content: '',
      defaultFontName: '',
      defaultColor: '#000',
      align: 'middle',
      ...element.text,
      ...props,
    },
  }, `shape-text-${element.id}`)
  const updateInset = (index: number, value: number) => {
    const next: TextInset = [...inset]
    next[index] = value
    updateText({ inset: next })
  }
  const changeFillType = (type: FillType) => {
    if (type === 'fill') remove(['gradient', 'pattern'])
    else if (type === 'gradient') {
      setGradientIndex(0)
      runtime.commit('Use gradient shape fill', [
        { type: 'element.properties.remove', payload: { id: element.id, property: 'pattern' } },
        { type: 'element.update', payload: { id: element.id, props: { gradient } } },
      ], { historyKey: `shape-style-${element.id}` })
    }
    else {
      runtime.commit('Use image shape fill', [
        { type: 'element.properties.remove', payload: { id: element.id, property: 'gradient' } },
        { type: 'element.update', payload: { id: element.id, props: { pattern: '' } } },
      ], { historyKey: `shape-style-${element.id}` })
    }
  }
  const changeShape = (shape: ShapePoolItem) => {
    const props: Partial<PPTShapeElement> = {
      viewBox: shape.viewBox,
      path: shape.path,
      special: shape.special,
    }
    if (shape.pathFormula) {
      props.pathFormula = shape.pathFormula
      props.viewBox = [element.width, element.height]
      const formula = SHAPE_PATH_FORMULAS[shape.pathFormula]
      if (formula.editable) {
        props.path = formula.formula(element.width, element.height, formula.defaultValue)
        props.keypoints = formula.defaultValue
      }
      else props.path = formula.formula(element.width, element.height)
    }
    else {
      props.pathFormula = undefined
      props.keypoints = undefined
    }
    update(props, `shape-replace-${element.id}`)
  }
  return (
    <div className="mona-shape-style-panel">
      <div className="mona-shape-panel-title"><span>{t('foundation.editor.shape.replace')}</span><DownIcon /></div>
      <div className="mona-shape-replace-pool">
        {SHAPE_LIST.map(category => (
          <div className="grid grid-cols-6 gap-[3.2%]" key={category.type}>
            {category.children.map((shape, index) => <ShapeThumbnail key={`${category.type}-${index}`} onSelect={() => changeShape(shape)} shape={shape} />)}
          </div>
        ))}
      </div>

      <div className="mona-shape-fill-row mb-2.5 flex w-full items-center gap-0">
        <div className="mona-shape-fill-control"><InspectorSelect<FillType> ariaLabel={t('foundation.editor.shape.fillType')} onChange={changeFillType} options={[
          { label: t('foundation.editor.shape.solidFill'), value: 'fill' },
          { label: t('foundation.editor.shape.gradientFill'), value: 'gradient' },
          { label: t('foundation.editor.shape.imageFill'), value: 'pattern' },
        ]} value={fillType} /></div>
        {fillType !== 'pattern' ? <div className="mona-shape-fill-spacer" /> : null}
        {fillType === 'fill' ? <div className="mona-shape-fill-control"><InspectorColorButton ariaLabel={t('foundation.editor.shape.fillColor')} color={element.fill || '#fff'} onChange={value => update({ fill: value })} /></div> : null}
        {fillType === 'gradient' ? <div className="mona-shape-fill-control"><InspectorSelect<GradientType> ariaLabel={t('foundation.editor.shape.gradientType')} onChange={value => updateGradient({ type: value })} options={[
          { label: t('foundation.editor.shape.linearGradient'), value: 'linear' },
          { label: t('foundation.editor.shape.radialGradient'), value: 'radial' },
        ]} value={gradient.type} /></div> : null}
      </div>
      {fillType === 'gradient' ? (
        <>
          <div className={inspectorRowClass}><EditorGradientBar index={Math.min(gradientIndex, gradient.colors.length - 1)} onChange={colors => updateGradient({ colors })} onIndexChange={setGradientIndex} value={gradient.colors} /></div>
          <PropertyRow label={t('foundation.editor.shape.currentStop')}><InspectorColorButton ariaLabel={t('foundation.editor.shape.currentStop')} color={gradient.colors[gradientIndex]?.color || gradient.colors[0]!.color} onChange={color => updateGradient({ colors: gradient.colors.map((stop, index) => index === gradientIndex ? { ...stop, color } : stop) })} /></PropertyRow>
          {gradient.type === 'linear' ? <PropertyRow label={t('foundation.editor.shape.gradientAngle')}><InspectorSlider ariaLabel={t('foundation.editor.shape.gradientAngle')} max={360} min={0} onChange={rotate => updateGradient({ rotate })} step={15} value={gradient.rotate} /></PropertyRow> : null}
        </>
      ) : null}
      {fillType === 'pattern' ? (
        <div className="mona-pattern-image-wrapper">
          <Button className="mona-pattern-image" onClick={() => {
            void pickFile(PRESENTATION_FILTERS.image, { title: t('foundation.editor.shape.uploadImage') })
              .then(async file => { if (file) update({ pattern: await fileToDataUrl(file) }) })
          }} size="editor" style={{ backgroundImage: `url(${element.pattern || ''})` }} type="button" variant="outline"><PlusIcon /></Button>
        </div>
      ) : null}

      <ElementFlipControls element={element} runtime={runtime} />
      <div className={inspectorDividerClass} />

      {element.text?.content ? (
        <>
          <RichTextBaseControls element={element} runtime={runtime} />
          <div className={inspectorDividerClass} />
          <PropertyRow label={t('foundation.editor.text.lineSpacing')}><InspectorSelect ariaLabel={t('foundation.editor.text.lineSpacing')} icon={<RowHeightIcon />} onChange={value => updateText({ lineHeight: value })} options={editorLineHeightOptions} value={element.text.lineHeight || 1.5} /></PropertyRow>
          <PropertyRow label={t('foundation.editor.text.paragraphSpacing')}><InspectorSelect ariaLabel={t('foundation.editor.text.paragraphSpacing')} icon={<VerticalSpacingIcon />} onChange={value => updateText({ paragraphSpace: value })} options={editorParagraphSpaceOptions} value={element.text.paragraphSpace === undefined ? 5 : element.text.paragraphSpace} /></PropertyRow>
          <PropertyRow label={t('foundation.editor.text.letterSpacing')}><InspectorSelect ariaLabel={t('foundation.editor.text.letterSpacing')} icon={<FullwidthIcon />} onChange={value => updateText({ wordSpace: value })} options={editorWordSpaceOptions} value={element.text.wordSpace || 0} /></PropertyRow>
          <div className={inspectorDividerClass} />
          <div className={`${inspectorSplitRowClass} is-insets`}><InspectorNumberInput ariaLabel={t('foundation.editor.text.marginTop')} label={t('foundation.editor.text.marginTop')} max={50} min={0} onChange={value => updateInset(0, value)} value={inset[0]} /><InspectorNumberInput ariaLabel={t('foundation.editor.text.marginBottom')} label={t('foundation.editor.text.marginBottom')} max={50} min={0} onChange={value => updateInset(2, value)} value={inset[2]} /></div>
          <div className={`${inspectorSplitRowClass} is-insets`}><InspectorNumberInput ariaLabel={t('foundation.editor.text.marginLeft')} label={t('foundation.editor.text.marginLeft')} max={50} min={0} onChange={value => updateInset(3, value)} value={inset[3]} /><InspectorNumberInput ariaLabel={t('foundation.editor.text.marginRight')} label={t('foundation.editor.text.marginRight')} max={50} min={0} onChange={value => updateInset(1, value)} value={inset[1]} /></div>
          <div className={inspectorDividerClass} />
          <InspectorButtonGroup className="flex w-full items-center mb-2.5">
            <InspectorButton active={(element.text.align || 'middle') === 'top'} ariaLabel={t('foundation.editor.text.alignTop')} onClick={() => updateText({ align: 'top' })} style={{ flex: 1 }}><AlignTopIcon /></InspectorButton>
            <InspectorButton active={(element.text.align || 'middle') === 'middle'} ariaLabel={t('foundation.editor.text.alignMiddle')} onClick={() => updateText({ align: 'middle' })} style={{ flex: 1 }}><AlignMiddleIcon /></InspectorButton>
            <InspectorButton active={(element.text.align || 'middle') === 'bottom'} ariaLabel={t('foundation.editor.text.alignBottom')} onClick={() => updateText({ align: 'bottom' })} style={{ flex: 1 }}><AlignBottomIcon /></InspectorButton>
          </InspectorButtonGroup>
          <div className={inspectorDividerClass} />
        </>
      ) : null}

      <ElementOutlineControls element={element} presentation={presentation} runtime={runtime} />
      <div className={inspectorDividerClass} />
      <ElementShadowControls element={element} presentation={presentation} runtime={runtime} />
      <div className={inspectorDividerClass} />
      <ElementOpacityControl element={element} runtime={runtime} />
      <div className={inspectorDividerClass} />
      <InspectorButton active={Boolean(painter)} ariaLabel={t('foundation.editor.shape.formatPainter')} onClick={() => runtime.shapeFormatPainter.toggle(element)} onDoubleClick={() => runtime.shapeFormatPainter.toggle(element, true)} style={{ width: '100%' }}><FormatBrushIcon /> {t('foundation.editor.shape.formatPainter')}</InspectorButton>
    </div>
  )
}

// src/views/Editor/Toolbar/ElementStylePanel/ShapeStylePanel.vue
<template>
  <div class="shape-style-panel">
    <div class="title">
      <span>{{ $t('toolbar.replaceShape') }}</span>
      <i-icon-park-outline:down />
    </div>
    <div class="shape-pool">
      <div class="category" v-for="item in SHAPE_LIST" :key="item.type">
        <div class="shape-list">
          <ShapeItemThumbnail 
            class="shape-item"
            v-for="(shape, index) in item.children"
            :key="index"
            :shape="shape"
            @click="changeShape(shape)"
          />
        </div>
      </div>
    </div>

    <div class="row">
      <Select 
        style="flex: 1;" 
        :value="fillType" 
        @update:value="value => updateFillType(value as 'fill' | 'gradient' | 'pattern')"
        :options="[
          { label: $t('toolbar.solidFill'), value: 'fill' },
          { label: $t('toolbar.gradientFill'), value: 'gradient' },
          { label: $t('toolbar.imageFill'), value: 'pattern' },
        ]"
      />
      <div style="width: 10px;" v-if="fillType !== 'pattern'"></div>
      <Popover trigger="click" v-if="fillType === 'fill'" style="flex: 1;">
        <template #content>
          <ColorPicker
            :modelValue="fill"
            @update:modelValue="value => updateFill(value)"
          />
        </template>
        <ColorButton :color="fill" />
      </Popover>
      <Select 
        style="flex: 1;" 
        :value="gradient.type" 
        @update:value="value => updateGradient({ type: value as GradientType })"
        v-else-if="fillType === 'gradient'"
        :options="[
          { label: $t('toolbar.linearGradient'), value: 'linear' },
          { label: $t('toolbar.radialGradient'), value: 'radial' },
        ]"
      />
    </div>
    
    <template v-if="fillType === 'gradient'">
      <div class="row">
        <GradientBar
          :value="gradient.colors"
          :index="currentGradientIndex"
          @update:value="value => updateGradient({ colors: value })"
          @update:index="index => currentGradientIndex = index"
        />
      </div>
      <div class="row">
        <div style="width: 40%;">{{ $t('toolbar.currentStop') }}</div>
        <Popover trigger="click" style="width: 60%;">
          <template #content>
            <ColorPicker
              :modelValue="gradient.colors[currentGradientIndex].color"
              @update:modelValue="value => updateGradientColors(value)"
            />
          </template>
          <ColorButton :color="gradient.colors[currentGradientIndex].color" />
        </Popover>
      </div>
      <div class="row" v-if="gradient.type === 'linear'">
        <div style="width: 40%;">{{ $t('toolbar.gradientAngle') }}</div>
        <Slider
          style="width: 60%;"
          :min="0"
          :max="360"
          :step="15"
          :value="gradient.rotate"
          @update:value="value => updateGradient({ rotate: value as number })" 
        />
      </div>
    </template>
    
    <template v-if="fillType === 'pattern'">
      <div class="pattern-image-wrapper">
        <FileInput @change="files => uploadPattern(files)">
          <div class="pattern-image">
            <div class="content" :style="{ backgroundImage: `url(${pattern})` }">
              <i-icon-park-outline:plus />
            </div>
          </div>
        </FileInput>
      </div>
    </template>

    <ElementFlip />

    <Divider />

    <template v-if="handleShapeElement.text?.content">
      <RichTextBase />
      <Divider />

      <div class="row">
        <div style="width: 40%;">{{ $t('toolbar.lineSpacing') }}</div>
        <Select style="width: 60%;"
          :value="lineHeight || 1"
          @update:value="value => updateTextProps({ lineHeight: value as number })"
          :options="lineHeightOptions.map(item => ({
            label: $t('toolbar.times', { value: item }), value: item
          }))"
        >
          <template #icon>
            <i-icon-park-outline:row-height />
          </template>
        </Select>
      </div>
      <div class="row">
        <div style="width: 40%;">{{ $t('toolbar.paragraphSpacing') }}</div>
        <Select style="width: 60%;"
          :value="paragraphSpace || 0"
          @update:value="value => updateTextProps({ paragraphSpace: value as number })"
          :options="paragraphSpaceOptions.map(item => ({
            label: item + 'px', value: item
          }))"
        >
          <template #icon>
            <i-icon-park-outline:vertical-spacing-between-items />
          </template>
        </Select>
      </div>
      <div class="row">
        <div style="width: 40%;">{{ $t('toolbar.letterSpacing') }}</div>
        <Select style="width: 60%;"
          :value="wordSpace || 0"
          @update:value="value => updateTextProps({ wordSpace: value as number })"
          :options="wordSpaceOptions.map(item => ({
            label: item + 'px', value: item
          }))"
        >
          <template #icon>
            <i-icon-park-outline:fullwidth />
          </template>
        </Select>
      </div>

      <Divider />

      <div class="row">
        <NumberInput
          :min="0"
          :max="50"
          :value="inset[0]"
          @update:value="value => updateInset(0, value)"
          style="width: 45%;"
        >
          <template #prefix>{{ $t('toolbar.marginTop') }}</template>
        </NumberInput>
        <div style="width: 10%;"></div>
        <NumberInput
          :min="0"
          :max="50"
          :value="inset[2]"
          @update:value="value => updateInset(2, value)"
          style="width: 45%;"
        >
          <template #prefix>{{ $t('toolbar.marginBottom') }}</template>
        </NumberInput>
      </div>
      <div class="row">
        <NumberInput
          :min="0"
          :max="50"
          :value="inset[3]"
          @update:value="value => updateInset(3, value)"
          style="width: 45%;"
        >
          <template #prefix>{{ $t('toolbar.marginLeft') }}</template>
        </NumberInput>
        <div style="width: 10%;"></div>
        <NumberInput
          :min="0"
          :max="50"
          :value="inset[1]"
          @update:value="value => updateInset(1, value)"
          style="width: 45%;"
        >
          <template #prefix>{{ $t('toolbar.marginRight') }}</template>
        </NumberInput>
      </div>

      <Divider />

      <RadioGroup 
        class="row" 
        button-style="solid" 
        :value="textAlign"
        @update:value="value => updateTextProps({ align: value as 'top' | 'middle' | 'bottom' })"
      >
        <RadioButton value="top" v-tooltip="$t('common.topAlign')" style="flex: 1;"><i-icon-park-outline:align-text-top-one /></RadioButton>
        <RadioButton value="middle" v-tooltip="$t('common.verticalCenter')" style="flex: 1;"><i-icon-park-outline:align-text-middle-one /></RadioButton>
        <RadioButton value="bottom" v-tooltip="$t('common.bottomAlign')" style="flex: 1;"><i-icon-park-outline:align-text-bottom-one /></RadioButton>
      </RadioGroup>

      <Divider />
    </template>

    <ElementOutline />
    <Divider />
    <ElementShadow />
    <Divider />
    <ElementOpacity />
    <Divider />

    <div class="row">
      <CheckboxButton
        v-tooltip="$t('toolbar.doubleClickContinuous')"
        style="flex: 1;"
        :checked="!!shapeFormatPainter"
        @click="toggleShapeFormatPainter()"
        @dblclick="toggleShapeFormatPainter(true)"
      ><i-icon-park-outline:format-brush /> {{ $t('toolbar.shapeFormatPainter') }}</CheckboxButton>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { type Ref, ref, watch } from 'vue'
import { storeToRefs } from 'pinia'
import { useMainStore, useSlidesStore } from '@/store'
import type { GradientType, PPTShapeElement, Gradient, ShapeText, TextInset } from '@/types/slides'
import { type ShapePoolItem, SHAPE_LIST, SHAPE_PATH_FORMULAS } from '@/configs/shapes'
import { getImageDataURL } from '@/utils/image'
import emitter, { EmitterEvents } from '@/utils/emitter'
import useHistorySnapshot from '@/hooks/useHistorySnapshot'
import useShapeFormatPainter from '@/hooks/useShapeFormatPainter'

import ElementOpacity from '../common/ElementOpacity.vue'
import ElementOutline from '../common/ElementOutline.vue'
import ElementShadow from '../common/ElementShadow.vue'
import ElementFlip from '../common/ElementFlip.vue'
import RichTextBase from '../common/RichTextBase.vue'
import ShapeItemThumbnail from '@/views/Editor/CanvasTool/ShapeItemThumbnail.vue'
import ColorButton from '@/components/ColorButton.vue'
import CheckboxButton from '@/components/CheckboxButton.vue'
import ColorPicker from '@/components/ColorPicker/index.vue'
import Divider from '@/components/Divider.vue'
import NumberInput from '@/components/NumberInput.vue'
import Slider from '@/components/Slider.vue'
import RadioButton from '@/components/RadioButton.vue'
import RadioGroup from '@/components/RadioGroup.vue'
import Select from '@/components/Select.vue'
import Popover from '@/components/Popover.vue'
import GradientBar from '@/components/GradientBar.vue'
import FileInput from '@/components/FileInput.vue'

const mainStore = useMainStore()
const slidesStore = useSlidesStore()
const { handleElement, handleElementId, shapeFormatPainter } = storeToRefs(mainStore)

const handleShapeElement = handleElement as Ref<PPTShapeElement>

const fill = ref<string>('#000')
const pattern = ref<string>('')
const gradient = ref<Gradient>({
  type: 'linear', 
  rotate: 0,
  colors: [
    { pos: 0, color: '#fff' },
    { pos: 100, color: '#fff' },
  ],
})
const fillType = ref('fill')
const textAlign = ref('middle')
const lineHeight = ref<number>()
const wordSpace = ref<number>()
const paragraphSpace = ref<number>()
const inset = ref<TextInset>([10, 10, 10, 10])
const currentGradientIndex = ref(0)
const lineHeightOptions = [0.9, 1.0, 1.15, 1.2, 1.4, 1.5, 1.8, 2.0, 2.5, 3.0]
const wordSpaceOptions = [0, 1, 2, 3, 4, 5, 6, 8, 10]
const paragraphSpaceOptions = [0, 5, 10, 15, 20, 25, 30, 40, 50, 80]

watch(handleElement, () => {
  if (!handleElement.value || handleElement.value.type !== 'shape') return

  fill.value = handleElement.value.fill || '#fff'
  const defaultGradientColor = [
    { pos: 0, color: fill.value },
    { pos: 100, color: '#fff' },
  ]
  gradient.value = handleElement.value.gradient || { type: 'linear', rotate: 0, colors: defaultGradientColor }
  pattern.value = handleElement.value.pattern || ''
  fillType.value = (handleElement.value.pattern !== undefined) ? 'pattern' : (handleElement.value.gradient ? 'gradient' : 'fill')
  textAlign.value = handleElement.value?.text?.align || 'middle'
  lineHeight.value = handleElement.value?.text?.lineHeight || 1.5
  wordSpace.value = handleElement.value?.text?.wordSpace || 0
  paragraphSpace.value = handleElement.value?.text?.paragraphSpace === undefined ? 5 : handleElement.value?.text?.paragraphSpace
  inset.value = handleElement.value?.text?.inset || [10, 10, 10, 10]

  if (handleElement.value.text?.content) {
    emitter.emit(EmitterEvents.SYNC_RICH_TEXT_ATTRS_TO_STORE)
  }
}, { deep: true, immediate: true })

watch(handleElementId, () => {
  currentGradientIndex.value = 0
})

const { addHistorySnapshot } = useHistorySnapshot()
const { toggleShapeFormatPainter } = useShapeFormatPainter()

const updateElement = (props: Partial<PPTShapeElement>) => {
  slidesStore.updateElement({ id: handleElementId.value, props })
  addHistorySnapshot()
}

// 设置填充类型：渐变、纯色
const updateFillType = (type: 'gradient' | 'fill' | 'pattern') => {
  if (type === 'fill') {
    slidesStore.removeElementProps({ id: handleElementId.value, propName: ['gradient', 'pattern'] })
    addHistorySnapshot()
  }
  else if (type === 'gradient') {
    currentGradientIndex.value = 0
    slidesStore.removeElementProps({ id: handleElementId.value, propName: 'pattern' })
    updateElement({ gradient: gradient.value })
  }
  else if (type === 'pattern') {
    slidesStore.removeElementProps({ id: handleElementId.value, propName: 'gradient' })
    updateElement({ pattern: '' })
  }
}

// 设置渐变填充
const updateGradient = (gradientProps: Partial<Gradient>) => {
  if (!gradient.value) return
  const _gradient = { ...gradient.value, ...gradientProps }
  updateElement({ gradient: _gradient })
}
const updateGradientColors = (color: string) => {
  const colors = gradient.value.colors.map((item, index) => {
    if (index === currentGradientIndex.value) return { ...item, color }
    return item
  })
  updateGradient({ colors })
}

// 上传填充图片
const uploadPattern = (files: FileList) => {
  const imageFile = files[0]
  if (!imageFile) return
  getImageDataURL(imageFile).then(dataURL => {
    pattern.value = dataURL
    updateElement({ pattern: dataURL })
  })
}

// 设置填充色
const updateFill = (value: string) => {
  updateElement({ fill: value })
}

// 修改形状
const changeShape = (shape: ShapePoolItem) => {
  const { width, height } = handleElement.value as PPTShapeElement
  const props: Partial<PPTShapeElement> = {
    viewBox: shape.viewBox,
    path: shape.path,
    special: shape.special,
  }
  if (shape.pathFormula) {
    props.pathFormula = shape.pathFormula
    props.viewBox = [width, height]

    const pathFormula = SHAPE_PATH_FORMULAS[shape.pathFormula]
    if ('editable' in pathFormula) {
      props.path = pathFormula.formula(width, height, pathFormula.defaultValue)
      props.keypoints = pathFormula.defaultValue
    }
    else props.path = pathFormula.formula(width, height)
  }
  else {
    props.pathFormula = undefined
    props.keypoints = undefined
  }
  updateElement(props)
}

const updateTextProps = (props: Partial<ShapeText>) => {
  const _handleElement = handleElement.value as PPTShapeElement
  const defaultText: ShapeText = {
    content: '',
    defaultFontName: '',
    defaultColor: '#000',
    align: 'middle',
  }
  const _text = _handleElement.text || defaultText
  updateElement({ text: { ..._text, ...props } })
}

const updateInset = (index: number, value: number) => {
  const _inset: TextInset = [...inset.value]
  _inset[index] = value
  updateTextProps({ inset: _inset })
}
</script>

<style lang="scss" scoped>
.shape-style-panel {
  user-select: none;
}
.row {
  width: 100%;
  display: flex;
  align-items: center;
  margin-bottom: 10px;
}
.font-size-btn {
  padding: 0;
}
.title {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 10px;
}
.shape-pool {
  width: 235px;
  height: 150px;
  overflow: auto;
  padding: 5px;
  padding-right: 10px;
  border: 1px solid $borderColor;
  margin-bottom: 20px;
}
.shape-list {
  @include flex-grid-layout();
}
.shape-item {
  @include flex-grid-layout-children(6, 14%);

  height: 0;
  padding-bottom: 14%;
  flex-shrink: 0;
}

.pattern-image-wrapper {
  margin-bottom: 10px;
}
.pattern-image {
  height: 0;
  padding-bottom: 56.25%;
  border: 1px dashed $borderColor;
  border-radius: $borderRadius;
  position: relative;
  transition: all $transitionDelay;

  &:hover {
    border-color: $themeColor;
    color: $themeColor;
  }

  .content {
    @include absolute-0();

    display: flex;
    justify-content: center;
    align-items: center;
    background-position: center;
    background-size: contain;
    background-repeat: no-repeat;
    cursor: pointer;
  }
}
</style>
