// apps/web/src/features/editor/TableStylePanel.tsx
import { useTranslation } from 'react-i18next'

import AddTextIcon from '~icons/icon-park-outline/add-text'
import AlignBothIcon from '~icons/icon-park-outline/align-text-both'
import AlignBottomIcon from '~icons/icon-park-outline/align-text-bottom-one'
import AlignCenterIcon from '~icons/icon-park-outline/align-text-center'
import AlignLeftIcon from '~icons/icon-park-outline/align-text-left'
import AlignMiddleIcon from '~icons/icon-park-outline/align-text-middle-one'
import AlignRightIcon from '~icons/icon-park-outline/align-text-right'
import AlignTopIcon from '~icons/icon-park-outline/align-text-top-one'
import DownIcon from '~icons/icon-park-outline/down'
import FillIcon from '~icons/icon-park-outline/fill'
import FontSizeIcon from '~icons/icon-park-outline/font-size'
import StrikethroughIcon from '~icons/icon-park-outline/strikethrough'
import TextIcon from '~icons/icon-park-outline/text'
import TextBoldIcon from '~icons/icon-park-outline/text-bold'
import TextItalicIcon from '~icons/icon-park-outline/text-italic'
import TextUnderlineIcon from '~icons/icon-park-outline/text-underline'
import type { PresentationState } from '@mona/presentation-core'
import type { PPTTableElement, TableCellStyle, TableTheme, TextAlign, TextAlignVertical } from '@mona/presentation-core/model'

import { Button } from '@/components/ui/button'
import { tableCommandMenu } from '@/features/editor/contextual/contextual-control-styles'
import {
  InspectorButton,
  InspectorButtonGroup,
  InspectorCheckbox,
  InspectorColorButton,
  InspectorPopoverButton,
  InspectorSelect,
  InspectorSwitch,
  inspectorDividerClass,
  inspectorRowClass,
  inspectorSelectGroupClass,
} from '@/features/editor/EditorInspectorPrimitives'
import { ElementOutlineControls, PropertyRow } from '@/features/editor/ElementStyleCommons'
import { editorFontOptions, editorFontSizeOptions } from '@/features/editor/editor-text-options'
import { executeTableCommand, parseTableCellKey, updateTableCellStyles, type TableCommand, type TableCommandPosition } from '@/features/editor/editor-table'
import type { EditorRuntime } from '@/features/editor/editor-runtime'
import { useEditorApplication } from '@/features/editor/services/editor-application'

const fontSizeOptions = editorFontSizeOptions.slice(0, 9)

export function TableStylePanel({
  element,
  presentation,
  runtime,
  selectedCells,
}: {
  element: PPTTableElement
  presentation: PresentationState
  runtime: EditorRuntime
  selectedCells: readonly string[]
}) {
  const { t } = useTranslation()
  const { notifications } = useEditorApplication()
  const [row, column] = selectedCells.length ? parseTableCellKey(selectedCells[0]!) : [0, 0]
  const style = element.data[row]?.[column]?.style ?? {}
  const attrs = {
    bold: !!style.bold,
    em: !!style.em,
    underline: !!style.underline,
    strikethrough: !!style.strikethrough,
    color: style.color || '#000',
    backcolor: style.backcolor || '',
    fontsize: style.fontsize || '12px',
    fontname: style.fontname || '',
    align: style.align || 'left',
    vAlign: style.vAlign || 'top',
  } satisfies Required<TableCellStyle>
  const commit = (props: Partial<PPTTableElement>, label = 'Update table style') => runtime.commit(label, [{ type: 'element.update', payload: { id: element.id, props } }], { historyKey: `table-style-${element.id}` })
  const updateText = (props: Partial<TableCellStyle>) => commit({ data: updateTableCellStyles(element, selectedCells, props) })
  const command = (name: TableCommand, position?: TableCommandPosition) => {
    const next = executeTableCommand(element, selectedCells, name, position)
    if (next === element) {
      if (name === 'delete-row' || name === 'delete-col') {
        notifications.notify({
          text: t(`foundation.editor.tableEditing.${name === 'delete-row' ? 'keepOneRow' : 'keepOneColumn'}`),
          type: 'warning',
        })
      }
      return
    }
    commit({ data: next.data, width: next.width, colWidths: next.colWidths }, 'Edit table structure')
  }
  const updateTheme = (props: Partial<TableTheme>) => {
    if (element.theme) commit({ theme: { ...element.theme, ...props } })
  }
  return (
    <div className="mona-table-style-panel">
      <div className={`${inspectorSelectGroupClass} ${inspectorRowClass}`}>
        <InspectorSelect ariaLabel={t('foundation.editor.text.fontFamily')} icon={<FontSizeIcon />} onChange={fontname => updateText({ fontname })} options={[{ label: t('common.defaultFont'), value: '' }, ...editorFontOptions]} search searchLabel={t('foundation.editor.text.fontSearch')} style={{ width: '50%' }} value={attrs.fontname} />
        <InspectorSelect ariaLabel={t('foundation.editor.text.fontSize')} icon={<AddTextIcon />} onChange={fontsize => updateText({ fontsize })} options={fontSizeOptions} search searchLabel={t('foundation.editor.text.fontSizeSearch')} style={{ width: '50%' }} value={attrs.fontsize} />
      </div>
      <InspectorButtonGroup className={`${inspectorRowClass} mona-table-color-row`}>
        <InspectorColorButton ariaLabel={t('foundation.editor.table.textColor')} color={attrs.color} icon={<TextIcon />} onChange={color => updateText({ color })} style={{ width: '50%' }} />
        <InspectorColorButton ariaLabel={t('foundation.editor.table.cellFill')} color={attrs.backcolor} icon={<FillIcon />} onChange={backcolor => updateText({ backcolor })} style={{ width: '50%' }} />
      </InspectorButtonGroup>
      <InspectorButtonGroup className="flex w-full items-center mb-2.5">
        <InspectorButton active={attrs.bold} ariaLabel={t('foundation.editor.text.bold')} onClick={() => updateText({ bold: !attrs.bold })} style={{ flex: 1 }}><TextBoldIcon /></InspectorButton>
        <InspectorButton active={attrs.em} ariaLabel={t('foundation.editor.text.italic')} onClick={() => updateText({ em: !attrs.em })} style={{ flex: 1 }}><TextItalicIcon /></InspectorButton>
        <InspectorButton active={attrs.underline} ariaLabel={t('foundation.editor.text.underline')} onClick={() => updateText({ underline: !attrs.underline })} style={{ flex: 1 }}><TextUnderlineIcon /></InspectorButton>
        <InspectorButton active={attrs.strikethrough} ariaLabel={t('foundation.editor.text.strikethrough')} onClick={() => updateText({ strikethrough: !attrs.strikethrough })} style={{ flex: 1 }}><StrikethroughIcon /></InspectorButton>
      </InspectorButtonGroup>
      <InspectorButtonGroup className="flex w-full items-center mb-2.5">
        {([
          ['left', AlignLeftIcon, 'alignLeft'],
          ['center', AlignCenterIcon, 'alignCenter'],
          ['right', AlignRightIcon, 'alignRight'],
          ['justify', AlignBothIcon, 'justify'],
        ] as const).map(([value, Icon, label]) => <InspectorButton active={attrs.align === value} ariaLabel={t(`foundation.editor.table.${label}`)} key={value} onClick={() => updateText({ align: value as TextAlign })} style={{ flex: 1 }}><Icon /></InspectorButton>)}
      </InspectorButtonGroup>
      <InspectorButtonGroup className="flex w-full items-center mb-2.5">
        {([
          ['top', AlignTopIcon, 'alignTop'],
          ['middle', AlignMiddleIcon, 'alignMiddle'],
          ['bottom', AlignBottomIcon, 'alignBottom'],
        ] as const).map(([value, Icon, label]) => <InspectorButton active={attrs.vAlign === value} ariaLabel={t(`foundation.editor.table.${label}`)} key={value} onClick={() => updateText({ vAlign: value as TextAlignVertical })} style={{ flex: 1 }}><Icon /></InspectorButton>)}
      </InspectorButtonGroup>
      <div className={inspectorDividerClass} />
      <ElementOutlineControls element={element} fixed presentation={presentation} runtime={runtime} />
      <div className={inspectorDividerClass} />
      <PropertyRow label={t('foundation.editor.tableStyle.rowActions')}>
        <InspectorButtonGroup>
          <InspectorButton ariaLabel={t('foundation.editor.tableStyle.addRow')} onClick={() => command('insert-row', 'after')} style={{ flex: 1 }}>{t('foundation.editor.tableStyle.addRow')}</InspectorButton>
          <InspectorPopoverButton ariaLabel={t('foundation.editor.tableStyle.rowActions')} className="mona-table-action-menu-trigger" content={<div className={tableCommandMenu}>
            <Button onClick={() => command('insert-row', 'before')} size="editor" type="button" variant="ghost">{t('foundation.editor.tableStyle.addAbove')}</Button>
            <Button onClick={() => command('insert-row', 'after')} size="editor" type="button" variant="ghost">{t('foundation.editor.tableStyle.addBelow')}</Button>
            <Button onClick={() => command('delete-row')} size="editor" type="button" variant="ghost">{t('foundation.editor.table.deleteRow')}</Button>
          </div>}><DownIcon /></InspectorPopoverButton>
        </InspectorButtonGroup>
      </PropertyRow>
      <PropertyRow label={t('foundation.editor.tableStyle.columnActions')}>
        <InspectorButtonGroup>
          <InspectorButton ariaLabel={t('foundation.editor.tableStyle.addColumn')} onClick={() => command('insert-col', 'after')} style={{ flex: 1 }}>{t('foundation.editor.tableStyle.addColumn')}</InspectorButton>
          <InspectorPopoverButton ariaLabel={t('foundation.editor.tableStyle.columnActions')} className="mona-table-action-menu-trigger" content={<div className={tableCommandMenu}>
            <Button onClick={() => command('insert-col', 'before')} size="editor" type="button" variant="ghost">{t('foundation.editor.tableStyle.addLeft')}</Button>
            <Button onClick={() => command('insert-col', 'after')} size="editor" type="button" variant="ghost">{t('foundation.editor.tableStyle.addRight')}</Button>
            <Button onClick={() => command('delete-col')} size="editor" type="button" variant="ghost">{t('foundation.editor.table.deleteColumn')}</Button>
          </div>}><DownIcon /></InspectorPopoverButton>
        </InspectorButtonGroup>
      </PropertyRow>
      <div className={inspectorDividerClass} />
      <PropertyRow label={t('foundation.editor.tableStyle.enableTheme')}>
        <div className="w-full text-right"><InspectorSwitch ariaLabel={t('foundation.editor.tableStyle.enableTheme')} checked={!!element.theme} onChange={checked => checked
          ? commit({ theme: { color: presentation.theme.themeColors[0]!, rowHeader: true, rowFooter: false, colHeader: false, colFooter: false } })
          : runtime.commit('Disable table theme', [{ type: 'element.properties.remove', payload: { id: element.id, property: 'theme' } }], { historyKey: `table-style-${element.id}` })} /></div>
      </PropertyRow>
      {element.theme ? <>
        <div className="mona-table-theme-options">
          <InspectorCheckbox className="mona-panel-checkbox" checked={element.theme.rowHeader} onChange={rowHeader => updateTheme({ rowHeader })}>{t('foundation.editor.tableStyle.headerRow')}</InspectorCheckbox>
          <InspectorCheckbox className="mona-panel-checkbox" checked={element.theme.rowFooter} onChange={rowFooter => updateTheme({ rowFooter })}>{t('foundation.editor.tableStyle.totalRow')}</InspectorCheckbox>
        </div>
        <div className="mona-table-theme-options">
          <InspectorCheckbox className="mona-panel-checkbox" checked={element.theme.colHeader} onChange={colHeader => updateTheme({ colHeader })}>{t('foundation.editor.tableStyle.firstColumn')}</InspectorCheckbox>
          <InspectorCheckbox className="mona-panel-checkbox" checked={element.theme.colFooter} onChange={colFooter => updateTheme({ colFooter })}>{t('foundation.editor.tableStyle.lastColumn')}</InspectorCheckbox>
        </div>
        <PropertyRow label={t('foundation.editor.tableStyle.themeColor')}><InspectorColorButton ariaLabel={t('foundation.editor.tableStyle.themeColor')} color={element.theme.color} onChange={color => updateTheme({ color })} /></PropertyRow>
      </> : null}
    </div>
  )
}

// src/views/Editor/Toolbar/ElementStylePanel/TableStylePanel.vue
<template>
  <div class="table-style-panel">
    <SelectGroup class="row">
      <Select
        style="width: 50%;"
        :value="textAttrs.fontname"
        search
        :searchLabel="$t('canvas.fontSearch')"
        autofocus
        @update:value="value => updateTextAttrs({ fontname: value as string })"
        :options="fontOptions"
      >
        <template #icon>
          <i-icon-park-outline:font-size />
        </template>
      </Select>
      <Select
        style="width: 50%;"
        :value="textAttrs.fontsize"
        search
        :searchLabel="$t('canvas.fontSizeSearch')"
        autofocus
        @update:value="value => updateTextAttrs({ fontsize: value as string })"
        :options="fontSizeOptions.map(item => ({
          label: item, value: item
        }))"
      >
        <template #icon>
          <i-icon-park-outline:add-text />
        </template>
      </Select>
    </SelectGroup>

    <ButtonGroup class="row" passive>
      <Popover trigger="click" style="width: 50%;">
        <template #content>
          <ColorPicker
            :modelValue="textAttrs.color"
            @update:modelValue="value => updateTextAttrs({ color: value })"
          />
        </template>
        <TextColorButton first v-tooltip="$t('toolbar.textColor')" :color="textAttrs.color">
          <i-icon-park-outline:text />
        </TextColorButton>
      </Popover>
      <Popover trigger="click" style="width: 50%;">
        <template #content>
          <ColorPicker
            :modelValue="textAttrs.backcolor"
            @update:modelValue="value => updateTextAttrs({ backcolor: value })"
          />
        </template>
        <TextColorButton last v-tooltip="$t('toolbar.cellFill')" :color="textAttrs.backcolor">
          <i-icon-park-outline:fill />
        </TextColorButton>
      </Popover>
    </ButtonGroup>

    <ButtonGroup class="row">
      <CheckboxButton 
        style="flex: 1;"
        :checked="textAttrs.bold"
        v-tooltip="$t('common.bold')"
        @click="updateTextAttrs({ bold: !textAttrs.bold })"
      ><i-icon-park-outline:text-bold /></CheckboxButton>
      <CheckboxButton 
        style="flex: 1;"
        :checked="textAttrs.em"
        v-tooltip="$t('common.italic')"
        @click="updateTextAttrs({ em: !textAttrs.em })"
      ><i-icon-park-outline:text-italic /></CheckboxButton>
      <CheckboxButton 
        style="flex: 1;"
        :checked="textAttrs.underline"
        v-tooltip="$t('common.underline')"
        @click="updateTextAttrs({ underline: !textAttrs.underline })"
      ><i-icon-park-outline:text-underline /></CheckboxButton>
      <CheckboxButton 
        style="flex: 1;"
        :checked="textAttrs.strikethrough"
        v-tooltip="$t('common.strikethrough')"
        @click="updateTextAttrs({ strikethrough: !textAttrs.strikethrough })"
      ><i-icon-park-outline:strikethrough /></CheckboxButton>
    </ButtonGroup>

    <RadioGroup 
      class="row" 
      button-style="solid" 
      :value="textAttrs.align"
      @update:value="value => updateTextAttrs({ align: value as TextAlign })"
    >
      <RadioButton value="left" v-tooltip="$t('common.leftAlign')" style="flex: 1;"><i-icon-park-outline:align-text-left /></RadioButton>
      <RadioButton value="center" v-tooltip="$t('common.centerAlign')" style="flex: 1;"><i-icon-park-outline:align-text-center /></RadioButton>
      <RadioButton value="right" v-tooltip="$t('common.rightAlign')" style="flex: 1;"><i-icon-park-outline:align-text-right /></RadioButton>
      <RadioButton value="justify" v-tooltip="$t('common.justify')" style="flex: 1;"><i-icon-park-outline:align-text-both /></RadioButton>
    </RadioGroup>

    <RadioGroup 
      class="row" 
      button-style="solid" 
      :value="textAttrs.vAlign"
      @update:value="value => updateTextAttrs({ vAlign: value as TextAlignVertical })"
    >
      <RadioButton value="top" v-tooltip="$t('common.topAlign')" style="flex: 1;"><i-icon-park-outline:align-text-top-one /></RadioButton>
      <RadioButton value="middle" v-tooltip="$t('common.verticalCenter')" style="flex: 1;"><i-icon-park-outline:align-text-middle-one /></RadioButton>
      <RadioButton value="bottom" v-tooltip="$t('common.bottomAlign')" style="flex: 1;"><i-icon-park-outline:align-text-bottom-one /></RadioButton>
    </RadioGroup>

    <Divider />

    <ElementOutline :fixed="true" />

    <Divider />

    <div class="row">
      <div style="width: 40%;">{{ $t('tableStyle.rowActions') }}</div>
      <ButtonGroup style="width: 60%;" passive>
        <Button first style="flex: 1;" @click="emitTableCommand('insert-row', 'after')">{{ $t('tableStyle.addRow') }}</Button>
        <Popover trigger="click">
          <template #content>
            <PopoverMenuItem center @click="emitTableCommand('insert-row', 'before')">{{ $t('tableStyle.addAbove') }}</PopoverMenuItem>
            <PopoverMenuItem center @click="emitTableCommand('insert-row', 'after')">{{ $t('tableStyle.addBelow') }}</PopoverMenuItem>
            <PopoverMenuItem center @click="emitTableCommand('delete-row')">{{ $t('table.deleteRow') }}</PopoverMenuItem>
          </template>
          <Button last class="popover-btn"><i-icon-park-outline:down /></Button>
        </Popover>
      </ButtonGroup>
    </div>
    <div class="row">
      <div style="width: 40%;">{{ $t('tableStyle.columnActions') }}</div>
      <ButtonGroup style="width: 60%;" passive>
        <Button first style="flex: 1;" @click="emitTableCommand('insert-col', 'after')">{{ $t('tableStyle.addColumn') }}</Button>
        <Popover trigger="click">
          <template #content>
            <PopoverMenuItem center @click="emitTableCommand('insert-col', 'before')">{{ $t('tableStyle.addLeft') }}</PopoverMenuItem>
            <PopoverMenuItem center @click="emitTableCommand('insert-col', 'after')">{{ $t('tableStyle.addRight') }}</PopoverMenuItem>
            <PopoverMenuItem center @click="emitTableCommand('delete-col')">{{ $t('table.deleteColumn') }}</PopoverMenuItem>
          </template>
          <Button last class="popover-btn"><i-icon-park-outline:down /></Button>
        </Popover>
      </ButtonGroup>
    </div>

    <Divider />

    <div class="row theme-switch">
      <div style="width: 40%;">{{ $t('tableStyle.enableTheme') }}</div>
      <div class="switch-wrapper" style="width: 60%;">
        <Switch 
          :value="hasTheme" 
          @update:value="value => toggleTheme(value)" 
        />
      </div>
    </div>

    <template v-if="theme">
      <div class="row">
        <Checkbox 
          @update:value="value => updateTheme({ rowHeader: value })" 
          :value="theme.rowHeader" 
          style="flex: 1;"
        >{{ $t('tableStyle.headerRow') }}</Checkbox>
        <Checkbox 
          @update:value="value => updateTheme({ rowFooter: value })" 
          :value="theme.rowFooter" 
          style="flex: 1;"
        >{{ $t('tableStyle.totalRow') }}</Checkbox>
      </div>
      <div class="row">
        <Checkbox 
          @update:value="value => updateTheme({ colHeader: value })" 
          :value="theme.colHeader" 
          style="flex: 1;"
        >{{ $t('tableStyle.firstColumn') }}</Checkbox>
        <Checkbox 
          @update:value="value => updateTheme({ colFooter: value })" 
          :value="theme.colFooter" 
          style="flex: 1;"
        >{{ $t('tableStyle.lastColumn') }}</Checkbox>
      </div>
      <div class="row">
        <div style="width: 40%;">{{ $t('tableStyle.themeColor') }}</div>
        <Popover trigger="click" style="width: 60%;">
          <template #content>
            <ColorPicker
              :modelValue="theme.color"
              @update:modelValue="value => updateTheme({ color: value })"
            />
          </template>
          <ColorButton :color="theme.color" />
        </Popover>
      </div>
    </template>
  </div>
</template>

<script lang="ts" setup>
import { computed, onMounted, ref, watch } from 'vue'
import { storeToRefs } from 'pinia'
import { useMainStore, useSlidesStore } from '@/store'
import type { PPTTableElement, TableCell, TableCellStyle, TableTheme, TextAlign, TextAlignVertical } from '@/types/slides'
import useLocalizedFonts from '@/hooks/useLocalizedFonts'
import emitter, { EmitterEvents, type TableCommand } from '@/utils/emitter'
import useHistorySnapshot from '@/hooks/useHistorySnapshot'

import ElementOutline from '../common/ElementOutline.vue'
import ColorButton from '@/components/ColorButton.vue'
import TextColorButton from '@/components/TextColorButton.vue'
import CheckboxButton from '@/components/CheckboxButton.vue'
import ColorPicker from '@/components/ColorPicker/index.vue'
import Divider from '@/components/Divider.vue'
import Switch from '@/components/Switch.vue'
import Checkbox from '@/components/Checkbox.vue'
import Button from '@/components/Button.vue'
import ButtonGroup from '@/components/ButtonGroup.vue'
import RadioButton from '@/components/RadioButton.vue'
import RadioGroup from '@/components/RadioGroup.vue'
import Select from '@/components/Select.vue'
import SelectGroup from '@/components/SelectGroup.vue'
import Popover from '@/components/Popover.vue'
import PopoverMenuItem from '@/components/PopoverMenuItem.vue'

const slidesStore = useSlidesStore()
const { handleElement, handleElementId, selectedTableCells: selectedCells } = storeToRefs(useMainStore())
const fontOptions = useLocalizedFonts()
const themeColor = computed(() => slidesStore.theme.themeColors[0])

const fontSizeOptions = [
  '12px', '14px', '16px', '18px', '20px', '22px', '24px', '28px', '32px',
]

const textAttrs = ref({
  bold: false,
  em: false,
  underline: false,
  strikethrough: false,
  color: '#000',
  backcolor: '',
  fontsize: '12px',
  fontname: '',
  align: 'left',
  vAlign: 'top',
})

const theme = ref<TableTheme>()
const hasTheme = ref(false)

watch(handleElement, () => {
  if (!handleElement.value || handleElement.value.type !== 'table') return
  
  theme.value = handleElement.value.theme
  hasTheme.value = !!theme.value
}, { deep: true, immediate: true })

const { addHistorySnapshot } = useHistorySnapshot()

// 更新当前选中单元格的文本样式状态
const updateTextAttrState = () => {
  if (!handleElement.value || handleElement.value.type !== 'table') return

  let rowIndex = 0
  let colIndex = 0
  if (selectedCells.value.length) {
    const selectedCell = selectedCells.value[0]
    rowIndex = +selectedCell.split('_')[0]
    colIndex = +selectedCell.split('_')[1]
  }
  const style = handleElement.value.data[rowIndex][colIndex].style

  if (!style) {
    textAttrs.value = {
      bold: false,
      em: false,
      underline: false,
      strikethrough: false,
      color: '#000',
      backcolor: '',
      fontsize: '12px',
      fontname: '',
      align: 'left',
      vAlign: 'top',
    }
  }
  else {
    textAttrs.value = {
      bold: !!style.bold,
      em: !!style.em,
      underline: !!style.underline,
      strikethrough: !!style.strikethrough,
      color: style.color || '#000',
      backcolor: style.backcolor || '',
      fontsize: style.fontsize || '12px',
      fontname: style.fontname || '',
      align: style.align || 'left',
      vAlign: style.vAlign || 'top',
    }
  }
}

onMounted(() => {
  updateTextAttrState()
})

watch(selectedCells, updateTextAttrState)

const updateElement = (props: Partial<PPTTableElement>) => {
  slidesStore.updateElement({ id: handleElementId.value, props })
  addHistorySnapshot()
}

// 设置单元格内容文本样式
const updateTextAttrs = (textAttrProp: Partial<TableCellStyle>) => {
  const _handleElement = handleElement.value as PPTTableElement

  const data: TableCell[][] = JSON.parse(JSON.stringify(_handleElement.data))

  for (let i = 0; i < data.length; i++) {
    for (let j = 0; j < data[i].length; j++) {
      if (!selectedCells.value.length || selectedCells.value.includes(`${i}_${j}`)) {
        const style = data[i][j].style || {}
        data[i][j].style = { ...style, ...textAttrProp }
      }
    }
  }
  updateElement({ data })
  updateTextAttrState()
}

// 更新表格主题：主题色、标题行、汇总行、第一列、最后一列
const updateTheme = (themeProp: Partial<TableTheme>) => {
  if (!theme.value) return
  const _theme = { ...theme.value, ...themeProp }
  updateElement({ theme: _theme })
}

// 开启/关闭表格主题
const toggleTheme = (checked: boolean) => {
  if (checked) {
    const props = {
      theme: {
        color: themeColor.value,
        rowHeader: true,
        rowFooter: false,
        colHeader: false,
        colFooter: false,
      }
    }
    updateElement(props)
  }
  else {
    slidesStore.removeElementProps({ id: handleElementId.value, propName: 'theme' })
    addHistorySnapshot()
  }
}

const emitTableCommand = (command: TableCommand['command'], position?: TableCommand['position']) => {
  emitter.emit(EmitterEvents.TABLE_COMMAND, {
    targetId: handleElementId.value,
    command,
    position,
  })
}
</script>

<style lang="scss" scoped>
.row {
  width: 100%;
  display: flex;
  align-items: center;
  margin-bottom: 10px;
}
.theme-switch {
  margin-bottom: 18px;
}
.switch-wrapper {
  text-align: right;
}
.popover-btn {
  width: 32px;
  padding: 0 3px;
}
</style>
