// apps/web/src/features/editor/VideoStylePanel.tsx
import { useTranslation } from 'react-i18next'

import PlusIcon from '~icons/icon-park-outline/plus'
import ScreenshotIcon from '~icons/icon-park-outline/screenshot-one'
import UndoIcon from '~icons/icon-park-outline/undo'
import type { PPTVideoElement } from '@mona/presentation-core/model'

import { Button } from '@/components/ui/button'
import { InspectorSwitch, inspectorDividerClass, inspectorRowClass } from '@/features/editor/EditorInspectorPrimitives'
import { PropertyRow } from '@/features/editor/ElementStyleCommons'
import type { EditorRuntime } from '@/features/editor/editor-runtime'
import { PRESENTATION_FILTERS, pickFile } from '@/features/editor/editor-files'

const fileAsDataUrl = (file: File) => new Promise<string>((resolve, reject) => {
  const reader = new FileReader()
  reader.onload = () => typeof reader.result === 'string' ? resolve(reader.result) : reject(new TypeError('Expected an image data URL'))
  reader.onerror = () => reject(reader.error)
  reader.readAsDataURL(file)
})

export function VideoStylePanel({ element, runtime }: { element: PPTVideoElement; runtime: EditorRuntime }) {
  const { t } = useTranslation()
  const update = (props: Partial<PPTVideoElement>) => runtime.commit('Update video style', [{
    type: 'element.update',
    payload: { id: element.id, props },
  }])
  const setPoster = async () => {
    const file = await pickFile(PRESENTATION_FILTERS.image, { title: t('foundation.editor.media.videoPoster') })
    if (file) update({ poster: await fileAsDataUrl(file) })
  }
  const setPosterFromFirstFrame = () => {
    const canvas = document.createElement('canvas')
    const context = canvas.getContext('2d')
    const video = document.createElement('video')
    video.crossOrigin = 'anonymous'
    video.preload = 'metadata'
    video.muted = true
    video.playsInline = true
    video.addEventListener('error', () => update({ poster: '' }))
    video.addEventListener('loadedmetadata', () => {
      video.requestVideoFrameCallback(() => {
        canvas.width = video.videoWidth
        canvas.height = video.videoHeight
        context?.drawImage(video, 0, 0, canvas.width, canvas.height)
        update({ poster: canvas.toDataURL('image/jpeg', .8) })
        video.remove()
        canvas.remove()
      })
    }, { once: true })
    video.src = element.src
  }
  return (
    <div className="text-control text-foreground select-none">
      <div className="mb-2.5">{t('foundation.editor.media.videoPoster')}</div>
      <div className="mb-2.5">
        <Button className="relative block h-0 w-full rounded-control border border-dashed p-0 pb-[56.25%] transition-all hover:border-foreground hover:text-foreground" onClick={() => { void setPoster() }} type="button" variant="ghost">
          <span className="absolute inset-0 flex items-center justify-center bg-contain bg-center bg-no-repeat" style={{ backgroundImage: element.poster ? `url(${element.poster})` : '' }}><PlusIcon /></span>
        </Button>
      </div>
      <div className={inspectorRowClass}>
        <Button className="w-full flex-1" onClick={setPosterFromFirstFrame} size="editor" type="button" variant="editor"><ScreenshotIcon /> {t('foundation.editor.media.firstFramePoster')}</Button>
      </div>
      {element.poster ? (
        <div className={inspectorRowClass}>
          <Button className="w-full flex-1" onClick={() => update({ poster: '' })} size="editor" type="button" variant="editor"><UndoIcon /> {t('foundation.editor.media.resetPoster')}</Button>
        </div>
      ) : null}
      <div className={inspectorDividerClass} />
      <PropertyRow label={t('foundation.editor.media.autoplay')}>
        <div className="w-full text-right">
          <InspectorSwitch ariaLabel={t('foundation.editor.media.autoplay')} checked={element.autoplay} onChange={autoplay => update({ autoplay })} />
        </div>
      </PropertyRow>
    </div>
  )
}

// src/views/Editor/Toolbar/ElementStylePanel/VideoStylePanel.vue
<template>
  <div class="video-style-panel">
    <div class="title">{{ $t('elementStyle.videoPoster') }}</div>
    <div class="background-image-wrapper">
      <FileInput @change="files => setVideoPoster(files)">
        <div class="background-image">
          <div class="content" :style="{ backgroundImage: handleVideoElement.poster ? `url(${handleVideoElement.poster})` : '' }">
            <i-icon-park-outline:plus />
          </div>
        </div>
      </FileInput>
    </div>
    <div class="row">
      <Button style="flex: 1;" @click="setVideoPosterFromFirstFrame()"><i-icon-park-outline:screenshot-one /> {{ $t('elementStyle.firstFramePoster') }}</Button>
    </div>
    <div class="row" v-if="handleVideoElement.poster">
      <Button style="flex: 1;" @click="updateVideo({ poster: '' })"><i-icon-park-outline:undo /> {{ $t('elementStyle.resetPoster') }}</Button>
    </div>

    <Divider />

    <div class="row switch-row">
      <div style="width: 40%;">{{ $t('elementStyle.autoplay') }}</div>
      <div class="switch-wrapper" style="width: 60%;">
        <Switch 
          :value="handleVideoElement.autoplay" 
          @update:value="value => updateVideo({ autoplay: value })" 
        />
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import type { Ref } from 'vue'
import { storeToRefs } from 'pinia'
import { useMainStore, useSlidesStore } from '@/store'
import type { PPTVideoElement } from '@/types/slides'
import { getImageDataURL } from '@/utils/image'
import useHistorySnapshot from '@/hooks/useHistorySnapshot'

import FileInput from '@/components/FileInput.vue'
import Button from '@/components/Button.vue'
import Switch from '@/components/Switch.vue'
import Divider from '@/components/Divider.vue'

const slidesStore = useSlidesStore()
const { handleElement } = storeToRefs(useMainStore())

const handleVideoElement = handleElement as Ref<PPTVideoElement>

const { addHistorySnapshot } = useHistorySnapshot()

const updateVideo = (props: Partial<PPTVideoElement>) => {
  if (!handleElement.value) return
  slidesStore.updateElement({ id: handleElement.value.id, props })
  addHistorySnapshot()
}

// 设置视频预览封面
const setVideoPoster = (files: FileList) => {
  const imageFile = files[0]
  if (!imageFile) return
  getImageDataURL(imageFile).then(dataURL => updateVideo({ poster: dataURL }))
}

// 获取视频首帧作为预览封面
const setVideoPosterFromFirstFrame = () => {
  const canvas = document.createElement('canvas')
  const ctx = canvas.getContext('2d')

  const video = document.createElement('video')
  video.crossOrigin = 'anonymous'
  video.preload = 'metadata'
  video.muted = true
  video.playsInline = true

  video.addEventListener('error', () => {
    updateVideo({ poster: '' })
  })

  video.addEventListener('loadedmetadata', () => {
    video!.requestVideoFrameCallback(() => {
      canvas.width = video.videoWidth
      canvas.height = video.videoHeight
      ctx!.drawImage(video, 0, 0, canvas.width, canvas.height)

      const poster = canvas.toDataURL('image/jpeg', 0.8)
      video.remove()
      canvas.remove()
      updateVideo({ poster })
    })
  }, { once: true })

  video.src = handleVideoElement.value.src
}
</script>

<style lang="scss" scoped>
.row {
  width: 100%;
  display: flex;
  align-items: center;
  margin-bottom: 10px;
}
.title {
  margin-bottom: 10px;
}
.background-image-wrapper {
  margin-bottom: 10px;
}
.background-image {
  height: 0;
  padding-bottom: 56.25%;
  border: 1px dashed $borderColor;
  border-radius: $borderRadius;
  position: relative;
  transition: all $transitionDelay;

  &:hover {
    border-color: $themeColor;
    color: $themeColor;
  }

  .content {
    @include absolute-0();

    display: flex;
    justify-content: center;
    align-items: center;
    background-position: center;
    background-size: contain;
    background-repeat: no-repeat;
    cursor: pointer;
  }
}
.switch-row {
  height: 32px;
}
.switch-wrapper {
  text-align: right;
}
</style>
